### PR TITLE
Display test detail when clicking patient name on results pg (#3601)

### LINKED ISSUE #3601: Make patient names on the Results page clickable to view their test result information
### Background
On the results page, viewing a patients full breadth of test result data is hidden away in the Actions ellipses button as "View details". This keeps valuable information hidden away for our users when this information should be more easily accessible and discoverable.

We propose making the patient's name clickable, taking users to the "View details" modal.

### Design

**BEFORE CLICKING ON A PATIENT'S NAME:**

**AFTER CLICKING ON A PATIENT'S NAME:**

### Acceptance Criteria

- [ ] Turn patient names into clickable hyperlinks using USWDS's existing design pattern for hyperlink text
- [ ] Clicking on a patient name should open the "View details" modal

### PR DESCRIPTION
**Pull request by emyl3**
# FRONTEND PULL REQUEST

## Related Issue
Fixes #3601 
This change helps make the "Test details" modal more discoverable.

## Changes Proposed
- On the "Results" tab, an org administrator should be able to click the patient's name and view the details of the test result in a modal.

## Additional Information
@kenieh had an open question in the issue about whether or not we want to remove the "View details" button in the Actions menu.

## Testing
1. Log in as an org admin.
2. Go to the "Results" page
3. Have at least one result
4. Click on the user's name and it should open the "Test details" modal
 
## Screenshots / Demos
Screen Shot 2022-05-13 at 4 07 10 PM
Screen Shot 2022-05-13 at 4 08 45 PM

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### CODE REVIEW

**Review by emmastephenson — COMMENTED** [review]
Looks great Elisa, thank you!!

One thing before I approve - could you fill out the PR description? Tagging the issue with "Fixes #3601" is generally how we link tickets to PRs; Github will auto-close the issue when the PR is merged that way. Would also appreciate if you could add a little video/screenshot to demo the new behavior. Thank you!

**Comment by emyl3** [comment]
> Looks great Elisa, thank you!!
> 
> One thing before I approve - could you fill out the PR description? Tagging the issue with "Fixes #3601" is generally how we link tickets to PRs; Github will auto-close the issue when the PR is merged that way. Would also appreciate if you could add a little video/screenshot to demo the new behavior. Thank you!

Oh no! I made changes to the description but I guess I never said them in a different tab I was making them in 😮‍💨 Will update that again 😅

**Comment by emyl3** [comment]
@emmastephenson Ready for review again! Sorry for making you review it twice! 😓

**Comment by emmastephenson** [comment]
@emyl3 no worries! I've done the same thing with too many Github tabs 😄

**Review by emmastephenson — APPROVED** [review]
Looks great, thank you Elisa!

**Review by fzhao99 — APPROVED** [review]

**Review by fzhao99 — APPROVED** [review]
🚢

**Review by johanna-skylight — APPROVED** [review]
LGTM

**Review by nickclyde — DISMISSED** [review]

**Comment by kenieh** [comment]
Not sure if we should remove "View details" from the "Actions" menu. Would it be possible to add analytics of some sort to understand how often people are clicking on the patient's name vs. the "View details" menu option?

**Comment by emmastephenson** [comment]
@kenieh we can, but would you mind making a new ticket for the analytics? I'd prefer to keep this change small.

**Comment by kenieh** [comment]
@emmastephenson sure thing!

**Review by fzhao99 — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]

**Review by kenieh — APPROVED** [review]
LGTM

**Pull request merged**
