### PR TITLE
rollback without throwing error due to permissions issue

### PR DESCRIPTION
**Pull request by alismx**
# DEVOPS/DATABASE PULL REQUEST

## Related Issue

- Fix database rollbacks #5110 

## Changes Proposed

- adjust indentation on github action to match usage in other parts of the file.
- add some output to the rollback job with helpful info
- update dockerfile to ensure proper user permissions
- update docker-compose usage to docker compose

## Testing

- [failed rollback](https://github.com/CDCgov/prime-simplereport/actions/runs/3944240823/jobs/6749948755) - check "Display logs"
- [passing rollback](https://github.com/CDCgov/prime-simplereport/actions/runs/3991006557/jobs/6845904653) - check "Display logs" 
- [docker compose usage works](https://github.com/CDCgov/prime-simplereport/actions/runs/3991006557/jobs/6845885802) - check "Build and push Docker images"

### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
Changes look great to me, thanks Alis!

**Review by emyl3 — APPROVED** [review]
LGTM!

**Review by zdeveloper — CHANGES_REQUESTED** [review]
Code changes looks good to me, but the behavior is not ideal. we dont want false positives
in the example you shared
 

> [failed rollback](https://github.com/CDCgov/prime-simplereport/actions/runs/3944240823/jobs/6749948755) - check "Display logs"

the rollback failed, but the check passed, which is certainly not the behavior that we want

**Review by rin-skylight — APPROVED** [review]

**Comment by alismx** [comment]
@zdeveloper [Created that ticket.](https://app.zenhub.com/workspaces/simplereport-eng-health-61127bc8b61cae0013456681/issues/gh/cdcgov/prime-simplereport/5111)

**Review by zdeveloper — APPROVED** [review]

**Pull request merged**
