### PR TITLE
Add training site banner and modal

### PR DESCRIPTION
**Pull request by nickscialli-usds**
## Related Issue or Background Info

- #973 

## Changes Proposed

- Add a `TrainingNotification` component that renders if `process.env.REACT_APP_IS_TRAINING_SITE === "true"`
- Tests that this displays/doesn't display in the appropriate environments
- Based on discussion with design folks, uses session storage to remember if the user has acknowledge the modal (documented in the discussion of the ticket)

## Screenshot

Training notifications

### CODE REVIEW

**Comment by nickscialli-usds** [comment]
@katiealoisi I can't push this to an environment for you to validate since it'll only work in the training environment, so hopefully the screenshot of it working locally will suffice

**Comment by hmyers-cms** [comment]
LGTM

**Comment by maya** [comment]
Can we use the [site alert component](https://designsystem.digital.gov/components/site-alert/) rather than the standard alert? The vertical border doesn't really work on a full-width notice.

Do we need the orange "design work in progress" tag at the top or will that come later?

**Comment by nickscialli-usds** [comment]
@maya 

>Can we use the site alert component rather than the standard alert? The vertical border doesn't really work on a full-width notice.

Yes, didn't know that existed

>Do we need the orange "design work in progress" tag at the top or will that come later?

I assumed the "design work in progress" was just an artifact from the design prototype and not supposed to display on the actual app

**Comment by katiealoisi** [comment]
LGTM too! You're right @nickscialli-usds, the "design work in progress" is an artifact from the prototype and should not display.

**Comment by maya** [comment]
Is it bc of the react modal component we're using that I can't exit using my escape key?

**Comment by maya** [comment]
Updated to use the USWDS site alert in 2d2ad32. Updated the modal heading type treatment to more closely match the Figma designs in abb5829.

Screen Shot 2021-03-24 at 1 51 52 PM

The only thing I'm currently unsure about is the button placement: right-aligned instead of left on this wide modal.

**Review by maya — APPROVED** [review]
Approve all the front-end work 🚀 

Though I can't speak to the more complex React stuff and tests b/c it's not in my expertise in case you need another eye.

**Review by timothybest-usds — APPROVED** [review]

**Pull request merged**
