### PR TITLE
Johanna/6685 improve facility selector

### LINKED ISSUE #6685: [FE] Improve facility selector on sign in
## Why should we do this?
The facility selector is difficult to use for organizations with a large number of facilities. 

## Action Requested
Replace the facility selector with a combo box for orgs with many facilities. 

## Acceptance Criteria
- Replace buttons with combo box
- typing in combo box will filter to matching results in drop-down
- Facilities should be in alphabetical order
- Selector only appears when the URL doesn't contain a facility. 2 cases where this happens:
  - if org has only 1 facility, URL will automatically get populated with that facility
  - if a user has already selected a facility, we keep that context in the URL for the session
- if no facility selected, 'Continue' button is disabled and greyed out
- Review final changes with design (Ryan or Kenny) prior to pushing to production.
  - test with really long facility name and see how page looks, get approval from design

## Additional Context
Figma [[URL](https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=3723%3A7842&mode=design&t=HeWFnwLv0g2ApeqF-1)]

Review with design to see if we want a different solution for smaller orgs, padding, etc. 
via **Laura King**: We won’t be able to pre-fill the combo box with the last selected facility, as this selector only appears when they’re loading a URL without a facility name and we don’t have a way of knowing last used (this is based on feedback from the BD team in our last refinement).

Current Experience screenshot is attached for reference.

Image

### PR DESCRIPTION
**Pull request by johanna-skylight**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #6685 

## Changes Proposed

- Modify select facility component to use combobox.
- Update styling to match the new designs.

## Additional Information
No facility page shared the styling with the facility select page so I have updated it as well. @nickisblake has been notified and has approved.

## Testing
Verify the pages looks good for below scenarios:

- Sign in with a url that has no facility id.
- Sign in with a user that has no facilities assigned.

## Screenshots / Demos
No facility selected.
Screenshot 2023-10-16 at 12 03 42 PM

After choosing a facility.
Screenshot 2023-10-16 at 12 03 37 PM

No facility warning also updated to match the new style.
Screenshot 2023-10-18 at 9 24 35 AM

### CODE REVIEW

**Review by fzhao99 — DISMISSED** [review]
verified locally and lgtm!

**Review by emyl3 — APPROVED** [review]
LGTM!!! Thank you for this change! 😸 

There is one thing I noticed unrelated to your change
But when a user has no facilities that page title has only a generic page title of "SimpleReport" -- we should probably update that. cc @jayna-SkylightDigital @mehansen 
Screenshot 2023-10-18 at 08 51 23

**Comment by johanna-skylight** [comment]
> LGTM!!! Thank you for this change! 😸
> 
> There is one thing I noticed unrelated to your change But when a user has no facilities that page title has only a generic page title of "SimpleReport" -- we should probably update that. cc @jayna-SkylightDigital @mehansen Screenshot 2023-10-18 at 08 51 23

I also feel this needs to be addressed. I have added `No facility access access` as a page title. Let me know if this works or if you need me to reach out to Laura Kerry. @jayna-SkylightDigital.

**Review by fzhao99 — APPROVED** [review]

**Comment by johanna-skylight** [comment]
@nickisblake  I have updated the copy of the `No facility access` page. Please see screenshot in the description of the PR.

**Pull request merged**
