### PR TITLE
Add Spotless gradle plugin to backend

### PR DESCRIPTION
**Pull request by jeskew-gov**
## Related Issue or Background Info

- Based on some discussion in https://github.com/CDCgov/prime-simplereport/pull/509#pullrequestreview-564318111; also moves us towards #694.

## Changes Proposed

- Add the Spotless gradle plugin and configure it to apply Google Java Format
- Replaces all tabs with four spaces in `build.gradle`. (We were using a mixture in that file, and Spotless will not, alas, enforce formatting conventions on .gradle files, at least not with the configuration proposed in this PR.)

## Additional Information

- ~~Spotless "ratchets" from `origin/main`, meaning it will only check or format files that have been changed from the `main` branch. This will prevent one single commit from changing the format of every Java file, but it has the side effect that `gradle build` will probably fail when you make a small tweak to a Java file until you run `gradle spotlessApply`~~
- ~~I suspect that we will be making great use of GitHub's "Hide whitespace changes" diff setting going forward. Try it out on this PR!~~
- The last commit on this PR applies the formatter to the whole backend codebase. It's easiest to go commit by commit so that you can skip the last one.
- `./gradlew build` will fail if the code format is not correct. Run `./gradlew spotlessApply` to run the autoformatter.

### CODE REVIEW

**Comment by benwarfield-usds** [comment]
I disagree with the part of this plan that says we will all just have to deal with randomly large whitespace-only changes periodically for the next however many months--the point of the way we've been (allegedly) working on this for the last bit has been to avoid that and try to have new code gradually achieve critical mass (then nuke tabs as appropriate in individual files). 

On the other hand it is fair to say that the desired ratchet has not been especially effective.

I do agree that having ruthless  mechanical enforcement is the only way to do have a strict style guide--I just prefer not having one, and letting people format their code how they like, within some reasonable (indentation-related) sanity checks.

**Comment by jeskew-gov** [comment]
@benwarfield-usds Would it maybe cause less disruption to migrate the whole backend code base in one go? I can remove the `ratchetFrom` configuration and reformat all files in a separate commit attributed to `nobody@cdc.gov`; that would make this PR much larger, but it would effectively eliminate style-only changes in future PRs.

**Review by ClydeDroid — APPROVED** [review]
Thanks for adding this! I am highly in favor of having enforced styles, even as pre-commit hooks - it generally saves a ton of dev time to not have to worry about formatting, etc.
Looks like there is a vscode integration for spotless as well!
https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-spotless-gradle

**Comment by benwarfield-usds** [comment]
Woooo merge conflicts! (This somewhat illustrates why this has continued to be an issue, honestly...)

I'd rather rip the bandaid off, yeah—possibly in slightly more commits than one huge one,  just because of the number of in-flight branches we tend to have, but if we're going to reformat everything, let's just reformat everything.

**Comment by jeskew-gov** [comment]
> Woooo merge conflicts! (This somewhat illustrates why this has continued to be an issue, honestly...)
> 
> I'd rather rip the bandaid off, yeah—possibly in slightly more commits than one huge one, just because of the number of in-flight branches we tend to have, but if we're going to reformat everything, let's just reformat everything.

Yeah, until this lands in `main`, I suspect I will need to remove the last commit, rebase over `main`, and rerun `gradle spotlessApply` after each PR merge.

**Pull request merged**
