### PR TITLE
Adding to merge queue triggers required branch protection checks

### PR DESCRIPTION
**Pull request by mehansen**
# DEVOPS PULL REQUEST

## Related Issue

We want to use a merge queue when merging to main. Once a PR is in the merge queue, it will be put in a merge group (potentially with other PRs, but unlikely if we configure it to require a minimum of 1 PR to start a merge operation). A merge group will only be merged once all required branch protection checks pass, so we have to trigger the workflows that run jobs that have the required checks.
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues

## Changes Proposed

Trigger workflows with required checks on the [merge_groups](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group) event 

## Testing

Tough to test without me turning on the merge queue functionality first. But the merge queue won't work if we don't add these triggers.

### CODE REVIEW

**Review by alismx — CHANGES_REQUESTED** [review]
Merge queues are new to me, but I love that we can do this.

Do we need to add this `merge_group` to the `CodeQL`, `tfsec`, and `Dependabot Create Issue` workflows, too?

**Comment by mehansen** [comment]
> Merge queues are new to me, but I love that we can do this.
> 
> Do we need to add this `merge_group` to the `CodeQL`, `tfsec`, and `Dependabot Create Issue` workflows, too?

I don't think so. None of those workflows complete checks that are required to merge to `main`. The workflows you listed would still run on pull requests so not sure we need them to run again on the temporary branch generated by the merge queue.

**Comment by alismx** [comment]
> > Merge queues are new to me, but I love that we can do this.
> > Do we need to add this `merge_group` to the `CodeQL`, `tfsec`, and `Dependabot Create Issue` workflows, too?
> 
> I don't think so. None of those workflows complete checks that are required to merge to `main`. The workflows you listed would still run on pull requests so not sure we need them to run again on the temporary branch generated by the merge queue.



> > Merge queues are new to me, but I love that we can do this.
> > Do we need to add this `merge_group` to the `CodeQL`, `tfsec`, and `Dependabot Create Issue` workflows, too?
> 
> I don't think so. None of those workflows complete checks that are required to merge to `main`. The workflows you listed would still run on pull requests so not sure we need them to run again on the temporary branch generated by the merge queue.

Hmm, `tfsec` should probably be required to merge, but since it isn't at the moment, this PR LGTM.

**Review by alismx — APPROVED** [review]

**Review by BobanL — APPROVED** [review]
🥇

**Pull request merged**
