### PR TITLE
Revert "Send multiplex results to patient experience frontend"

### PR DESCRIPTION
**Pull request by nickclyde**
Reverts CDCgov/prime-simplereport#3788

Seeing this error at `PatientExperienceController.java:76`

image

### CODE REVIEW

**Review by zdeveloper — APPROVED** [review]
LGTM! will put it back after we figure out this line is causing errors to be thrown.
`PatientExperienceController.java`

`    Result covidResult = testEvent.getResultForDisease(_diseaseService.covid()).orElseThrow();`

**Review by zdeveloper — DISMISSED** [review]
One thing I just remembered is that this was put in place to break some of the infinite loops we had when jsonifying the audit log. we might wanna put that piece back by itself after taking this out, namely the JSON ignores

**Review by zdeveloper — APPROVED** [review]
added the `@JsonIgnore` back in

**Review by emmastephenson — APPROVED** [review]

**Review by DanielSass — APPROVED** [review]

**Comment by emmastephenson** [comment]
I think I figured out what's causing the pxp issues here, will fix in another PR but wanted to leave some notes here.

It looks like this is only happening with corrected tests - the patient link points at a TestOrder with a correction_status of `REMOVED`. That TestOrder in turn references a TestEvent which also has a `REMOVED` correction_status. The Result, however, points at the TestOrder and a _different_ TestEvent with an `ORIGINAL` status, which is why we're seeing NPE - we attempt to look up the TestEvent with the REMOVED status, and it doesn't exist in the Results table. 

@nathancrtr, I am not super familiar with the corrections workflow so going to pass a couple of questions your way - let me know if you'd prefer to chat over Zoom instead.
- Which is the canonical TestEvent that should be referenced as the source of truth? The one with the REMOVED status, or the one with an ORIGINAL status? (I assumed REMOVED would mean that the TestEvent is bad, but maybe I have that backwards?)
- Does the TestEvent that was corrected become an orphan, without a TestOrder reference? Do we ever need to find it again? Asking because I'm not sure if the best move here is to create a new entry in the Result table holding the new TestEvent / old TestOrder, or if we should instead update the existing row in the Result table to point to the new TestEvent instead of the old one.

**Comment by emmastephenson** [comment]
Also @zdeveloper thank you for catching the `@JsonIgnores`! They're why I pushed this PR so quickly in the first place, even without attempting to read the specific diseases the audit log starts hitting a recursion loop without those.

**Pull request merged**
