### PR TITLE
Upgrades to testing facilities column in the results page

### PR DESCRIPTION
**Pull request by johanna-skylight**
# FRONTEND PULL REQUEST

## Related Issue

Fixes [3691](https://github.com/CDCgov/prime-simplereport/issues/3691)

## Changes Proposed

- Results table logic now accepts the flag displayFacility. When this flag is true the Facility Column will be visible and when is false the column will be hidden.
- The column header got renamed to Facility
- The flag displayFacilityColumn was added to the main view/component.

## Additional Information
No new test coverage was required.
I also moved the graphql queries out of the testResultList.tsx file and into their own file as the tsx file is getting too long. It should be considered if we want to adopt this (creating a specific file for a container component's queries) as a standard for the app.

## Testing
Load an account with multiple facilities. 
Select all facilities in the filter area and see that the column "Facility" displays in the table.
Select a facility and see that the column "Facility" column does not display.
 
## Screenshots / Demos
**all facilities**
Screen Shot 2022-05-24 at 3 51 29 PM

**testing facility**
Screen Shot 2022-05-24 at 3 51 19 PM

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### CODE REVIEW

**Comment by johanna-skylight** [comment]
Still waiting on fixes to the deploy workflow to test and get UX sign off but might as well get some engineering review started!

**Comment by johanna-skylight** [comment]
@kenieh This is ready for review in https://dev.simplereport.gov/

**Comment by kenieh** [comment]
@johanna-skylight this looks great for the COVID-only use case! Could I see a screenshot of the version of this with multiplex results too? Or is that still in development?

**Comment by johanna-skylight** [comment]
PR got messed up with merging conflicts

**Pull request closed without merging**
