### PR TITLE
Pin metabase version to v0.44.1.

### LINKED ISSUE #4153: Metabase loading issues
### Background
Metabase is not loading for some users, but this is intermittent - some loads still work fine.

### Action requested
@rin-skylight, this looks a lot like the pattern we saw before, when Metabase updated and some of our hosted instances had the new version while others didn't. I can't remember what the fix you took then was, but maybe we need to do it again? (Can confirm that there is a new version at least; they changed the UI implementation of filters)

### Acceptance Criteria
Metabase loads consistently

### PR DESCRIPTION
**Pull request by rin-skylight**
# DEVOPS PULL REQUEST

## Related Issue

- Resolves #4153.

## Changes Proposed

- Pins metabase to v0.44.1, which is the latest as of the time of this PR.

## Additional Information

- Metabase releases new versions fairly frequently...usually once every two weeks. It will likely be necessary to create a recurring action item to update metabase manually.
- We may wish to also consider expanding our CI/CD pipeline to automatically pull the latest metabase image, repackage it, and deploy it to our own registry for each environment. That would allow us to constantly receive automatic updates, but would ensure that all instances would be locked at a specific metabase version until we deliberately merge changes to `main`. The question is how much we value modernity over stability, as metabase can conceivably push breaking changes without our knowledge. I defer to our app-side technical leads for a judgment on which aspect is more important, especially given that metabase is production-facing. (My vote would be to pin to a specific version, and choose to update manually.)

## Testing

- Reviewers can deploy to any environment with metabase enabled, and can cross-check the presence of the correct image tag in Azure. I'm happy to provide guidance on this process, if needed!
 
### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Comment by emmastephenson** [comment]
> We may wish to also consider expanding our CI/CD pipeline to automatically pull the latest metabase image, repackage it, and deploy it to our own registry for each environment. That would allow us to constantly receive automatic updates, but would ensure that all instances would be locked at a specific metabase version until we deliberately merge changes to main. The question is how much we value modernity over stability, as metabase can conceivably push breaking changes without our knowledge. I defer to our app-side technical leads for a judgment on which aspect is more important, especially given that metabase is production-facing. (My vote would be to pin to a specific version, and choose to update manually.)

@rin-skylight my vote is actually the opposite 😄 I think we should integrate Metabase into our CI/CD pipeline and update versions on pushes to `main`. My thinking is as follows:
- Historically we're not great about these manual updates (** cough _Spring_ cough **). It just creates more work for someone, and it's hard to track
- We haven't seen breaking version updates from Metabase in the ~18 months we've been using it
- It's quasi-used in production, to the extent that we share some dashboards with external partners, but it's not seen by any SimpleReport end users.

@zdeveloper your thoughts?

**Review by emmastephenson — DISMISSED** [review]
That said I am fine to temporarily pin the version! Just want to make sure we agree about any follow-up work.

**Review by zdeveloper — DISMISSED** [review]
LGTM! Thank you!

**Comment by zdeveloper** [comment]
> > We may wish to also consider expanding our CI/CD pipeline to automatically pull the latest metabase image, repackage it, and deploy it to our own registry for each environment. That would allow us to constantly receive automatic updates, but would ensure that all instances would be locked at a specific metabase version until we deliberately merge changes to main. The question is how much we value modernity over stability, as metabase can conceivably push breaking changes without our knowledge. I defer to our app-side technical leads for a judgment on which aspect is more important, especially given that metabase is production-facing. (My vote would be to pin to a specific version, and choose to update manually.)
> 
> @rin-skylight my vote is actually the opposite smile I think we should integrate Metabase into our CI/CD pipeline and update versions on pushes to `main`. My thinking is as follows:
> 
> * Historically we're not great about these manual updates (** cough _Spring_ cough **). It just creates more work for someone, and it's hard to track
> * We haven't seen breaking version updates from Metabase in the ~18 months we've been using it
> * It's quasi-used in production, to the extent that we share some dashboards with external partners, but it's not seen by any SimpleReport end users.
> 
> @zdeveloper your thoughts?

Yeah, I agree with you, its like getting a new shiny car every time we upgrade, so the risk is very low, as opposed to upgrading spring, which like upgrading the engine on an existing car and making sure everything works in that car (arguably harder). 

I am totally cool with getting a new version every time, as long as we set the pipeline correctly to update all the instances to the latest version.

**Comment by zdeveloper** [comment]
@rin-skylight any update on this PR? does it need to be merged or closed?

**Comment by rin-skylight** [comment]
> @rin-skylight any update on this PR? does it need to be merged or closed?

I've updated this with the latest metabase version for pinning...this got a little out-of-date with the initial approval delay, and I didn't want to run the risk of accidentally forcing our production metabase version backwards!

**Review by emmastephenson — APPROVED** [review]
LGTM!

**Review by zdeveloper — APPROVED** [review]

**Pull request merged**
