### PR TITLE
always create patient link

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- we need to always create a patient link regardless of preference

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [x] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [x] Any content changes (including new error messages) have been approved by content team

### Support
- [x] Any changes that might generate new support requests have been flagged to the support team
- [x] Any changes to support infrastructure have been demo'd to support team

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by nathancrtr — APPROVED** [review]
Dig it 👍 just curious, what was the background on this?

**Comment by zdeveloper** [comment]
> Dig it +1 just curious, what was the background on this?

So after we originally were creating patient links when we added a test to the queue and when we submitted a test, so I removed the part where we create a patientLink when we add a patient to the queue a while back, and forgot to make it where we always should create it regardless of preference so we handle the resend case more gracefully.

**Review by JSkeets — APPROVED** [review]
Thanks for getting this change in, cool to see it go from alarm to resolution in a short time period

**Comment by JSkeets** [comment]
> Dig it 👍 just curious, what was the background on this?

Actually pretty cool, we received an alarm this morning of 
`https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/source/Alerts.EmailLinks/scope/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%7D%5D%7D/q/eJxFjLsOgkAURHu%2BYkq2gOxulAQSbPwFK7sVxkjCy713Q%2BPHi1p4ujnJnMhnoqhkL2wPRkJj4n8sw6x5pKRRz0tPgxt1I2fk3lqUJXxdG4S5h6SuowjaFvcwCr9Sh2mPh2nFqUXeB%2BXH7F%2FvC%2BsKW11c1Rxc431pf1wNChwnk70B/prettify/1/timespan/2022-01-06T16%3A36%3A22.0000000Z%2F2022-01-06T16%3A41%3A22.0000000Z`

with resend email links with null ids and this is the fix for it

**Review by nathancrtr — APPROVED** [review]

**Pull request merged**
