### PR TITLE
Disable GraphQL Playground functionality

### PR DESCRIPTION
**Pull request by rin-skylight**
## Related Issue or Background Info

- We do not want the GraphQL playground enabled by default in our environments. A security review indicates that the plugin seemingly cannot connect to a live database, which minimizes any damage potential, but having it enabled is bad practice.

## Changes Proposed

- Remove GraphiQL plugin from `build.gradle`.
- Disable playground in Spring Boot settings.
- Delete static plugin initialization page.

## Additional Information

- Upgrading the Apollo version in later PRs may cause some form of a playground to recur. We will need to check then to ensure that we do not inadvertently re-introduce a vulnerability.

### Infrastructure
- [x] **Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!**

### Support
- [x] Any changes that might generate new support requests have been flagged to the support team
- [x] Any changes to support infrastructure have been demo'd to support team

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)

## Cloud
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by jdorothy — COMMENTED** [review]
This looks good, but I was under the impression that we wanted to keep this functionality locally (it actually is very useful for development).

**Comment by emmastephenson** [comment]
> This looks good, but I was under the impression that we wanted to keep this functionality locally (it actually is very useful for development).

That was our initial hope, but Rin and I could not find a way to disable this only for production. There are theoretically `yaml` configs that will disable the playground for production, which we tried to no avail. We also tried setting the `node env` [setting](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/docker-compose.yml#L9) to `production` as graphQL claims the [playground is disabled there](https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/#:~:text=When%20NODE_ENV%20is%20set%20to%20production%2C%20GraphQL%20Playground%20(as%20well%20as%20introspection)%20is%20disabled%20as%20a%20production%20best%2Dpractice.), but I think we have some kind of custom playground config set up because none of that restricted the playground from showing up. 
For local dev, I think we can use Insomnia for the same purpose as the playground.

**Review by nickclyde — APPROVED** [review]
I'm good with just using Insomnia locally :+1:

**Review by jdorothy — APPROVED** [review]

**Comment by jdorothy** [comment]
> > This looks good, but I was under the impression that we wanted to keep this functionality locally (it actually is very useful for development).
> 
> That was our initial hope, but Rin and I could not find a way to disable this only for production. There are theoretically `yaml` configs that will disable the playground for production, which we tried to no avail. We also tried setting the `node env` [setting](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/docker-compose.yml#L9) to `production` as graphQL claims the [playground is disabled there](https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/#:~:text=When%20NODE_ENV%20is%20set%20to%20production%2C%20GraphQL%20Playground%20(as%20well%20as%20introspection)%20is%20disabled%20as%20a%20production%20best%2Dpractice.), but I think we have some kind of custom playground config set up because none of that restricted the playground from showing up. For local dev, I think we can use Insomnia for the same purpose as the playground.

In that case I'm good, approved!

**Comment by rin-skylight** [comment]
Thanks, all!

**Pull request merged**
