### PR TITLE
Include testKitNameId in fhir

### PR DESCRIPTION
**Pull request by zdeveloper**
# BACKEND PULL REQUEST

## Related Issue

- part of #4898

## Changes Proposed

- Add `testKitNameId` to FHIR

## Additional Information

- Will add equipmentUid in a separate PR since that requires some refactoring

## Testing

- How should reviewers verify this PR?

### CODE REVIEW

**Review by BobanL — CHANGES_REQUESTED** [review]
Changes look good, but I think there are a couple of test that should be updated:
* `convertToObservation_Result_matchesJson`
* `convertToObservation_Result_correctionMatchesJson`

**Review by BobanL — DISMISSED** [review]
Looks great! Thank you 🍡

**Review by johanna-skylight — DISMISSED** [review]
LGTM!

**Review by BobanL — DISMISSED** [review]
👍

**Review by DanielSass — APPROVED** [review]
👍

**Review by BobanL — APPROVED** [review]

**Pull request merged**
