### PR TITLE
Update modal buttons

### LINKED ISSUE #887: Add sticky footer to modal and remove duplicate header button
The current implementation of duplicate buttons in the header and footer is an accessibility issue and this would fix that.

### PR DESCRIPTION
**Pull request by maya**
## Related Issue or Background Info

Resolves #887

## Changes Proposed

- Removes the complete button in the modal header
- Changes the cancel button to an "X" close button
- Adds a sticky footer to the TOT modal for the "complete questionnaire verbally" form.

## Additional Information

- 

## Screenshots / Demos
Screen Shot 2021-03-01 at 10 16 49 PM

### CODE REVIEW

**Comment by maya** [comment]
Thoughts @katiealoisi @hmyers-cms?

**Comment by hmyers-cms** [comment]
Now that I'm seeing it, I'd like to know what you think about potentially keeping the button at the top and having the header be sticky instead of the footer. The footer creates a lot of dead space, and it might be nice for the patient name to always be visible as you scroll. Open to your design thoughts + would love to know if that update would be a lot of extra work at this point

**Comment by maya** [comment]
Yeah it could be a lot more work, hard to say at this point. We can reduce the vertical padding of the footer by 50% and that would cut some of the space, with that update I don't think it would take so much room. My rec would be to fix the issue and make improvements in the future.

**Comment by hmyers-cms** [comment]
Okay sounds good. In that case, LGTM

**Review by ClydeDroid — APPROVED** [review]
Awesome work @maya

**Pull request merged**
