### PR TITLE
update backend add user mutation

### PR DESCRIPTION
**Pull request by BobanL**
# BACKEND PULL REQUEST

## Related Issue

- Part of #5945 - Adding two new parameters to addUser mutation

## Changes Proposed

- Add `accessAllFacilities` and `facilities` to the userInput object
- Add userInput to the addUserToCurrentMutation 

## Additional Information

- There will be 2 more PRs to resolve the rest of the work, Front end changes to use the new parameters and then a cleanup.

## Testing

- These changes should not impact existing functionality.  Deployed in [Dev](https://dev.simplereport.gov/)!
  - Creating new organization, adding an org admin, adding new user, and reprovisioning deleted user all works as expected.

### CODE REVIEW

**Review by johanna-skylight — COMMENTED** [review]
LGTM! But would you mind fixing the 2 sonar cloud smells in the unit test code :D. Thanks!

**Review by johanna-skylight — APPROVED** [review]
LGTM!

**Comment by mehansen** [comment]
Will the cleanup involve removing the part from your other PR where we use find users with the `q` parameter?

**Review by mehansen — APPROVED** [review]
looks good! 🙆‍♀️

**Comment by BobanL** [comment]
> Will the cleanup involve removing the part from your other PR where we use find users with the `q` parameter?

Yes it will! It'll also clean up tests and improve test coverage 😄

**Pull request merged**
