### PR TITLE
[1495] Create service user for Okta -- In Test

### PR DESCRIPTION
**Pull request by JSkeets**
## Related Issue or Background Info
[1495](https://app.zenhub.com/workspaces/simplereport-devops-61127bc8b61cae0013456681/issues/cdcgov/prime-simplereport/1495)

This work represents the desire to have a service user for Okta which uses a service user account API tokens instead of personal user tokens. This PR is to temporarily modify the token only for the test environment, to ensure that no issues come up with the new token before moving onto different environments, by making the permanent change and exposing it to a wider variety of use cases.

A service user for Okta was created. The user has access to all environments, and largely, clones the permissions of the user our current token operates under. The user can be viewed in Okta here [simplereport-developer](https://hhs-prime-admin.okta.com/admin/user/profile/view/00ulduxsjCgWGKZDz4h6). 

The user is associated with a google group at `simplereport-developers@googlegroups.com`. All developers will be added to this google group. 

## Changes Proposed
- Create Okta service user
- Store API token in Github secrets
- Modify test to use new API token

## Additional Information

This method of testing, merging the PR, letting it be used, and then rolling out to other environments may be clunky. If anyone has better methods, I am all ears.

## Screenshots / Demos

I have logged into test after the deploy with the new token, and have not had any issues. I view this PR as a test which allows any issues to come up. 

Screen Shot 2021-09-20 at 2 18 11 PM

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by nullflux — APPROVED** [review]
This PR seems fine, though I would have expected the `OKTA_API_TOKEN` to have been stored in KeyVault and passed to the relevant application environments via Terraform during the build as opposed to set in the GitHub environment

I _am_ concerned though about using a Google Group for the Okta User. This seems like something that should be handled in AD using a CDC address? Let's follow up offline

**Comment by jdorothy** [comment]
> This PR seems fine, though I would have expected the `OKTA_API_TOKEN` to have been stored in KeyVault and passed to the relevant application environments via Terraform during the build as opposed to set in the GitHub environment
> 
> I _am_ concerned though about using a Google Group for the Okta User. This seems like something that should be handled in AD using a CDC address? Let's follow up offline

Agreed on the API token - it's technically not in scope but this would be a nice improvement. As currently written we have a chicken and egg problem with the Okta API key, because the Terraform provider expects it to be defined _before_ actually running any Terraform scripts (that would then presumably use a resource to retrieve that value). I think we could get around that by using the CLI to retrieve the secret in the GH Action before running TF.

Also agreed on the Google Group. I see why a group email is necessary, but CDC may have a solution they prefer more.

**Comment by nullflux** [comment]
Ahh that makes sense about the Terraform provider. Thanks for the context!

**Comment by JSkeets** [comment]
I will investigate some other ways implementing a shared email for the group, hopefully the CDC has a preferred method.

**Pull request merged**
