### PR TITLE
Add Consent page to Experian flow

### LINKED ISSUE #2278: Experian flow needs consent language
### Description
Experian requires us to put their consent information in front of our users before we make any requests on that user's behalf. We need to add this consent language to the identity verification flow.

### Proposed solution 
Details from Experian (also forwarded in an email): 

There are two parts to this, one for the Experian FCRA data and one for the Boku data that we are leveraging as part of the identity proofing process.

FRCA Language:
```
You understand that by clicking on the I AGREE button immediately following this notice, you are providing ‘written instructions’
to (Client) under the Fair Credit Reporting Act authorizing (Client) to obtain information from your personal credit profile or other
information from Experian. You authorize (Client) to obtain such information solely to confirm your identity to avoid fraudulent transactions in your name.
```

- The “I AGREE” button must immediately follow the notice provided for above. The notice and “I AGREE” button must be separate from any other notice or message contained on the web site.
- The consumer must have the ability to fully review any of the terms to which he or she is agreeing immediately preceding
the consensual click.
- The consumer must not be able to proceed in the process without affirmatively agreeing to the terms in the notice.
- The consumer must have the ability (should they choose) to print out the terms to which he or she is agreeing, including their consent.
- The record of the consumer’s ‘written instruction’ by clicking “I AGREE” must be retained by Client in a form that is capable of being accurately reproduced for later reference by the Parties.

Boku Language:
```
You authorize your wireless operator to disclose to us details of your account, subscriber, billing and device, if available, to support verification of identity, fraud avoidance in support of and for the duration of your business relationship with us.  Where applicable, this information may also be shared by us with other companies to support your transactions and for fraud avoidance purposes.  You can see a more detailed list of information potentially disclosed and how we use your data in our Privacy Policy.
```

We can combine the two consent statements into a single one, but Experian requires a screenshot of language in-app before they'll turn our access on.

### Specific Asks
Victor, can you provide input about what point in the flow we should put this language? What should we do if the user doesn't agree to them?
Rebecca, I don't think we have a ton of flexibility on the language, but could you write the copy for the purpose in the FCRA text?
Nick, once the above are done, can you add this to the Experian UI?

Please provide screenshots of the final product to @TimBest so we can get approval

Thanks all!

### PR DESCRIPTION
**Pull request by nickclyde**
## Related Issue or Background Info

- Resolves #2278

## Changes Proposed

- Adds `Consent` component with required consent language from Experian
- Flow starts with this new component, requires checking "I AGREE" checkbox before continuing

## Additional Information

- this is a quick pass, open to design changes

## Screenshots / Demos

image

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification

### CODE REVIEW

**Comment by Rebecca-LM** [comment]
@nickclyde not sure what we can change here from a legal standpoint but here are my thoughts below and requested changes.

- Change title to "Identity verification consent"
- First paragraph add "your" so it reads ..."access your identify verification details"...
- Last sentence: lowercase "privacy policy" (can we link to it here too? it's https://www.cdc.gov/other/privacy.html)
- Do we need the I AGREE and the Submit button? I would prefer we do the same pattern as our terms of service. If this is possible then we'd need to:  Change "I AGREE" to "Submit" in the second paragraph (I'd prefer we have this in bold, not all caps). OR we could just get rid of the Submit button and have "I agree" as the button copy. Again, I prefer lowercase so we're not yelling :)

**Comment by nickclyde** [comment]
I'd be happy to make the content changes but I'm not sure about Experian's requirements for us either. @emmastephenson are we allowed to change the language?

As for the "I agree", I believe they want us to make agreeing to the terms an explicit step before you are allowed to continue, which is why I moved it into a checkbox.

**Comment by emmastephenson** [comment]
Reading the email again, I don't think we need a checkbox. Here's the contract language from Experian:

> A.                                FCRA Compliance--Written Instructions. Client shall substantially comply with the following web site requirements:
> 
> (1)             Client will prominently display a message specifically informing the consumer that his or her credit profile will be consulted
> for the purpose for which it is to be used and no other purpose, and that clicking on the “I AGREE” button following such notice
> constitutes written instructions to the Client under the FCRA. Client agrees that the notice provided by Client will be substantially as
> follows:
> 
> “You understand that by clicking on the I AGREE button immediately following this notice, you are providing ‘written instructions’
> to (Client) under the Fair Credit Reporting Act authorizing (Client) to obtain information from your personal credit profile or other
> information from Experian. You authorize (Client) to obtain such information solely to _____________________________
> (insert purpose e.g. to confirm your identity to avoid fraudulent transactions in your name.)
> 
> (2)             The “I AGREE” button must immediately follow the notice provided for above. The notice and “I AGREE” button must be
> separate from any other notice or message contained on the web site.
> 
> (3)             The consumer must have the ability to fully review any of the terms to which he or she is agreeing immediately preceding
> the consensual click.
> 
> (4)             The consumer must not be able to proceed in the process without affirmatively agreeing to the terms in the notice.
> 
> (5)             The consumer must have the ability (should they choose) to print out the terms to which he or she is agreeing, including their
> consent.
> 
> (6)             The record of the consumer’s ‘written instruction’ by clicking “I AGREE” must be retained by Client in a form that is capable of
> being accurately reproduced for later reference by the Parties.


My read on this is that we don't need the checkbox, and that we can just make the button say "I agree". We also have to send a screenshot of this page to Experian, so if they _really_ want the checkbox for some reason we can always add it back in later.

I think the other copy changes Rebecca suggested are perfectly fine, Experian shouldn't have an issue with those.

Thank you both for the quick feedback here!

**Comment by nickclyde** [comment]
Great, I'll go ahead and make those changes then!

**Comment by nickclyde** [comment]
Updated the screenshot with the new language!

**Review by Rebecca-LM — CHANGES_REQUESTED** [review]
Sorry, just caught these!
- First sentence change to: create **an** account
- Add a comma after "Fair Credit Reporting Act"

**Comment by nickclyde** [comment]
Oxford comma ftw!

**Review by Rebecca-LM — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]

**Pull request merged**
