### PR TITLE
Email notification for Patient Bulk Upload

### PR DESCRIPTION
**Pull request by georgehager**
# BACKEND PULL REQUEST

## Related Issue #4440 

Adds an email notification once patient bulk upload is complete. The email includes a link back to the application, where if logged in, the user can view the newly uploaded patients.

Update: Ready for review!

Also note that this is the same PR as #4758, I created this new branch to keep things tidy.

## Changes Proposed

-  adds an email template for patient bulk upload
- when save to the database save in the async method for patient bulk upload is complete, an email is sent to notify the user
- if processing fails, an email is sent to notify the user (screenshot [here](https://github.com/CDCgov/prime-simplereport/issues/4440#issuecomment-1324262939))

## Additional Information

Tests Added
- I added two unit tests for the new email template success + error
- Integration test to verify if processing and save is successful, success email gets triggered
- Integration test to verify if processing within the while loop fails, or if the saveAll to the db fails, error email gets triggered

Here is the sequence of events: before patient upload, after patient upload, and then the email that gets sent:
- before
dev4 b4
- after
dev4 after
- email
dev4 email

When an error occurs in processing, sending the error email is triggered. Note that error email cannot be triggered manually via the app since validation catches csv errors (forcing failure would require a code change to remove validation or force the db to fail). If you figure out a way to do this 🙌  let me know though. Since this isn't manually testable in an environment, here are the logs when I triggered errors in the code:
- processing error in while loop (turned off validation in `PatientBulkUploadService` and uploaded an invalid csv
Screen Shot 2022-11-22 at 4 01 21 PM
- processing error in saveAll (forced an error in the `addPatientsAndPhoneNumbers` method)
Screen Shot 2022-11-22 at 4 15 31 PM

## Testing

How should reviewers verify this PR?
- Go to **dev5**, upload patients via csv, and confirm that you receive an email notifying you when the upload is complete. Click the `See patients` link, which should take you directly to the patients page, if you are logged in to dev4.
- Note that error email cannot be triggered manually

## Checklist for Primary Reviewer
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [x] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] Changes comply with the SimpleReport Style Guide

### CODE REVIEW

**Comment by emmastephenson** [comment]
Giving this a pre-review before I head out - overall looks great! My one note is to make sure to revert the changes to `application-azure-dev5` before merging. There are also a couple of code smells to address on the `PatientBulkUploadServiceAsyncTest` (some of them will be fixed in the main async PR, but not all).

**Comment by georgehager** [comment]
> Giving this a pre-review before I head out - overall looks great! My one note is to make sure to revert the changes to `application-azure-dev5` before merging. There are also a couple of code smells to address on the `PatientBulkUploadServiceAsyncTest` (some of them will be fixed in the main async PR, but not all).

I'm planning to resolve and push code smell fixes after the async PR goes in.

**Comment by georgehager** [comment]
@johanna-skylight @emyl3 @zdeveloper @BobanL ready for final review!

**Review by BobanL — APPROVED** [review]
Thank you 🥇

**Review by johanna-skylight — APPROVED** [review]
LGTM

**Review by emyl3 — APPROVED** [review]
Codewise looks good to me! I wasn't able to get mailhog working locally so wasn't able to see emails there. However, with the bug bash testing -- confident the mail actually sends 😄

**Pull request merged**
