### PR TITLE
Add design/content language to PR checklist

### PR DESCRIPTION
**Pull request by emmastephenson**
Following the action items from 12/14 P-D sync, updating the PR checklist to include reviews from design/content.

### CODE REVIEW

**Review by zdeveloper — DISMISSED** [review]
LGTM!

**Comment by emmastephenson** [comment]
@nickclyde would you mind reviewing this when you get the chance? TIA!

**Review by nickclyde — APPROVED** [review]
Looks good!

**Review by nickclyde — APPROVED** [review]

**Review by zdeveloper — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
