### PR TITLE
Add supported disease table

### LINKED ISSUE #3411: Add a table for supported diseases (db)
### Background
As part of the database work for the multiplex effort, we need a way to track which diseases SimpleReport supports. 

See the [engineering doc for](https://docs.google.com/document/d/11QpgPUGDM1HTqHEjae7roeJaynkcJ_15MoQ8jGaTphs/edit#heading=h.46qi1mwc83xv) Multiplex.

### Action Requested
Add a new table to the database for supported diseases. This table should have the following data stored in it:
- internal UUID
- column for disease name (as LOINC code)
- jsonb column for potential result (also as LOINC codes)

Once the table has been created, we'll need to input COVID-19 and Flu A/Flu B as our supported diseases.

[LIVD Table](https://www.cdc.gov/csels/dls/sars-cov-2-livd-codes.html) (You'll want to reference the LOINC mapping in the spreadsheet)
### Acceptance Criteria

- [ ] New disease table has been added to the database
- [ ] Table contains COVID-19, Flu A, and Flu B metadata

### PR DESCRIPTION
**Pull request by emmastephenson**
## Related Issue or Background Info

- Fixes #3411 

## Changes Proposed

- Add a new supported disease table
- Add COVID-19, Flu A, and Flu B to the table

## Additional Information

- This is a non-audited table as it should only ever be updated internally (users will never have write access)

This is the result of running the migrations locally:
Screen Shot 2022-02-23 at 4 06 17 PM

- We need to check with someone(?) who is a LOINC expert that these are the right values to store

### Infrastructure
- [ ] **Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!**

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Comment by emmastephenson** [comment]
@MauriceReeves-usds, adding you as a reviewer because Tim B. said you're our resident LOINC/LIVD expert - I want to make sure that a) the LOINCs I've chosen to represent covid/flu a/flu b are accurate, and b) that this is a reasonable way to think about/store diseases. This is the first stage of our multiplex work, please let me know if you have any questions!

**Review by nickclyde — DISMISSED** [review]
Looks good to me!

**Review by nickclyde — APPROVED** [review]

**Review by zdeveloper — CHANGES_REQUESTED** [review]
LGTM! However, rebased with master then the rollback still didnt work despite the rollback command succeeding

Notice it asking for a pro license, @jdorothy is this something we should worry about?
```shell
zedd@pop-os:~/workspace/prime-simplereport/backend$ ./gradlew liquibaseUpdateToTag -PliquibaseCommandValue=add-default_specimen_type_id-to-facility

> Task :liquibaseUpdateToTag
liquibase-plugin: Running the 'main' activity...
14:51:10.125 INFO  [liquibase.integration.commandline.Main]: ####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Get advanced features and support at          ##
##      liquibase.com/protrial                    ##
##                                                ##
####################################################
Starting Liquibase at Tue, 01 Mar 2022 14:51:10 CST (version 3.10.3 #32 built at Mon Oct 12 07:24:42 UTC 2020)
14:51:10.792 INFO  [liquibase.integration.commandline.Main]: No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
14:51:10.792 INFO  [liquibase.integration.commandline.Main]: Liquibase Community 3.10.3 by Datical
14:51:10.793 INFO  [liquibase.integration.commandline.Main]: ####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Get advanced features and support at          ##
##      liquibase.com/protrial                    ##
##                                                ##
####################################################
Starting Liquibase at Tue, 01 Mar 2022 14:51:10 CST (version 3.10.3 #32 built at Mon Oct 12 07:24:42 UTC 2020)
14:51:11.133 INFO  [liquibase.lockservice.StandardLockService]: Successfully acquired change log lock
14:51:11.557 INFO  [liquibase.changelog.StandardChangeLogHistoryService]: Reading from simple_report.databasechangelog
14:51:11.660 INFO  [liquibase.lockservice.StandardLockService]: Successfully released change log lock
14:51:11.662 INFO  [liquibase.integration.commandline.Main]: Liquibase command 'updateToTag' was executed successfully.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
```

**Review by zdeveloper — APPROVED** [review]
The rollback worked using the following command
`./gradlew liquibaseRollbackCount -PliquibaseCommandValue=2`
unblocking this PR since the previous issue was observed on `main` branch too.

**Comment by jdorothy** [comment]
> Notice it asking for a pro license, @jdorothy is this something we should worry about?

Nope! That's the output regardless of command, it's just letting you know.

**Pull request merged**
