### PR TITLE
Add Nightwatch.js end-to-end tests

### PR DESCRIPTION
**Pull request by ClydeDroid**
This adds some E2E/Integration tests using [Nightwatch.js](https://nightwatchjs.org/) and selenium. 
Run them with the following commands while the app (both front and backends) is already running:

```bash
cd frontend
npm run e2e
```

They run using selenium hub in a Docker Compose setup, and hit the app running at localhost:3000. For now I added a single test that adds a new patient, more can be added, the sky is the limit!

Screenshot:
image
image

### CODE REVIEW

**Comment by nickrobison-usds** [comment]
Excited about this change!

**Comment by timothybest-usds** [comment]
please run  `prettier -c ./src --write` and commit the changes to get the linter CI to pass

**Comment by timothybest-usds** [comment]
can you add `yarn e2e` to https://github.com/CDCgov/prime-simplereport/blob/main/.github/workflows/smoketest.yml so this runs in CI

**Review by timothybest-usds — APPROVED** [review]
looks like

**Pull request merged**
