### PR TITLE
Update to `dart-sass` and use mixins at the component level

### LINKED ISSUE #1676: Get Sass resources to work when imported into the component
### Description
I'd like to be able to use Sass resources (mixins, functions, variables) at the component-level Sass file, so that I can use USWDS Sass mixins, functions, and variables and import it in a component file. 

### Proposed solution 
Explore setting up [sass-resources-loader](https://github.com/shakacode/sass-resources-loader) or something similar

### Additional info
We'll need to change from `node-sass` to Dart Sass  to do this, which is good bc `node-sass` is no longer supported. Though it's unclear what other effects there are with this.

#### ⭐ Chromatic
Chromatic is working on a feature to only create snapshots on changed files, but we'd need to move to componentized Sass to get these benefits. This will help ensure long-term use of Chromatic. Otherwise, we may reach our quota as we add more stories and push more frequently. cc @bmaden-usds @timbest-usds for visibility

---

### Definition of done

- Developers can use Sass resources (from USWDS) at the component level. For example: in [FacilitySelect.scss](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/facilitySelect/FacilitySelect.scss) and import it into [FacilitySelect.tsx](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/facilitySelect/FacilitySelect.tsx#L7).
- This works for the app and Storybook

/cc @cdevent

### PR DESCRIPTION
**Pull request by cdevent**
## Related Issue or Background Info

Closes #1676

## Changes Proposed

As requested in https://github.com/CDCgov/prime-simplereport/issues/1676 

- moved from `node-sass` to the `sass`
- make the required mixins, functions, etc. accessible on the component level. 
- upgrade version of USWDS to `2.11.2`

## Additional Information

One thing that's related only to the USWDS that's we have some warnings on `watch-css` and `compile-scss` about some deprecations in Dart Sass: 

Screenshot 2021-05-24 at 5 41 02 PM

### UI
- [x] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design

### CODE REVIEW

**Comment by maya** [comment]
@cdevent thanks for getting this started! Are the Sass deprecation warnings preventing Sass from being built? e.g. the two checks that don't complete: 

- Chromatic / chromatic-deployment (push) 
- Test / frontend-lint-and-build (pull_request)

I created an issue with the USWDS team and it's on their radar and will hopefully be resolved: https://github.com/uswds/uswds/issues/4204

**Comment by cdevent** [comment]
> @cdevent thanks for getting this started! Are the Sass deprecation warnings preventing Sass from being built? e.g. the two checks that don't complete: 
> 
> 
> 
> - Chromatic / chromatic-deployment (push) 
> 
> - Test / frontend-lint-and-build (pull_request)
> 
> 
> 
> I created an issue with the USWDS team and it's on their radar and will hopefully be resolved: https://github.com/uswds/uswds/issues/4204
@maya 
Sounds good!

No, it's look like that problem that file App.css is not exist and sass cannot handle creating it

**Comment by cdevent** [comment]
I'll check it on my morning

**Comment by maya** [comment]
I'm not sure if it's related, but I can't see any Sass/CSS changes on the `main` branch on `yarn start`, but I can see it on `yarn storybook`. How about you?

I do see this error, but I also know we had errors/warnings before like in #569:
```
{
  "status": 1,
  "file": "/Users/mayabenari/Code/prime-simplereport/frontend/src/scss/PrimeStyles.scss",
  "line": 59,
  "column": 12,
  "message": "no mixin named at-media",
  "formatted": "Error: no mixin named at-media\n        on line 59 of src/scss/PrimeStyles.scss\n>>   @include at-media(\"mobile-lg\") {\n\n   -----------^\n"
}
```

**Comment by maya** [comment]
The issue above seems unrelated, this works for the app. Storybook wasn't working locally for me, but after adding 80a862c, it works.

Do we know if there's a difference in the compile time between these?

**Comment by cdevent** [comment]
Dart sass performance is a known issue and it's not a best side of it. Node sass is faster. Actually if I'm understanding right we need dart sass only if u wants to get `@use` in scss files. I'll work with it today more to investigate it any other issues, and it's look like we have a problem when it's building using 'yarn build`

**Comment by maya** [comment]
Looks like `main` is fixed. Did you find anything in your research about Node sass / speed, or @use?

**Comment by cdevent** [comment]
I've pushed some changes today, can you check?

**Comment by cdevent** [comment]
Mixings and @use should work

**Comment by maya** [comment]
Sure, will be able to check later today. Were any of the changes made performance or speed-related?

**Comment by maya** [comment]
Confirmed that mixins and functions are working at the component level. Also, when compiling at a component level, it's much faster (a few seconds) than compiling the entire custom stylesheet (20 seconds). 

I'd like a few more engineers' eyes on this since it changes how we compile styles.

**Comment by maya** [comment]
Here's a PR for the fix for USWDS warnings: https://github.com/uswds/uswds/pull/4209

**Comment by maya** [comment]
While it works for the app, it doesn't look like Sass resources are loading on Storybook components yet. Test with the Facility select component and `src/app/facilitySelect/FacilitySelect.scss` and `yarn storybook`.

**Comment by cdevent** [comment]
I'll look what can i do on storybook level.

**Comment by cdevent** [comment]
> While it works for the app, it doesn't look like Sass resources are loading on Storybook components yet. Test with the Facility select component and `src/app/facilitySelect/FacilitySelect.scss` and `yarn storybook`.

try please now on your side, I've pushed webpack setup for Storybook.

**Comment by maya** [comment]
This is working in Storybook now, thanks! 🥳

**Review by maya — APPROVED** [review]
Looks good from my end 👍  Though hold to merge until some other engineers have reviewed it.

**Comment by maya** [comment]
Reminder to resolve conflicts @cdevent

**Review by emmastephenson — APPROVED** [review]
LGTM, but with the caveat that I'm not experienced with sass, so someone who knows more frontend should probably review as well.

**Review by nickclyde — APPROVED** [review]
Craco setup looks good to me :+1:

**Pull request merged**
