### PR TITLE
Drop data_hub_upload table

### PR DESCRIPTION
**Pull request by mehansen**
# DATABASE PULL REQUEST

## Related Issue

removing an unused table as followup to this commit: https://github.com/CDCgov/prime-simplereport/commit/1d646e9d9d9ad84de090bf478e7d4397dfaaf03d

## Changes Proposed

see PR #5105 for more info. this table hasn't been used since 2021 and we are no longer storing this kind of upload data in this way (can be found in Azure function app logs) so it's not entirely relevant to keep

## Additional Information

open to discussion on whether we should keep this in case we ever have need for it

## Testing

I'll deploy to a lower and we can check out metabase

## Checklist for Primary Reviewer

- [ ] Only database changes are included in this PR
- [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] Rollback has been verifed locally and in a deployed environment

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
Dropping the table sounds good to me! We also have the backup non-flexible database from April 2022 (since we needed to maintain audit logs from that db) so this data is still available there if we ever needed it for regulatory purposes or whatever.

**Comment by mehansen** [comment]
> Dropping the table sounds good to me! We also have the backup non-flexible database from April 2022 (since we needed to maintain audit logs from that db) so this data is still available there if we ever needed it for regulatory purposes or whatever.

oh great, thanks for pointing that out!

**Review by BobanL — APPROVED** [review]
Looks good! Thanks

**Review by zdeveloper — APPROVED** [review]
Thank you!

**Pull request merged**
