### PR TITLE
Release Multiplex

### PR DESCRIPTION
**Pull request by emmastephenson**
This PR will enable multiplex for end users!! 🎉 

To be merged Monday 7/11.

### CODE REVIEW

**Comment by emmastephenson** [comment]
@emyl3 and @johanna-skylight, could y'all investigate the test failure on Monday morning while I'm OOO? Afraid I won't be able to look at it before then!

**Comment by emyl3** [comment]
> @emyl3 and @johanna-skylight, could y'all investigate the test failure on Monday morning while I'm OOO? Afraid I won't be able to look at it before then!

Yes! Investigating now 👀

**Comment by johanna-skylight** [comment]
The priority should be getting multiplex launch so I have patched this PR to pass the unit test and created a ticket to follow up on the test case fix https://github.com/CDCgov/prime-simplereport/issues/3956. Elisa is currently working on the fix

**Comment by emyl3** [comment]
@johanna-skylight and I thought it would be best to fix the failing unit test separately so it does not block the release of multiplex https://github.com/CDCgov/prime-simplereport/issues/3956

**Review by johanna-skylight — APPROVED** [review]

**Review by fzhao99 — APPROVED** [review]
woooooo!!!!!!!!

**Review by emyl3 — APPROVED** [review]
😭 🙌 😹

**Pull request merged**
