### PR TITLE
Add ARIA labels to test card timer

### LINKED ISSUE #4046: Test card timer should have more accurate label
## Area or Component
Conduct Test

## Quick Summary
The timer's aria name is "15:00", but would be more accurately labelled "timer" (or at least given a role of timer)

## Accessibility Violation
* `aria-name-missing-incorrect`
    * The element's accessible name is missing or is not appropriate for the element's purpose

## Action Requested
The test card timer should have a more descriptive aria label: "timer" should suffice.

Can also consider adding a `role` of timer

## Source Code (optional)
https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/testQueue/TestTimer.tsx#L234-L275

### PR DESCRIPTION
**Pull request by mehansen**
# FRONTEND PULL REQUEST

## Related Issue

Resolves #4046 

## Changes Proposed

- Labels the timer button with the given action
- Sets the role of the timer text within the button to 'timer' - I think this should also prevent a screenreader from repeatedly announcing every time the text updates

## Additional Information

- went with more specific label than just "timer" because I think it's not clear from that whether you're starting or stopping the timer since screen readers can't read the start and reset icons

## Testing

Deploy locally or to a lower and inspect the elements to see that they have the correct label - should be different when the timer is stopped than when it's running
 
## Screenshots / Demos
Screen Shot 2022-08-16 at 8 54 10 AM

Screen Shot 2022-08-16 at 8 54 17 AM

Screen Shot 2022-08-16 at 8 54 29 AM

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [n/a] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [x] Any content changes have been approved by content team

### Support
- [n/a] Any changes that might generate new support requests have been flagged to the support team
- [n/a] Any changes to support infrastructure have been demo'd to support team

### Security
- [n/a] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [n/a] Any dependencies introduced have been vetted and discussed

### Documentation
- [n/a] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Comment by mehansen** [comment]
fyi @lauraykerr since the button names are a minor content change for users using screen readers

**Comment by lauraykerr** [comment]
> fyi @lauraykerr since the button names are a minor content change for users using screen readers

Thanks, looks good to me @mehansen

**Review by emmastephenson — APPROVED** [review]
Adding the `role` as timer is a great idea, thanks Merethe!

**Review by zdeveloper — APPROVED** [review]
LGTM! thank you!

**Pull request merged**
