### PR TITLE
Add NAT gateways to each env + static IP

### PR DESCRIPTION
**Pull request by jdorothy**
## Related Issue or Background Info

#2855

We need control over the outbound IP addresses being used in order to pass a reasonable list of IPs to third parties to allowlist.

## Changes Proposed

- Create static IP
- Associate IP with NAT gateway
- Associate NAT gateway with VNet subnets for VMs, web apps, and load balancers
- Outbound traffic originating from within the VNet (e.g. the API making an external HTTP request) now originates from the static IP

## Additional Information

- This doesn't affect _all_ app traffic, just traffic that originates from within the VNet. Inbound traffic passing through the App Gateway will still return through the App Gateway, for instance.
- This is difficult to prove since we have to do so by originating outbound traffic from within the VNet - e.g. SSHing into an App Service container, which we can't do. One way you can see this by running a `curl` from within a VM.

### Testing
- [ ] Create a VM in `test` with the following change: on the Networking tab, find the IP Address dropdown. Click "Create new" underneath and select Standard (Basic should be the initial value).
- [ ] Log into that VM and run `curl ipinfo.io`. The returned IP should match the IP assigned to the NAT gateway in `test`.

### CODE REVIEW

**Review by JSkeets — APPROVED** [review]
Looks good to me

**Comment by JSkeets** [comment]
I attempted to go through your testing steps, but there are no NAT gateways in test. I presume that the resource was created and destroyed ? The code looks great though!

**Comment by jdorothy** [comment]
> I attempted to go through your testing steps, but there are no NAT gateways in test. I presume that the resource was created and destroyed ? The code looks great though!

Yeah unfortunately another test deploy got rid of it. You can redeploy to test from this branch though.

**Comment by bmaden-usds** [comment]
We'll need to find out what the IP addresses will change to and then submit a request to Experian to have those IPs added to our accounts as authorized addresses **before** deploying this (unless somehow this will retain one of the outbound ip addresses already used by the app service).

We have 2 accounts that will need the production ip address and another 2 accounts that will need both the nat gw address of all other environments that have Experian enabled (I think this is just `stg` and `test` right now).

Unfortunately, it takes **5 to 7 days** for Experian to process this request (yup, one that seems like it should be self-service), so we should put in a request to get that added well before we merge this.

**Comment by emmastephenson** [comment]
> We'll need to find out what the IP addresses will change to and then submit a request to Experian to have those IPs added to our accounts as authorized addresses **before** deploying this (unless somehow this will retain one of the outbound ip addresses already used by the app service).
> 
> We have 2 accounts that will need the production ip address and another 2 accounts that will need both the nat gw address of all other environments that have Experian enabled (I think this is just `stg` and `test` right now).
> 
> Unfortunately, it takes **5 to 7 days** for Experian to process this request (yup, one that seems like it should be self-service), so we should put in a request to get that added well before we merge this.

@jdorothy I assume the IP will be set by Azure, right? Do we have a way to get the final static IP address to Experian before this is merged?

**Comment by jdorothy** [comment]
> > > We'll need to find out what the IP addresses will change to and then submit a request to Experian to have those IPs added to our accounts as authorized addresses **before** deploying this (unless somehow this will retain one of the outbound ip addresses already used by the app service).
> > > We have 2 accounts that will need the production ip address and another 2 accounts that will need both the nat gw address of all other environments that have Experian enabled (I think this is just `stg` and `test` right now).
> > > Unfortunately, it takes **5 to 7 days** for Experian to process this request (yup, one that seems like it should be self-service), so we should put in a request to get that added well before we merge this.
> > 
> > 
> > @jdorothy I assume the IP will be set by Azure, right? Do we have a way to get the final static IP address to Experian before this is merged?
> 
> Yikes. Okay, I think we'll have to split this PR into two parts then. We can merge the code creating the IP address and gateway, so we'll know right away, but hold off on actually associating the gateway with the VNet until Experian's ready.

I pushed a new commit to comment out the actual subnet -> NAT gateway association. So we'll still create the actual infrastructure but not actually use it for outbound traffic until we hear back from Experian, at which point we can remove the comments in a follow up PR.

**Review by emmastephenson — APPROVED** [review]
Thanks Josh, LGTM!

**Pull request merged**
