### PR TITLE
Boban/6115 prevent correct result from deleted facility

### LINKED ISSUE #6115: Prevent org admin from correcting results for a deleted facility
### Background
As a result of #5977, we want to ensure that org admins cannot correct a test result for a deleted facility.

Since the current correction flow is,
- Click "Correct result"
- Mark reason for correction
- Depending on the correction reasons below, it will return the incorrect test result to the queue: 
   1. "Incorrect test result"
   2. "Incorrect test date"
   3. "Reason not listed" -> "Correct result" sub-option
- We need to prevent the user from selecting the above options because a deleted facility's test queue is inaccessible

### Action requested

- [ ] Confirm with design, what pattern and copy we want to use to prevent the user from correcting a test that is associated with a deleted facility

**Option 1 - error toast** 

Image

- Cons:
   - message auto closes in 5 seconds so user can miss the message

**Option 2 - inline form error** let's go with this option

Image

- Note (to confirm with design if necessary):
  - How to display "Reason not listed" view changes when there is this error for the particular sub-option?
  - Should existing modal close button copy change?

- [ ] Org admin cannot correct a test result for these 3 options  for a deleted facility
   1. "Incorrect test result"
   2. "Incorrect test date"
   3. "Reason not listed" -> "Correct result" sub-option

- [ ] Org admin can continue to correct a test result for these 2 options  for a deleted facility
   1. "Duplicate test"
   2. "Reason not listed" -> "Mark result as an error" sub-option
make sure this sends a message to our queue(s) with the correction 

### Acceptance Criteria
Option 2 is implemented in coordination with design

### Additional context
N/A

### PR DESCRIPTION
**Pull request by BobanL**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #6115 

## Changes Proposed

- Pass `isFacilityDeleted` to the correction modal
- If the facility is deleted, there is static text on the bottom; `You can only update duplicate tests and errors from a deleted facility. Contact [support@simplereport.gov](mailto:support@simplereport.gov) for help.`
  - For invalid selected options these errors appear `Can't update test result for deleted facility` and `Can't update test date for deleted facility`

## Additional Information

- The text has been provided by @lauraykerr 

## Testing

- Test in dev2

## Screenshots / Demos

https://github.com/CDCgov/prime-simplereport/assets/10108172/dc9e52ca-691f-443f-845a-5c47cac7ca96

### CODE REVIEW

**Review by johanna-skylight — APPROVED** [review]
Looks good! 👍

**Review by emyl3 — APPROVED** [review]
LGTM!! 🎸

**Review by johanna-skylight — APPROVED** [review]

**Comment by johanna-skylight** [comment]
@BobanL I approved but I am not sure why I am not marked with the check sign 😅

**Comment by BobanL** [comment]
> @BobanL I approved but I am not sure why I am not marked with the check sign 😅

I think it's because I made a small change after you reviewed 😃

**Pull request merged**
