### PR TITLE
Mike/7277 content audit csv bulk results upload

### LINKED ISSUE #7277: Content Audit (Application) - CSV Bulk Results Uploader
## Why should we do this?
- **Current experience:** The "CSV Bulk Results Upload Guide" uses COVID-19-specific language, potentially confusing users submitting results for other supported conditions.
- **Why we want to make this change:** By using generic language like "condition tested" and mentioning all currently supported conditions (COVID-19, Flu A, Flu B, RSV), we provide accurate and inclusive information for all users, aligning with the project's goal of broader disease and condition support.

## User story
- As a representative of a facility conducting rapid point-of-care tests for various conditions, I want the "CSV Bulk Results Upload Guide" to clearly explain the formatting requirements and restrictions for all supported conditions, so I can submit bulk results without errors or confusion.

## Action Requested
**1. Bulk results upload guide - Introduction**
- Existing text: _How to format and upload a CSV file to report test results in bulk through SimpleReport._
- New text copy: `How to format and upload a CSV file to report test results in bulk for COVID-19, Flu A and B, and RSV through SimpleReport.`

**2. Data Formatting Guide: Additional data and notes > Comment**
- Existing text: _This field isn't meant for characteristics of COVID-19 tests or statements about false positive or negative results._
- New text copy: `This field isn't meant for characteristics of the condition tested or statements about false positive or negative results.`

## Acceptance Criteria

**Design**
-   [ ] Visual and functional consistency with the existing guide design is maintained.

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
- No Figma design files are associated with this specific content update.
- Screenshots of the affected areas of the page are attached for reference.

guide-intro
guide-comment

### PR DESCRIPTION
**Pull request by mpbrown**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #7277 

## Changes Proposed

- Updates copy to the proposed changes

## Testing

- Deployed on dev6

## Screenshots / Demos

Bulk results upload guide header

Screenshot 2024-03-06 140830

Comment field description copy
Screenshot 2024-03-06 140855

### CODE REVIEW

**Comment by mpbrown** [comment]
@kenieh I pushed these copy changes up to [dev6](https://dev6.simplereport.gov/app/results/upload/submit/guide?facility=4854089c-512b-4145-ae0e-11ec5d7f2b12), let me know when you get a chance to give design signoff on this

**Review by fzhao99 — APPROVED** [review]

**Review by bobbywells52 — APPROVED** [review]
LGTM

**Comment by kenieh** [comment]
@tomi is currently taking a look! she was the one that made the suggestions of changes for this page.

**Comment by tomiobikunle** [comment]
@mpbrown just reviewed the changes - design signoff granted.

**Pull request merged**
