### PR TITLE
Test results list filter button works as expected

### PR DESCRIPTION
**Pull request by nathancrtr**
## Related Issue or Background Info

#1516 

The `Clear filter` button on the test results page does not actually clear applied filters. This patch fixes this and includes other minor language and formatting updates.

## Changes Proposed

* The "Clear filters" clears applied filters
    * Previously, it just closed the filter drawer  
* Actions text says "Filter" instead of "Get test results"
* Action label is singular ("Action" instead of "Actions")
* Date formatting follows MM/DD/YYYY convention. 
    * Date formatting is covered in a separate ticket (#350) but it's an easy fix for this case here.

## Additional Information
The issue (#1516) also requested the following change:

>  Refreshing the page clears the filters, which is not the expected behavior. Applied filters should remain when user refreshes page.

This was deemed out-of-scope for this work and will be addressed separately.

## Screenshots / Demos

https://user-images.githubusercontent.com/27730981/118699766-ea371300-b7df-11eb-8970-ebf34078426a.mov

## Checklist for Author and Reviewer
Please verify that the acceptance criteria are met.

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] ~Database changes are submitted as a separate PR~
- [x] ~GraphQL schema changes are backward compatible with older version of the front-end~

### Security
- [x] ~Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)~
- [x] ~Any dependencies introduced have been vetted and discussed~

## Cloud
- [x] ~DevOps team has been notified if PR requires ops support~
- [x] ~If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification~

### CODE REVIEW

**Review by nickscialli-usds — COMMENTED** [review]
This interaction still strikes me as funky. I think the big issue is that we clobber our DOM tree with a "Loading..." indicator, causing the drawer to close. I think if we stop preventing the rendering of the underlying `DetachedTestResultsList` component, we can fix this jarring interaction.

**Comment by nathancrtr** [comment]
@nickscialli-usds re: https://github.com/CDCgov/prime-simplereport/pull/1625#pullrequestreview-662582224

> This interaction still strikes me as funky. I think the big issue is that we clobber our DOM tree with a "Loading..." indicator, causing the drawer to close. I think if we stop preventing the rendering of the underlying `DetachedTestResultsList` component, we can fix this jarring interaction.

What aspect of the interaction are you referring to? I noted in [the issue](https://github.com/CDCgov/prime-simplereport/issues/1516#issuecomment-842630730) that the drawer closes when a filter is applied, which sounds like what you're talking about.

Since that's the current behavior on `main` and changing it isn't mentioned in the issue, @nullflux had suggested that be addressed in a separate ticket - especially since test result filtering is facing a large set of changes soon.

It does result in a pretty incongruous experience though. IMO it would be good to deal with it _before_ a full-fledged set of filters is built out so that the feature doesn't land with a weird UX.

(cc: @katiealoisi this continues our conversation from the related issue)

**Comment by nickscialli-usds** [comment]
@nathancrtr ah okay, thanks for pointing me to that discussion. We're all noticing the same issue; the question is the order in which to approach the work.

**Review by nickscialli-usds — APPROVED** [review]
👍

**Comment by nathancrtr** [comment]
@katiealoisi I created a separate issue for the drawer-closing problem: https://github.com/CDCgov/prime-simplereport/issues/1636.

I think it would be nice to address this sooner rather than later but I'll let the powers that be decide the timing (cc: @aliciabeckett-gov)

**Comment by katiealoisi** [comment]
Thx @nathancrtr! @aliciabeckett-gov would love to prioritize this. As others on this thread have noticed, it's really jarring and I worry that users will (1) not realize they have filters apply and (2) not know how to clear them.

**Pull request merged**
