### PR TITLE
Johanna/5786 clean up old schema support verify org part 2

### LINKED ISSUE #5786: Clean up "old org schema" related code
### Background
On May 3, 2023 we received a [support request to delete pending orgs that have been created on or before May 1, 2022](https://skylight-hq.slack.com/archives/C01F3DSC7V2/p1683125720386359). 

As part of this ticket #5632, we discovered some ["old org schema" related code to check for legacy orgs](https://github.com/CDCgov/prime-simplereport/pull/5778#discussion_r1191187858) using the old schema is no longer required.

### Action requested
Clean up old org schema related code in the codebase
(Good place to start is https://github.com/CDCgov/prime-simplereport/pull/3092/files# in `frontend/src/app/supportAdmin/PendingOrganizations/PendingOrganizations.tsx`)

### Acceptance Criteria
All "old org" code is removed.

### PR DESCRIPTION
**Pull request by johanna-skylight**
# BACKEND PULL REQUEST

## Related Issue

- Resolves #5786 

## Changes Proposed

- Update the type to reflect that the admin data is mandatory in pending organization and regenerated the graphql file.
- Deleted a method that was marked as unused.

## Testing
Code is available in dev1
- Regression testing for edit and verify a pending org.

### CODE REVIEW

**Review by BobanL — APPROVED** [review]
Changes look good! Tested in dev and was able to verify a pending organization

**Review by emyl3 — APPROVED** [review]
This LGTM!

(non-blocking and only noticed while testing your PR -- behavior currently exists in prod) One thing we may want to do in the future is add form validation for when we "Edit" a pending organization since we currently let users submit empty fields for required fields (with the exception of an org name -- if the user leaves that blank then there is an error message)

Screenshot 2023-05-23 at 17 00 27

Screenshot 2023-05-23 at 17 00 30

If you think this is worthwhile, I am happy to create a ticket for it 😸

**Comment by johanna-skylight** [comment]
> This LGTM!
> 
> (non-blocking and only noticed while testing your PR -- behavior currently exists in prod) One thing we may want to do in the future is add form validation for when we "Edit" a pending organization since we currently let users submit empty fields for required fields (with the exception of an org name -- if the user leaves that blank then there is an error message)
> 
> Screenshot 2023-05-23 at 17 00 27 Screenshot 2023-05-23 at 17 00 30
> If you think this is worthwhile, I am happy to create a ticket for it 😸

yes! Thanks for finding that @emyl3 please create the ticket and thanks again :D.

**Comment by emyl3** [comment]
> > This LGTM!
> > (non-blocking and only noticed while testing your PR -- behavior currently exists in prod) One thing we may want to do in the future is add form validation for when we "Edit" a pending organization since we currently let users submit empty fields for required fields (with the exception of an org name -- if the user leaves that blank then there is an error message)
> > Screenshot 2023-05-23 at 17 00 27 Screenshot 2023-05-23 at 17 00 30
> > If you think this is worthwhile, I am happy to create a ticket for it 😸
> 
> yes! Thanks for finding that @emyl3 please create the ticket and thanks again :D.

Done: https://github.com/CDCgov/prime-simplereport/issues/5867

**Pull request merged**
