### PR TITLE
Enable RSV and new test card

### PR DESCRIPTION
**Pull request by mpbrown**
# BACKEND PULL REQUEST

## Related Issue

- #6933 

## Changes Proposed

- Enables RSV single entry and new test card

## Testing

- How should reviewers verify this PR?

### CODE REVIEW

**Review by emyl3 — COMMENTED** [review]
Do we want to add `singleEntryRsvEnabled` for stg and training?

**Comment by mpbrown** [comment]
> Do we want to add `singleEntryRsvEnabled` for stg and training?

I think `application.yaml` already turns on `singleEntryRsvEnabled` for all environments except for prod where we explicitly had it disabled until ready so it should be inherited right?

**Comment by emyl3** [comment]
> > Do we want to add `singleEntryRsvEnabled` for stg and training?
> 
> I think `application.yaml` already turns on `singleEntryRsvEnabled` for all environments except for prod where we explicitly had it disabled until ready so it should be inherited right?

ahh yes! you are right -- sorry I didn't check there beforehand 😅 Thank you!

**Review by emyl3 — APPROVED** [review]
LGTM!

**Review by fzhao99 — APPROVED** [review]

**Pull request merged**
