### PR TITLE
Bump dockerfile nginx:1.21.1-alpine to nginx:1.23-alpine

### PR DESCRIPTION
**Pull request by snesm**
# FRONTEND PULL REQUEST

## Related Issue

- [Unsupported nginx](https://endoflife.date/nginx) docker image

## Changes Proposed

- Move from nginx:1.21.1-alpine to nginx:1.23-alpine (which will use the latest in the 1.23 line)
- This includes a dockerfile for Cypress testing

## Additional Information

- Current image: nginx:1.21.1-alpine vulnerabilities 40  (4 Critical, 24 High, 9 Medium, 3 Low)

## Testing

- How should reviewers verify this PR?
 
## Screenshots / Demos

- For large changes, please pair with a designer to ensure changes are as intended

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Comment by emmastephenson** [comment]
I still don't have Cypress running locally successfully (😬) so not sure I'm the best person to review this PR. @alismx, can you verify that running Cypress still works with this new version of nginx?

**Comment by alismx** [comment]
> I still don't have Cypress running locally successfully (grimacing) so not sure I'm the best person to review this PR. @alismx, can you verify that running Cypress still works with this new version of nginx?

@emmastephenson I'll look into this version change and report back. It'll be easier to incorporate this version change with that other cypress PR seeing as this directory will no longer exist after that merge.

**Comment by snesm** [comment]
Related to (or superseded by) https://github.com/CDCgov/prime-simplereport/pull/3688

**Comment by alismx** [comment]
I don't mind if we merge this, it looks good to go and works great! 

In the mean time, I've pulled this change into the other PR. I deleted the Nginx in the Cypress directory as it's no longer needed after the rework. The config from the Nginx directory is used instead.

https://github.com/CDCgov/prime-simplereport/blob/f7fea356dff1e4cba2358b55e3b0b08e51f6dcab/nginx/Dockerfile

**Comment by emmastephenson** [comment]
@snesm I believe this version bump was included in #3688, which was just merged to `main` earlier today. I think this PR can be safely closed, since the version bump is already in place. Thank you for bringing it to Alis's attention though!

**Comment by snesm** [comment]
Thanks @alismx !

**Pull request closed without merging**
