### PR TITLE
Bump net.javacrumbs.shedlock:shedlock-spring in /backend

### PR DESCRIPTION
**Pull request by emyl3**
# BACKEND PULL REQUEST

## Related Issue
- Reopening https://github.com/CDCgov/prime-simplereport/pull/7187 because checks on PR were not running
- Please see linked dependabot PR for description and testing results

## Changes Proposed
- Upgrade shedlock to version `5.10.2`

### CODE REVIEW

**Comment by emyl3** [comment]
deployed to dev4 and saw the cron job ran again
Screenshot 2024-02-02 at 10 01 21

**Review by fzhao99 — APPROVED** [review]
lgtm!

**Review by bobbywells52 — APPROVED** [review]
LGTM

**Review by mpbrown — APPROVED** [review]
LGTM!

**Pull request merged**
