### PR TITLE
Update vulnerable FHIR packages. Remove unneeded identity dependency.

### LINKED ISSUE #5047: Snyk - Update High and Critical vulnerabilities (Jan 2023)

### PR DESCRIPTION
**Pull request by rin-skylight**
# DEVOPS PULL REQUEST

## Related Issue

- Resolves #5047.

## Changes Proposed

- Updates FHIR dependencies to resolve https://security.snyk.io/vuln/SNYK-JAVA-CAUHNHAPIFHIR-3245104.
- Updates function app dependencies to resolve [SNYK-JS-JSONWEBTOKEN-3180020](https://app.snyk.io/vuln/SNYK-JS-JSONWEBTOKEN-3180020).

## Additional Information

- The function app was successfully verified on `dev7`.
- The application was smoke tested on `dev7` with no adverse effects noted.

## Testing

- Dependent functionality should be verified to ensure package upgrades have not made a deleterious impact.

### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Cloud
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Comment by rin-skylight** [comment]
NOTE: There is some debate about whether the FHIR dependencies modified herein constitute a proper fix for the reported security issue. Though a researcher has indicated that the fix is insufficient, they have yet to provide evidence supporting their indication. Until such time as their claims are founded, this fix has been deemed acceptable for our use.

**Comment by rin-skylight** [comment]
This has been successfully tested on `dev7`, including proper functioning of the function app. No adverse effects noted!

**Review by BobanL — APPROVED** [review]
tested in dev7 and looks good!

**Review by johanna-skylight — APPROVED** [review]
LGTM

**Pull request merged**
