### PR TITLE
remove index from keys

### LINKED ISSUE #5588: Remove index from keys
### Background
Array index should not be used as the key in components.  

### Action requested
* Replace the index value for key with another unique id.
    * https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6479&id=CDCgov_prime-data-input-client
### Acceptance Criteria
* No `key` property is set as the index.
    * https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6479&id=CDCgov_prime-data-input-client

### PR DESCRIPTION
**Pull request by BobanL**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #5588 

## Changes Proposed

- Remove the usage of index in keys as much as possible
  - In some cases, there are no unique values that could be used for keys ,like in the case of the email and phone number sections of person. There we try to use the both the value of the field and the index to ensure uniqueness and to resolve the code smell, that `key` has been moved out and into its own variable
  - Base64 encode certain values from the element so the value is more consistent
    - _Maybe this could be done better or isn't necessary?_ 
 
## Additional Information

- Removed ordering provider list since it was no longer used anywhere in the project
- The codesmell for [phone number](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6479&id=CDCgov_prime-data-input-client&open=AYTtR5kytwUHNlXi_ph5) / [email](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6479&id=CDCgov_prime-data-input-client&open=AYTtR5ketwUHNlXi_ph0) should be marked as will not fix since there is no unique value that comes with these fields. 

## Testing

- Ensure that no unique key error is thrown in the console of the browser.

### CODE REVIEW

**Comment by fzhao99** [comment]
going to briefly explore generating id's at the data level for phone numbers / emails before merging to address the last two places where we're using the index as a key

**Comment by fzhao99** [comment]
refactoring for those two components were too complicated, so this lgtm as is!

**Comment by fzhao99** [comment]
> going to briefly explore generating id's at the data level for phone numbers / emails before merging to address the last two places where we're using the index as a key

refactoring for those two components were too complicated, so this lgtm as is!

**Review by fzhao99 — APPROVED** [review]

**Review by johanna-skylight — APPROVED** [review]
LGTM!

**Pull request merged**
