### PR TITLE
Fix list-related accessibility issues in TOS

### LINKED ISSUE #3979: TOS contains lists for stylization purposes only
## Area or Component
Patient Experience - Terms of Service

## Quick Summary
There are several non-list elements contained in a list on the terms of service. "User", "Entity", etc are more appropriately subheadings. 

## Accessibility Violation
Two:
`<ul> and <ol> must only directly contain <li>, <script> or <template> elements.` https://dequeuniversity.com/rules/axe/4.4/list?application=AxeChrome

`Content is not a list but is marked as such`
https://axe.deque.com/rule-help/en/semantic-list-used-for-presentation
## Action Requested
See comments below for reference. The changes requested include:
- Consolidate list items and paragraph text in "Definitions," and bold defined words
- Change list items to subheadings in "Data rights and usage"
- Make "Accounts/registration" sentence case for consistency
- Switch user types to subheadings in "Other responsibilities," and change indentation of list items underneath 

Note: These changes were approved by the CDC’s Office of General Counsel through Mike Judd.

## Source Code (optional)
https://github.com/CDCgov/prime-simplereport/blob/c3e6b2dc330021e425e01657eaee613c51f9e11c/frontend/src/lang/en.ts#L368-L368

## Original Deque Issue
list | Ensures that lists are structured correctly | Non-list element contained the Terms of Service ("user", "entity" etc are more appropriately subheadings) | <ul> and <ol> must only directly contain <li>, <script> or <template> elements | https://dequeuniversity.com/rules/axe/4.4/list?application=AxeChrome | serious | No | No |   | ["ul:nth-child(27)"] | Fix all of the following:  List element has direct children that are not allowed inside <li> elements | <ul> | cat.structure,wcag2a,wcag131 | rnv7@cdc.gov | Patient Self Reg - Terms of Service | https://stg.simplereport.gov/app/register/9C7BB |   | 2022-07-13T20:53:04.526Z
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### PR DESCRIPTION
**Pull request by mehansen**
# FRONTEND PULL REQUEST

## Related Issue

Closes #3979 

## Changes Proposed

- Consolidate list items and paragraph text in "Definitions," and bold defined words
- Change list items to subheadings in "Data rights and usage"
- Make "Accounts/registration" sentence case for consistency
- Switch user types to subheadings in "Other responsibilities," and change indentation of list items underneath
- change font size for level 4 headers in TOS

## Testing

I will deploy to `dev2`. Check that changes look right for both English and Spanish versions of the TOS. You can access this page by finding the patient self-registration link in the org admin settings and pasting it in your browser.

## Screenshots / Demos
Screenshot of new subheadings with proposed font size:
Screen Shot 2022-10-04 at 11 28 03 AM

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved

### Content
- [ ] Any content changes have been approved by content team

### CODE REVIEW

**Comment by mehansen** [comment]
Looking for approvals from @vz3, @lauraykerr, and >= 1 dev before merging.

@vz3 just looking for a review on the font size choice for the level 4 headers (e.g. see screenshot and the diff in `PrimeStyles.css`)
@lauraykerr please confirm content looks good

**Review by zdeveloper — DISMISSED** [review]
LGTM from a dev perspective, thanks for working on this.

**Comment by lauraykerr** [comment]
@mehansen Content looks good to me, thanks! H2 and H3 look very close in size to me, so wondering if we want to bump H4 down to paragraph size and use current H4 size for H3 (but not sure if this has implications elsewhere). I defer to @vz3 though.

**Comment by vz3** [comment]
Agreed, can we make "For entity users" body+bold and drop "Accounts/Registration" by a header level.

**Comment by mehansen** [comment]
thanks @lauraykerr and @vz3!
from an accessibility standpoint, I think [it's bad form to follow h2 with an h4](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks) so I left the heading levels as is and changed the styling sizes for h3 and h4. h4 is now the same font size as the paragraph text. here's what that looks like:
Screen Shot 2022-10-04 at 2 47 46 PM

how does that look? I'll also redeploy to `dev2` so that should be ready in a few minutes

**Review by lauraykerr — APPROVED** [review]
LGTM, thanks @mehansen!

**Review by zdeveloper — APPROVED** [review]

**Comment by vz3** [comment]
This works, approving!

**Review by vz3 — APPROVED** [review]

**Pull request merged**
