### PR TITLE
[DO NOT REVIEW] Allow multiplex result submissions on test cards

### LINKED ISSUE #3481: Allow multiplex result submissions on test cards
### Background
Setting up the test card to enable multiplex result submissions.

### Action requested
When SR users select a Multiplex device in the Devices dropdown, we need to update the testcard UI to enable multiplex result submissions.

### Acceptance Criteria

- [ ] Increase width of the card
- [ ] Increase width of the Device dropdown (being able to see the full length of text is important for users to differentiate one device from another.)
- [ ] Add "Click here if test is inconclusive" button
- [ ] Auto-sizer?

### Design

Figma (WIP): https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6991%3A26520

**SCREENSHOT: comparing Multiplex card to SARs only card**

**DIFFERENT STATES OF THE TEST CARD**

**SPACING SPECS**

### Additional context
More potential design changes coming up for the test card—namely how we might inform users where multiplex results are being sent to.

### PR DESCRIPTION
**Pull request by nickclyde**
# FRONTEND PULL REQUEST

## Related Issue

- Resolves #3481

## Changes Proposed

- Adds support for submitting Flu A and Flu B results to the frontend
- Changes queries used in queue from `addTestResultNew` to `addTestResultMultiplex` and `editQueueItem` to `editQueueItemMultiplex`

## Additional Information

- Checking inconclusive makes result for all three diseases inconclusive
- If you have results marked for Flu A or B, then switch back to a COVID-only device, those Flu results will be cleared

## Testing

- Start a test, choose a device that supports Flu A/Flu B, submit with  Flu Results, see Flu Results on Results page.
 
## Screenshots / Demos
Screen Shot 2022-05-31 at 2 36 27 PM
Screen Shot 2022-05-31 at 2 36 37 PM
Screen Shot 2022-05-31 at 2 36 57 PM

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### CODE REVIEW

**Comment by emmastephenson** [comment]
I'll do a more through review tomorrow, but the initial pass looks good! The only thing I noticed is there may be some kind of debounce issue when switching from inconclusive -> not inconclusive results, shown here: https://watch.screencastify.com/v/PJ6KxHOrYLBfKRrcCZST

It doesn't really break the functionality and only happens occasionally (as far as I can tell, only if you click on a new result and then elsewhere on the card quickly) but I did want to flag.

I also wanted to flag the current behavior for extra-long names to @kenieh - if the name is too long, the DOB is pushed over to the side and "start timer" to the next row. This happens for both multiplex and regular tests, but it's more likely with multiplex since there's less real estate on the left side of the card. It's out of the scope of this PR to address, just wanted to make a note for future improvements if required.
Long name:
Screen Shot 2022-05-31 at 3 53 26 PM

**Comment by emmastephenson** [comment]
@kenieh that submit button becoming clickable is the bug I was talking about too - normally it only becomes clickable if you have results input for all three diseases, but there's an edge case interaction possible with the "inconclusive" checkbox that's currently making it clickable out of place.

**Comment by kenieh** [comment]
@emmastephenson got it that makes sense! thanks for clarifying.

**Review by emmastephenson — COMMENTED** [review]
Overall looks great! Only holding off on approvals because I'm not sure when we want to merge.

**Comment by emmastephenson** [comment]
Converting this to a draft to keep as reference, but this will probably be ultimately folded into a multiplex feature branch PR.

**Pull request closed without merging**
