### PR TITLE
Modify makefile to permit slot promotion for environments with integer identifiers

### PR DESCRIPTION
**Pull request by rin-skylight**
# DEVOPS PULL REQUEST

## Related Issue

- Due to the presence of multiple environments in a single resource group, our makefile needs to be reworked to permit deployments in our newer environments.

## Changes Proposed

- Modify the `promote` target to support `dev`-level environments with integer identifiers.

## Additional Information

- There are arguably cleaner implementations of this. If we get to the point that we add multiple environments in more than just the `dev` resource group, we will need to revisit multiple files. This works for our current use case, however, as we do not anticipate the addition of more environments outside of `dev` at this time.

## Testing

- Testing a deployment of an environment that is not dev2, dev3, or dev4 should be sufficient to verify proper functionality.
 
### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]

**Review by DanielSass — DISMISSED** [review]
🥇

**Review by DanielSass — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]
Looks good! I assume each Okta application has its own client id?

**Comment by rin-skylight** [comment]
> Looks good! I assume each Okta application has its own client id?

You are correct! I figured that out the hard way. 😅

**Review by nathancrtr — APPROVED** [review]
let's rock 👨‍🎤

**Pull request merged**
