### PR TITLE
Johanna/6596 clean up act warnings part2

### LINKED ISSUE #6596: Clean up the act wraps so we don't get warnings [Part2]
### Background
After the jest-dom version mismatches got fixed the project is again unhappy with any `act` wrappings/usage. The frontend test logs are again being polluted with warnings.

### Action requested
Clean up the act wraps to get rid of the warnings and implement the new way to use the `UserEvent` library in below files:

- SingleFileInput.test.tsx
- Header.test.tsx
-  MultiSelect.test.tsx
- MultiSelectDropdown.test.tsx
- ManagePatients.test.tsx
- ManagePhoneNumbers.test.tsx
- FacilityForm.test.tsx
- ManageUsers.test.tsx
- ManageUsersContainer.test.tsx
- PersonalDetailsForm.test.tsx

### Acceptance Criteria
The frontend test logs should not display warnings due to usage of `act` method.

### PR DESCRIPTION
**Pull request by johanna-skylight**
# FRONTEND PULL REQUEST

## Related Issue

Resolves #6596 

## Changes Proposed

Remove act wrappers.
Migrate the usage of userEvent to the new way of implementation.

## Additional Information
I have also fixed issues in other files that were not related to act wrappers like incorrect imports and incomplete testing data.

## Testing

All checks for frontend unit test should pass.

### CODE REVIEW

**Comment by johanna-skylight** [comment]
@alismx the workflows `build_frontend_image` and `build_frontend_lighthouse_image` have constantly failed in this PR. I have the latest code from `main`. Could this be related to the latest updates to our CI 🤔 ?

**Review by BobanL — DISMISSED** [review]

**Review by mehansen — COMMENTED** [review]
thanks for doing all this! it all looks great just a couple notes

**Comment by johanna-skylight** [comment]
Thanks for the review @mehansen I have addressed all the issues!.

**Review by BobanL — APPROVED** [review]

**Review by emyl3 — APPROVED** [review]
LGTM!

**Pull request merged**
