### PR TITLE
Upgrade USWDS 3.0

### PR DESCRIPTION
**Pull request by mpbrown**
# FRONTEND PULL REQUEST

## Related Issue

- #5737

## Changes Proposed

- Update frontend to use USWDS 3.0
- Refactor scss folder structure
- Remove npm script for sass compilation in favor of Create React App's built-in sass compilation via webpack

## Additional Information

- When `SASS_PATH` is set in `frontend/.env`, CRA's webpack configuration will give deprecation warnings because it does not use absolute paths. [See more on this CRA issue](https://github.com/facebook/create-react-app/issues/12329). Setting `SASS_PATH` in the npm scripts using absolute paths avoids this issue.

## Testing

- Verify that no frontend regression has occurred

### CODE REVIEW

**Review by johanna-skylight — DISMISSED** [review]
This is a very clean implementation Mike! Thanks for your work on this 🥇 .

**Review by nathancrtr — APPROVED** [review]
My smoke testing did not indicate any UI regressions as a result of this upgrade, and the Chromatic scan concurs.

Thanks for this one @mpbrown! Agreed that this looks like a really clean implementation. 🚀

**Review by johanna-skylight — APPROVED** [review]

**Review by zdeveloper — APPROVED** [review]
LGTM! thank you for getting this setup the correct way!

**Review by DanielSass — APPROVED** [review]
LGTM!

**Pull request merged**
