### PR TITLE
Add @RequireGlobalAdminUser on queries and mutations in admin.graphqls

### LINKED ISSUE #6114: [BUG] Some admin queries/mutations are available to non admins
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following queries/mutations can be accessed by non-admin users
- `resendToReportStream`
- `pendingOrganizations`
- `editPendingOrganization`
- `markPendingOrganizationAsDeleted`

### Steps To Reproduce

1. Fetch token of a non-admin user
2. Attempt to run any one of those queries/mutations in a lower environment

### Expected Behavior

Unauthorized message should be sent back

### Additional context

_No response_

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

### PR DESCRIPTION
**Pull request by BobanL**
# BACKEND PULL REQUEST

## Related Issue

- Resolves #6114 
- Some queries/mutations in our `admin.graphqls` did not have proper authorization checks and allowed non-admin users to use `resendToReportStream`, `pendingOrganizations`, `editPendingOrganization`, and `markPendingOrganizationAsDeleted`

## Changes Proposed

- Add the `@RequireGlobalAdminUser` annotation on the queries/mutations.

## Additional Information

- 

## Testing

- Available on dev3
- With a non-admin user, ensure that the queries and mutations cannot be run without an `authorization` error.
```gql
query PendingOrganizations {
    pendingOrganizations {
        externalId
        name
        adminFirstName
        adminLastName
        adminEmail
        adminPhone
        createdAt
    }
}
```
```gql
mutation ResendToReportStream {
    resendToReportStream(
        testEventIds: "790e8ae5-c726-43f9-b6e3-04a59f49bf43"
        fhirOnly: true
    )
}
```
```gql
mutation EditPendingOrganization {
    editPendingOrganization(
        orgExternalId: "AK-Dat-other-org-201bdd81-eb7c-41b3-beaf-2abed1d64af9"
        name: "Dat other org"
        adminFirstName: "Jim"
        adminLastName: "Jan"
        adminEmail: "elisalee@yopmail.com"
        adminPhone: "2485551234"
    )
}
```
```gql
mutation MarkPendingOrganizationAsDeleted {
    markPendingOrganizationAsDeleted(
        orgExternalId: "AK-Dat-other-org-201bdd81-eb7c-41b3-beaf-2abed1d64af9"
        deleted: true
    )}
```

### CODE REVIEW

**Comment by fzhao99** [comment]
is there a good way to try to hit the endpoints without admin user access? Would ghosting in locally as a non-admin user + Insomnia work?

**Comment by BobanL** [comment]
> is there a good way to try to hit the endpoints without admin user access? Would ghosting in locally as a non-admin user + Insomnia work?

Locally, you could use the authorization token `Bearer SR-DEMO-LOGIN ben@example.com` for non admin and `Bearer SR-DEMO-LOGIN ruby@example.com` for admin. I think testing with Insomnia or Postman is the only way to test this though.

Here are the 4 problem queries/mutations examples. You'll just need to get valid data for the organization ones though. 

```gql
query PendingOrganizations {
    pendingOrganizations {
        externalId
        name
        adminFirstName
        adminLastName
        adminEmail
        adminPhone
        createdAt
    }
}
```
```gql
mutation ResendToReportStream {
    resendToReportStream(
        testEventIds: "790e8ae5-c726-43f9-b6e3-04a59f49bf43"
        fhirOnly: true
    )
}
```
```gql
mutation EditPendingOrganization {
    editPendingOrganization(
        orgExternalId: "AK-Dat-other-org-201bdd81-eb7c-41b3-beaf-2abed1d64af9"
        name: "Dat other org"
        adminFirstName: "Jim"
        adminLastName: "Jan"
        adminEmail: "elisalee@yopmail.com"
        adminPhone: "2485551234"
    )
}
```
```gql
mutation MarkPendingOrganizationAsDeleted {
    markPendingOrganizationAsDeleted(
        orgExternalId: "AK-Dat-other-org-201bdd81-eb7c-41b3-beaf-2abed1d64af9"
        deleted: true
    )}
```

**Review by emyl3 — APPROVED** [review]
Tried this on dev5 since I had a user that wasn't a support admin and making these requests via postman resulted in an error with the message "header: Unauthorized; body: Please check for errors and try again" LGTM! Thank you for your thoroughness on this! 🔐

**Review by fzhao99 — APPROVED** [review]
verified on dev3

**Pull request merged**
