### PR TITLE
chore(dependabot): update reviewers and add new package ecosystem for…

### LINKED ISSUE #6894: Update reviewers for dependabot
As we make team adjustments, dependabot reviews will need to be updated.

### PR DESCRIPTION
**Pull request by alismx**
# DEVOPS PULL REQUEST

## Related Issue

- Resolves  #6894 

## Changes Proposed 

This Pull Request:
- Adds a review segment for Docker files in the root directory.
- Adjust the reviewers.
- Removes Alis and Rin as hard-coded reviewers across all package ecosystems.

This change aims to streamline the review process by specifying teams rather than individual users.

## Additional Information 

We need to create a team `cdcgov/simplereport-devsecopsreviews`.

## Testing 

This PR changes the configuration and does not introduce changes to the application's functionality. Validation requires monitoring future Dependabot PRs to observe if they align with the new configurations.

### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Review by BobanL — DISMISSED** [review]
👍

**Review by emyl3 — DISMISSED** [review]
LGTM!

**Comment by alismx** [comment]
This will be reworked to match the expectations set in SR eng sync.

**Review by fzhao99 — APPROVED** [review]

**Review by emyl3 — APPROVED** [review]
Thank you!

**Pull request merged**
