### PR TITLE
Remove cloud.gov deploy

### PR DESCRIPTION
**Pull request by timothybest-usds**
in favor of the staging work being done in azure https://github.com/CDCgov/prime-central/issues/146

### CODE REVIEW

**Comment by benwarfield-usds** [comment]
I would prefer to keep our existing CD environment working until we get working CD into Azure—especially since it seems like the plan for the staging environment isn't really suitable for either demos or QA.

**Comment by timothybest-usds** [comment]
My understanding was the demo env https://demo.simplereport.org/ was an azure env

**Comment by benwarfield-usds** [comment]
Yeah, but @pete-usds hates the infrastructure and as far as I know it's all manually deployed. Let's sync sometime soon about what envs we need and how close we are to having them--I'm not sure anybody except possibly Pete has the full picture, which seems bad given Pete's imminent disappearance.

**Comment by pete-usds** [comment]
Yep demo is in azure, same steps to deploy as beta just change "beta" to "demo" in pretty much all the instructions! Still lots of manual stuff as Ben indicated.

**Comment by timothybest-usds** [comment]
@benwarfield-usds good to merge now that we have CD with the dev env?

**Comment by benwarfield-usds** [comment]
I would say no, until that deploy has been QC'd a bit better and we've sorted out how we're using our environments for story QA.

**Review by benwarfield-usds — APPROVED** [review]
OK, fine, I agree that we don't need the cloud.gov deploys any more. Though I gotta say, I feel pretty good about not deep-sixing this back in November. 😁

**Pull request merged**
