### PR TITLE
refactor findSupportedDiseaseByNameContains to findByName

### PR DESCRIPTION
**Pull request by zdeveloper**
# BACKEND PULL REQUEST

## Related Issue

- `findSupportedDiseaseByNameContains` causes the following error in future spring versions

```java
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [\] did not match expected type [java.lang.String (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [\] did not match expected type [java.lang.String (n/a)]
	at app//org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at app//org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at app//org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at app//org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at app//org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at app//org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at app//com.sun.proxy.$Proxy211.findSupportedDiseaseByNameContains(Unknown Source)
	at app//gov.cdc.usds.simplereport.service.DiseaseService.initDiseases(DiseaseService.java:27)
	at app//gov.cdc.usds.simplereport.service.DiseaseService$$FastClassBySpringCGLIB$$e4305785.invoke(<generated>)
	at app//org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at app//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at app//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at app//org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at app//org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at app//org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at app//gov.cdc.usds.simplereport.service.DiseaseService$$EnhancerBySpringCGLIB$$d844157.initDiseases(<generated>)
	at app//gov.cdc.usds.simplereport.SimpleReportApplication.lambda$initDiseasesOnStartup$0(SimpleReportApplication.java:50)
	at app//org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777)
	... 84 more

```

## Changes Proposed

- refactor `findSupportedDiseaseByNameContains` to `findByName` in `SupportedDiseaseRepository` and utilize `Optionals`

### CODE REVIEW

**Comment by nickclyde** [comment]
What is actually going on with the error here? Is it not possible to do a `Contains` repo method at all in the new Spring? That seems like a pretty big breaking change

**Comment by emmastephenson** [comment]
> What is actually going on with the error here? Is it not possible to do a `Contains` repo method at all in the new Spring? That seems like a pretty big breaking change

It seems like this is an underlying bug within Hibernate: https://github.com/spring-projects/spring-data-jpa/issues/2472#issue-1176907733

@zdeveloper Seems like it's fixed in the latest version of Spring, or we can pin the Hibernate dependency to a working version.

**Comment by zdeveloper** [comment]
> > What is actually going on with the error here? Is it not possible to do a `Contains` repo method at all in the new Spring? That seems like a pretty big breaking change
> 
> It seems like this is an underlying bug within Hibernate: [spring-projects/spring-data-jpa#2472 (comment)](https://github.com/spring-projects/spring-data-jpa/issues/2472#issue-1176907733)
> 
> @zdeveloper Seems like it's fixed in the latest version of Spring, or we can pin the Hibernate dependency to a working version.

Hmm I got this problem on Spring Boot 2.6.7, which is the latest.
Also I would argue against using the contains, since it uses the `like` operation under the hood, which is slower than findByName. I am honestly not sure why the contains was used in the first place, since we already know the name, might as well just use it directly to load the diseases.

**Comment by nickclyde** [comment]
According to the thread Emma linked, it looks like it will be fixed in Hibernate 5.6.9, but that's not released yet. Anyways, Zedd I think you're right that there's no need to use contains here anyways. 👍

**Review by nickclyde — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]

**Pull request merged**
