### PR TITLE
TF: remove old DBs and switch to new DBs

### PR DESCRIPTION
**Pull request by jdorothy**
# DEVOPS PULL REQUEST

## Related Issue

#3358 

## Changes Proposed

- Remove TF code for old DBs
- Switch any resource referencing the old DBs to the new DBs

## Additional Information

- The two `log` blocks removed from `azurerm_monitor_diagnostic_setting.postgres` is intentional - these blocks are not supported by Postgres Flexible DB.
- The `terraform plan` has a failing change regarding the `azurerm_postgres_flexible_server_database.metabase` - this is because `persistent` hasn't updated its outputs yet from this change. If actually run, this value will update, and the _real_ error is that then Terraform will think it has to create that database in the new flexible DB for some reason (it doesn't, it already exists). So, a `terraform import` for that resource in each env will be needed to finish the deploy.

## Testing

- This has been tested against and deployed to `pentest`.
 
### Infrastructure
- [ ] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

## Cloud
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by rin-skylight — APPROVED** [review]
Wow, what a milestone. Thanks for getting all of this done; I know it was a major lift.

**Review by emmastephenson — APPROVED** [review]
This looks great! Thanks for all your work on this.

**Review by zdeveloper — APPROVED** [review]
LGTM! any reason why the TF checks are failing?

**Comment by jdorothy** [comment]
> LGTM! any reason why the TF checks are failing?

Check out the 2nd bullet point under Additional Information

**Pull request merged**
