### PR TITLE
Old pending org schema clean up in verify org view Part 1/2

### PR DESCRIPTION
**Pull request by johanna-skylight**
# FRONTEND PULL REQUEST

## Related Issue

- Partially implements #5786 

## Changes Proposed

- Removed all checks for org types using the old graphql schema in edit/verify org page.

## Additional Information

- This is only the frontend clean up and a backend ticket will come after.
- I was able to verify that no orgs with the old schema are ever returned to the frontend by checking [PR 3989](https://github.com/CDCgov/prime-simplereport/pull/3989).

## Testing
Code is available in Dev1
- Sign up for a new org
- Edit the org data
- Verify the org

### CODE REVIEW

**Review by BobanL — DISMISSED** [review]

**Review by emyl3 — DISMISSED** [review]
LGTM! Could not find any more of the old code on the frontend! Added a pending org, edited and verified successfully!

**Comment by johanna-skylight** [comment]
Summary of changes in the cypress front:
 - Fixed order of backend calls in the multiplex spec (first authentication hooks trigger and then resetting of the data).
 - Swap the order of specs 09 and 10 because if spec of save and test had multiple attempts the state of the test queue was getting messed up for the multiplex test. Ideally we should clean the queue but that is more effort than I want to put right now.
 - Removed the logic to soft delete the devices created during the e2e testing as this was breaking the default selection of a device in the queue-item component... hence marking all the queue items with error states and messing up assertions in the save and test spec.

**Review by BobanL — APPROVED** [review]
👌

**Review by emyl3 — APPROVED** [review]
LGTM! test in dev as well!

**Pull request merged**
