### PR TITLE
add experian link back to the experian details form and updated labels

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- adds experian link back in to the experian personal details form

## Changes Proposed

- add Experian link back in to the experian personal details form
- unbold birthday field
- change sign up label `Email address` to `Work Email`
- add step indicators to the sign-up flow

## Screenshots / Demos
image
image
image

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by nickclyde — APPROVED** [review]

**Comment by Rebecca-LM** [comment]
@zdeveloper for question 2 of the Experian thing looks like we should replace "currently or have" with  "...currently have, or...." everything else looks good, thank you!

**Review by Rebecca-LM — CHANGES_REQUESTED** [review]
@zdeveloper for question 2 of the Experian thing looks like we there's a typo, so we should replace "currently or have" with "...currently have, or...." Everything else looks good, thank you!

**Comment by zdeveloper** [comment]
@Rebecca-LM oh yeah the displayed questions are just examples for the mocks, ill update it. the real questions will be random and loaded from experian on the spot

**Comment by zdeveloper** [comment]
@Rebecca-LM change done! (updated the screenshot)

**Review by Rebecca-LM — APPROVED** [review]

**Pull request merged**
