### PR TITLE
Add UI for notifying users of self-registration duplicates

### LINKED ISSUE #1379: Flag duplicate patient profiles in patient self-registration UI
Spec: https://docs.google.com/document/d/1gVutot1vYrHHQYg6ExeTA6bhWib3YrE_77C1VItzAqk/edit  
Figma design: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3434%3A11296

Now that the patient self-registration is live we are seeing patients register themselves multiple times. To prevent duplicate profiles we will let users know they are already registered if there is an exact match on first name, last name, DOB, and zip code.

- [ ] In self-registration, if the profile is determined to be a duplicate the user will not be allowed to proceed with registering.

##Screenshots
Figma design: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3434%3A11296

See "Patient self-registration flow" section

### PR DESCRIPTION
**Pull request by nathancrtr**
## Related Issue or Background Info

- Closes #1379

Delivering this is blocked on:
- [ ] Translations for the duplicate warning modal

## Changes Proposed
- Adds a duplicate check UI
- Enhances the common modal component to account for variants. Currently, only the "warning" variant is developed

## Screenshots / Demos

The duplicate experience can be viewed in storybook here: https://60a556a7c807cc0039ec6786-vwzzccjotl.chromatic.com/?path=/story/app-self-registration--duplicate

### UI
- [] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [n/a] Database changes are submitted as a separate PR
  - [n/a] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [n/a] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [n/a] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [n/a] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [n/a] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [n/a] Any dependencies introduced have been vetted and discussed

## Cloud
- [n/a] DevOps team has been notified if PR requires ops support
- [n/a] If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification

### CODE REVIEW

**Comment by nathancrtr** [comment]
@Rebecca-LM: @kenieh and I noticed that when the duplicate patient modal appears and and forces the user to exit sign-up, it redirects to the normal "registration success" page:

Screen Shot 2021-09-02 at 12 57 07 PM

The second paragraph should still be OK, but the first paragraph struck us as confusing. What are your thoughts?

**Comment by Rebecca-LM** [comment]
@nickclyde what are they seeing right before this screen? And what do we want them to do, ideally at this point?

**Comment by emmastephenson** [comment]
@nathancrtr can you provide Rebecca with a little more context on this flow?

**Comment by nathancrtr** [comment]
> @nickclyde what are they seeing right before this screen? And what do we want them to do, ideally at this point?

This modal appears on the self-registration form. Once a patient has entered all of their information that we consider identifying (first name, last name, DOB, postal code), we perform the check to see if a patient matching that identifying data already exists in that facility. If so, the modal will appear.

If a patient _does_ get this modal during self-registration there is nothing more for them to do. We're basically claiming they have already registered and no further action from them is required. It just feels mildly confusing to congratulate them for completing their patient profile when they technically didn't 🙂 

You can check out the [storybook](https://60a556a7c807cc0039ec6786-vwzzccjotl.chromatic.com/?path=/story/app-self-registration--duplicate) if you're curious. The modal will appear after you click away from a field after entering any values for `First name`, `Last name`, `Date of birth`, and `Postal code`.

**Comment by Rebecca-LM** [comment]
> > @nickclyde what are they seeing right before this screen? And what do we want them to do, ideally at this point?
> 
> This modal appears on the self-registration form. Once a patient has entered all of their information that we consider identifying (first name, last name, DOB, postal code), we perform the check to see if a patient matching that identifying data already exists in that facility. If so, the modal will appear.
> 
> If a patient _does_ get this modal during self-registration there is nothing more for them to do. We're basically claiming they have already registered and no further action from them is required. It just feels mildly confusing to congratulate them for completing their patient profile when they technically didn't 🙂
> 
> You can check out the [storybook](https://60a556a7c807cc0039ec6786-vwzzccjotl.chromatic.com/?path=/story/app-self-registration--duplicate) if you're curious. The modal will appear after you click away from a field after entering any values for `First name`, `Last name`, `Date of birth`, and `Postal code`.

Gotcha, this is helpful. So we need alternate copy for that first line so we're not saying thanks for completing a profile? Do we basically want to tell them they can now go get a test because they're in the system, or to contact someone for help, or something else?

**Comment by nathancrtr** [comment]
> So we need alternate copy for that first line so we're not saying thanks for completing a profile? Do we basically want to tell them they can now go get a test because they're in the system[...]?

Precisely! At that point they can just show up at the testing site, no further action from them required.

**Comment by Rebecca-LM** [comment]
@nathancrtr how does this look?

Header: Registration complete
[x Testing facility x]

Body: **First name Last name**, you're already registered at [x Testing facility x] and your patient profile is complete.

(keep second sentence as is)

**Pull request merged**
