### PR TITLE
add indiana

### PR DESCRIPTION
**Pull request by fzhao99**
Makes Indiana live

resolves https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/3968

### CODE REVIEW

**Review by johanna-skylight — DISMISSED** [review]
LGTM 🎉

**Review by emyl3 — DISMISSED** [review]
Hooray! Thank you, Bob! 😹

**Comment by fzhao99** [comment]
@johanna-skylight  @emyl3  turns out we were using Indiana in a frontend test that was verifying the failure path of someone trying to sign up in an unavailable state 😅. 

i went ahead and changed it. apologies for the duplicate approvals!

**Comment by emyl3** [comment]
> @johanna-skylight @emyl3 turns out we were using Indiana in a frontend test that was verifying the failure path of someone trying to sign up in an unavailable state 😅.
> 
> i went ahead and changed it. apologies for the duplicate approvals!

hahah what are the odds! thanks for catching that and no worries at all!

**Review by emyl3 — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]
Thanks for taking care of this Bob!

**Pull request merged**
