### PR TITLE
Add new PR templates

### PR DESCRIPTION
**Pull request by emmastephenson**
The meta-PR review...adding new PR templates!

The result of engineering sync on 3/10/22.

### CODE REVIEW

**Comment by emmastephenson** [comment]
@zdeveloper as primary reviewer
@rin-skylight would appreciate extra eyes on DevOps template
No testing reviewer required.

All, please feel free to leave suggestions on these templates! Happy to add or remove checklist items.

**Review by nickclyde — COMMENTED** [review]
Should we have one for PRs that include both backend and frontend changes?

**Comment by emmastephenson** [comment]
> Should we have one for PRs that include both backend and frontend changes?

I was thinking the existing PR template could be used for that, but I'm also happy to make a more specific one!

**Review by zdeveloper — APPROVED** [review]
Thank you!

**Review by jdorothy — APPROVED** [review]
Thank you!

**Review by rin-skylight — APPROVED** [review]
I love this. Thank you for putting all of these together! The DevOps one looks great, and I believe it covers all of what we need for the time being.

**Pull request merged**
