### PR TITLE
Add analytics skeleton page

### LINKED ISSUE #2480: v0: Add skeleton analytics page
### Description
Create a new page for the dashboard tab. 

### Proposed solution 
Create a new page, `COVID-19 testing data`, that is only visible to admin users. 

### Additional context
This page needs to be feature-flagged until we're ready to turn on analytics.

Design from @vz3:
analytics sketch

### PR DESCRIPTION
**Pull request by nickclyde**
## Related Issue or Background Info

- Resolves #2480

## Changes Proposed

- Adds a skeleton page to match the design in #2480, with data to be filled in with later tickets
- Add a basic test
- Add a story

## Additional Information

- Used screenshots in place of graphs/tables to be implemented in later tickets

## Screenshots / Demos
image

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]

**Comment by vz3** [comment]
Design feedback:
- Latest comp has a drop for a role selector rather than the table. Will share here. Would like to pair around the controls up top. Additionally, the selected state for roles should appear in date range.
- On date range `12/1/2021-12-31/2021` should be `12/1/2021 &emdash; 12/31/2021` (@Rebecca-LM does style guide have date ranges?)
- Little more whitespace above Abby Road School District
- Card labels should be non-bolded "Tests conducted" "Positive tests" "Positivity rate"
- Numbers should be aligned to vertical center.
- Pls double check that the card has same vertical as horizontal dimension.
- ^ 2 should use a triangle glyph, red if up, green if down. I can provide if needed.

**Comment by Rebecca-LM** [comment]
@vz3 AP style says to use regular hyphens for date ranges, but if we want to use an en dash (not em dash) I'd be cool with this (looks a lil nicer) and I'll add it to the style guide. Lmk what you prefer. FYI on below in case you're not familiar. :)

Em dashes and en dashes (— vs –) ... The en dash is approximately the length of the letter n, and the em dash the length of the letter m. The shorter en dash (–) is sometimes used to mark ranges.

**Comment by nickclyde** [comment]
@vz3 just pushed up the changes you suggested except the first bullet, see updated screenshot. Let's pair sometime next week on the controls up top!

**Comment by Rebecca-LM** [comment]
@vz3 also flagging "role" language here. We discussed "Type of person tested" but hadn't decided on a good term for this.

**Comment by vz3** [comment]
Updated comp can be found here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3996%3A13764

**Comment by Rebecca-LM** [comment]
@vz3 @nickclyde lmk when this needs a content pass

**Pull request merged**
