### PR TITLE
use /actuator/health for backend health checks

### PR DESCRIPTION
**Pull request by BobanL**
# DEVOPS PULL REQUEST

## Related Issue

- During the Spring boot 3 update, we noticed that the [deployments](https://github.com/CDCgov/prime-simplereport/actions/workflows/deployDev.yml?query=branch%3Aboban%2Fspring-upgrade) were failing because the app gateway was checking the health status on the `/` endpoint. The `/` endpoint was failing our security rules because we did not also permit access to `/index.html`. It seems better that we just remove access to `/` and then use `/actuator/health` for health check accross the app.

## Changes Proposed

- Add probe to app_gateway for backend services that will check the `/actuator/health` endpoint
- Replace all places where the backend's `/health` was being check with `/actuator/health`
- Remove access to `/` endpoint in security config
- Remove `index.html`

## Additional Information

- The `/health` endpoint only ever returns 200 OK which is not that useful. SpringBoot already gives us more information in actuator so I thought it would be best to just remove it to reduce confusion.
- App Gateway uses health probes to do backend health checks and app services uses the new endpoint
Dev5 now:
image
image
image

Dev6:
image

image

image

## Testing

- Verify 401 not authorized on [`/health`](https://dev5.simplereport.gov/api/health) and [`/`](https://dev5.simplereport.gov/api/) and 200 OK on [`/actuator/health`](https://dev5.simplereport.gov/api/actuator/health)
- Application can be deployed, feel free to redeploy to dev5 (Currently deployed on dev5)

### CODE REVIEW

**Review by zdeveloper — DISMISSED** [review]
LGTM! thank you for uncovering and fixing this

**Review by fzhao99 — APPROVED** [review]
🎉 

three cheers for boban

**Review by alismx — CHANGES_REQUESTED** [review]
Is the plan to remove the static-http(s) probes in your other PR?

Does `/api/actuator/health` endpoint work for metabase? I thought the standard metabase healthcheck endpoint was `/api/health`.

**Comment by BobanL** [comment]
> Is the plan to remove the static-http(s) probes in your other PR?

No,  `Static-http` probe will stay to check the status of the static site.

> Does `/api/actuator/health` endpoint work for metabase? I thought the standard metabase healthcheck endpoint was `/api/health`.
Good callout, I have reverted the health check for metabase!

**Review by alismx — APPROVED** [review]
Looks good! Thanks for these updates.

**Review by fzhao99 — APPROVED** [review]

**Pull request merged**
