### PR TITLE
Validate addresses in the facility form

### LINKED ISSUE #1189: Add frontend address validation to facility forms
create organization, facility add, and facility edit forms should prompt the user with a smarty streets normalized address option in the same manor as the person form.

Contact Tim if you need a smarty streets token for local testing.

Designs for confirming two addresses at once:

### PR DESCRIPTION
**Pull request by nickscialli-usds**
## Related Issue or Background Info

- Resolves #1189

## Changes Proposed

- Updates `AddressConfirmationModal` to accept any number of addresses
- Retrofits `PersonForm` to use new `AddressConfirmationModal` interface
- Adds `AddressConfirmationModal` to `FacilityForm` to check both the Facility's address and the Ordering Provider's address (if provided)
- Adds tests for `FacilityForm`

## Additional Information

- Some things that might be worth smoke-testing:
    - Person address validation still works
    - Facility address needs fixing but Ordering Provider address does not need fixing
    - Ordering Provider address needs fixing but Facility address does not need fixing
    - Both need fixing
    - Neither needs fixing

## Screenshots / Demos

Currently on the test environment: https://test.simplereport.gov

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [N/A] Database changes are submitted as a separate PR
- [N/A] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [N/A] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [N/A] Any dependencies introduced have been vetted and discussed

## Cloud
- [N/A] DevOps team has been notified if PR requires ops support
- [N/A] If there are changes that cannot be tested locally, this has been deployed to our Azure `test` environment for verification

### CODE REVIEW

**Comment by katiealoisi** [comment]
Can you add a colon to the end of "Please select an option for ordering provider address to continue" for consistency?

I also noticed that the validation appears for ordering provider even if the user leaves the address field blank. How hard would it be to hide the ordering provider validation when it's blank?

**Comment by nickscialli-usds** [comment]
@katiealoisi yes on the colon, on the latter part I could have sworn I took care of that already, let me see if I messed up or it's a caching thing

**Comment by nickscialli-usds** [comment]
@katiealoisi here's what I am seeing when the Ordering Provider address is left blank. Did you leave all address fields blank for Ordering Provider (street, street2, city, state, zip)?

only one validation

**Comment by katiealoisi** [comment]
@nickscialli-usds I just tried it again and it's working as you described! When I tried it before, I left all fields blank. The only thing that came up in the address validation was "USA".

**Comment by nickscialli-usds** [comment]
@katiealoisi okay great. That's how it was prior to my latest deploy to the test environment, so my guess is you got a cached version of the app when you tried previously 🤷‍♂️

**Review by nathancrtr — APPROVED** [review]
LGTM 🌮

**Pull request merged**
