### PR TITLE
Update node-fetch resolution to close security vulnerability

### PR DESCRIPTION
**Pull request by alismx**
# DEVOPS PULL REQUEST

## Related Issue

- node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor
- [CWE-173](https://cwe.mitre.org/data/definitions/173.html)
- [CWE-200](https://cwe.mitre.org/data/definitions/200.html)
- [CWE-601](https://cwe.mitre.org/data/definitions/601.html)

## Changes Proposed

- Update node-fetch resolution to a version that is not vulnerable

## Additional Info

- This is prep for turning on Dependabot security PRs.

### Infrastructure
- [x] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Review by rin-skylight — APPROVED** [review]

**Review by emyl3 — APPROVED** [review]
deployed to dev2 temporarily and smoke tested. LGTM! 👍

**Comment by alismx** [comment]
@rin-skylight @emyl3 I didn't change anything, but I had to force-push the branch because the actions didn't properly kick off.

**Review by emyl3 — APPROVED** [review]
thank you for the heads up, alis! LGTM!!

**Review by rin-skylight — APPROVED** [review]
🚀

**Pull request merged**
