### PR TITLE
fix bug adding new user

### PR DESCRIPTION
**Pull request by BobanL**
# BACKEND PULL REQUEST

## Related Issue

- Quick fix to #5945 

## Changes Proposed

- Use both the search and q results to fetch a user when updating user privileges.

## Additional Information

- When users are added, Okta's backend needs time to propogate the new user to be `searchable` and by the time we attempt to update the users permissions the user is not available.  This is similar to the issue we previously had with [groups](https://github.com/okta/okta-sdk-java/issues/750). By using both the search and q results we can make sure this isn't a problem.
- This is a TEMP fix until the refactor to just set roles and facilities in a single mutation is done. 

## Testing

- Test adding a new user in any env, it will probably fail. Test again in dev3 and it should work!

### CODE REVIEW

**Review by johanna-skylight — APPROVED** [review]
LGTM!

**Review by emyl3 — APPROVED** [review]
Successfully added a user with no error in dev3. :) 

out of curiosity, do we have a ticket to track this work: "refactor to set roles and facilities in a single mutation"?

Thank you for this fix, Boban!

**Comment by mehansen** [comment]
this is interesting! how does using both search and the other kind of query fix this? would the username query always work even if the name isn't searchable yet?

**Comment by BobanL** [comment]
> Successfully added a user with no error in dev3. :)
> 
> out of curiosity, do we have a ticket to track this work: "refactor to set roles and facilities in a single mutation"?
> 
> Thank you for this fix, Boban!

I was going to open a new PR shortly after this to do this.



> this is interesting! how does using both search and the other kind of query fix this? would the username query always work even if the name isn't searchable yet?

In this case, I believe using query alone would be sufficient actually! Search is the [recommended](https://developer.okta.com/docs/reference/api/users/#content-type-header-fields-2:~:text=Finds%20a%20user%20that%20matches%20firstName%2C%20lastName%2C%20and%20email%20properties.%20However%2C%20Okta%20recommends%20the%20search%20parameter.) . I thinking sticking with search in the long run will be better and I can just remove the query parameter from update once addUser supports `accessAllFacilities` and `facilities`.

**Comment by BobanL** [comment]
Okta Search vs Q results may differ a little. Read more about it [here](https://github.com/okta/okta-sdk-java/issues/750).

**Pull request merged**
