### PR TITLE
Bump okta-spring-boot-starter from 2.0.0 to 2.1.6

### PR DESCRIPTION
**Pull request by snesm**
# BACKEND PULL REQUEST

## Related Issue

- [Snyk issue](https://app.snyk.io/org/prime-simplereport/project/c406c1e0-bc05-4f30-bbc1-e0b72bb1b3ee#issue-SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-2833359)
- [Snyk issue](https://app.snyk.io/org/prime-simplereport/project/c406c1e0-bc05-4f30-bbc1-e0b72bb1b3ee#issue-SNYK-JAVA-COMNIMBUSDS-1243767)
- [Snyk issue](https://app.snyk.io/org/prime-simplereport/project/c406c1e0-bc05-4f30-bbc1-e0b72bb1b3ee#issue-SNYK-JAVA-ORGSPRINGFRAMEWORKSECURITY-1314741)

## Changes Proposed

- No functional changes

## Additional Information

- [change log](https://github.com/okta/okta-spring-boot/releases)
- note that previous upgrade attempts from 2.0.0 to 2.1.* encountered an [issue](https://github.com/CDCgov/prime-simplereport/pull/1941)

## Testing

- Validate Okta login functionality

## Checklist for Primary Reviewer

- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [ ] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] GraphQL schema changes are backward compatible with older version of the front-end
- [ ] Changes comply with the SimpleReport Style Guide
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed
- [ ] Any changes to the startup configuration have been documented in the README

----

### CODE REVIEW

**Review by rin-skylight — CHANGES_REQUESTED** [review]
Simple smoke testing of this PR fails with an infinite Okta login loop. This code should not be merged in its present state.

**Comment by snesm** [comment]
Thanks @rin-skylight !

@emmastephenson Can the "Okta login loop" be added to an upcoming sprint?  It may also need to coincide with the Spring upgrade efforts.

**Comment by rin-skylight** [comment]
> Thanks @rin-skylight !
> 
> @emmastephenson Can the "Okta login loop" be added to an upcoming sprint? It may also need to coincide with the Spring upgrade efforts.

@snesm Respectfully, it's the responsibility of the contributing engineer to confirm their code works with the existing project. This includes making sure you go through a full local test, including a smoke test and running the unit tests. If a bug like this is introduced, the contributing engineer should diagnose what's going wrong, and try to come up with an alternative. Only if that doesn't work should we look at putting another item in the backlog to be prioritized and added into a sprint; we've got an extensive roadmap, and it can be very difficult to fit new items in unless they are absolutely essential.

Security issues are very important, but they require that same standard of testing. There are usually a few separate ways that we can go about closing a hole; if upgrading a large dependency doesn't work, another approach is to use a more surgical upgrade.

In this case, the high-priority vulnerabilities you've targeted here were fixed in a different PR by locking the individual dependencies, rather than their parent packages. It makes `build.gradle` a bit messier to do so, but that will hold us over as we work on the major upgrades behind-the-scenes.

**Comment by snesm** [comment]
Remediation via: https://github.com/CDCgov/prime-simplereport/pull/4226

Great work @rin-skylight, Thank you!

**Pull request closed without merging**
