### PR TITLE
Mike/5844 tests bulk upload results fhir

### LINKED ISSUE #5844: Add test coverage to BulkUploadResultsToFhir
BulkUploadResultsToFhir.class has really poor coverage. would like to write tests for

- Input csv file, assert on json bundle at the output
- Write performance class tests, assert on the bunders speed to not take more than 30 seconds on a 5000 row file
- consider mocking the clock and the UUID generator to obtain predictable bundle.
- make sure the time fields are considered in the senders timezone (from the testing facility address) and the the backend server's

### PR DESCRIPTION
**Pull request by mpbrown**
# BACKEND PULL REQUEST

## Related Issue

- Closes #5844 

## Changes Proposed

- Adds performance test for the bulk uploader on a large csv file
- Adds regression test for bulk uploader that checks whether the evaluated bundle matches the expected FHIR json data
- Refactors `FhirConverter` as a Spring component instead of a static utility class. This improves the testability of the converter by allowing easier mocking.
- Adds mockable wrappers for random UUID generation, Date generation, and handling timezones with various FHIR datetime objects

## Additional Information

- Some recent data discrepancies with dates might be caused by the HL7 FHIR package relying on the system's default time zone. Currently the csv data for the bulk uploader does not handle time zones so we'll need to address this.
- For example, if a row of data refers to 6/9/2023 at 15:00 and lacks time zone info, there is no way to determine whether that refers to 3pm eastern or 3pm pacific even if the machine running the bulk uploader is always using UTC. Unless we require a csv column that specifies time zone, we could potentially base it on other data such as testing facility location.

## Testing

- Review the code changes and verify the backend tests work correctly on your machine

### CODE REVIEW

**Comment by mpbrown** [comment]
I'll create an additional PR for this story that bases the uploaded data's time zone on the testing facility location

**Comment by mpbrown** [comment]
Deployed on Dev7 for testing

**Review by mehansen — COMMENTED** [review]
any thoughts on explicitly setting the time zone for the values in our fhir bundle so the behavior is predictable regardless of the system time zone?
e.g.
`provenance.getRecordedElement().setTimeZone(TimeZone.getTimeZone("utc"));`

**Comment by mehansen** [comment]
yes to supporting time zones for bulk upload! one thing I was thinking about is I think we were talking about the separate bulk upload experience having no concept of facility. so inferring time zone from facility would make that tricky if we ever decide to go back to implementing that. one other thing I thought about was making time zone a setting on the Manage org page

**Comment by mpbrown** [comment]
> any thoughts on explicitly setting the time zone for the values in our fhir bundle so the behavior is predictable regardless of the system time zone? e.g. `provenance.getRecordedElement().setTimeZone(TimeZone.getTimeZone("utc"));`

Yeah I think it would be good for us to always set it as UTC, then I can remove some of those ugly changes I made in the `FhirConverter` since in the tests we wouldn't have to use a mock to update those fields with `setTimeZoneZulu(true)`.

I'm currently working on handling time zones for the bulk uploader and here's some of what I have so far. This should preserve the time if it is included in `test_result_date` and hopefully be able to use the correct local zone offset from UTC. So with the following code, here is what the results would be:

Previously - "12/20/2021 14:00" in Central Time (UTC-5) gets converted to "2021-12-20T00:00:00Z", so it was losing the time value and using the system's default time zone so that for Central Time it ends up being 5 hours later at "12/20/2021 19:00"

Updated - "12/20/2021 14:00" in Central Time (UTC-5) gets converted to "2021-12-20T19:00:00Z" which is still in UTC by default but now is the correct instant of time from the uploaded data

But even with all of that, I think there would be some edge cases we'd need to figure out like if a lab already uses UTC for its data by default, in which case basing the time zone off their address might not be accurate. So then we either fall back to UTC or possibly a user time zone setting like you mentioned.

```
    var testResultDateTime = LocalDate.parse(row.getTestResultDate().getValue(), dateTimeFormatter).atStartOfDay();

    if (row.getTestResultDate().getValue().contains(":")) {
      testResultDateTime = LocalDateTime.parse(row.getTestResultDate().getValue(), dateTimeFormatter);
    }

    var zoneOffset = ZoneOffset.UTC;
    try {
      TimezoneInfo testResultTimezoneInfo = addressValidationService.getTimezoneByAddress(
              row.getTestingLabStreet().getValue(),
              row.getTestingLabStreet2().getValue(),
              row.getTestingLabCity().getValue(),
              row.getTestingLabState().getValue(),
              row.getTestingLabZipCode().getValue()
      );
      zoneOffset = ZoneOffset.ofHours(testResultTimezoneInfo.utcOffset);
    } catch (InvalidAddressException exception) {
      log.error("Unable to find timezone by testing lab address");
    }
    var dateTested = Date.from(testResultDateTime.toInstant(zoneOffset));

    var diagnosticReport =
        fhirConverter.convertToDiagnosticReport(
            mapTestResultStatusToFhirValue(row.getTestResultStatus().getValue()),
            testPerformedCode,
            testEventId,
            dateTested,
            dateGenerator.newDate());
```

**Review by BobanL — APPROVED** [review]
Changes look great! Thanks for cleaning these things up.

**Review by nathancrtr — APPROVED** [review]
Looks great! Tested in the deployed environment and we can see that FHIR submissions do not seem to be affected by any code changes here.

Screen Shot 2023-06-14 at 11 15 26 AM

**Pull request merged**
