### PR TITLE
remove the facility_device_specimen_type table

### PR DESCRIPTION
**Pull request by zdeveloper**
# BACKEND PULL REQUEST

## Related Issue

- part of #3352 

## Changes Proposed

- Remove unused facility_device_specimen_type table

## Testing

- How should reviewers verify this PR?

### CODE REVIEW

**Review by mehansen — COMMENTED** [review]
lgtm! except I have one question more for my liquibase knowledge: 
do we do rollbacks often? e.g. on lowers when we're deploying different versions of code? and if so should the rollback for this change also include repopulating the table with the data from the `populate-specimen-tables` changeset? I would guess someone on an older branch might need the values to be in the table

**Review by DanielSass — DISMISSED** [review]

**Comment by emmastephenson** [comment]
> lgtm! except I have one question more for my liquibase knowledge: do we do rollbacks often? e.g. on lowers when we're deploying different versions of code? and if so should the rollback for this change also include repopulating the table with the data from the `populate-specimen-tables` changeset? I would guess someone on an older branch might need the values to be in the table

@mehansen I was wondering this too, and I _think_ the only time it would be an issue is if this specific changeset was altered between code versions. Otherwise to my knowledge liquibase doesn't execute a rollback, it just would keep the newer database changes in the database (somewhat silently). Merging old code on top of these changes should be about the same as if we'd gone directly into the database and run a `DROP TABLE` command - liquibase would just ignore it. Liquibase mostly cares that the changeloglock for each changeset is the same, rather than that all changesets are contained within the file. (I think! @zdeveloper correct me if I'm wrong)

**Review by emmastephenson — APPROVED** [review]
LGTM 👍

**Comment by zdeveloper** [comment]
@mehansen @emmastephenson Thanks for the reviews, sorry for the very late response, We dont really do rollbacks often, but its tested in the automated CI. 
The liquibase [dropTable](https://docs.liquibase.com/change-types/drop-table.html) doesnt support auto rollback per [docs](https://docs.liquibase.com/change-types/drop-table.html#:~:text=PostgreSQL,No) thus the manual rollback is needed to pass the tests.
As far as  the values in the table, they are irrelevant, since the table is not used at all in the app ([ref](https://github.com/CDCgov/prime-simplereport/pull/4858)).

**Comment by zdeveloper** [comment]
Tested on dev3, and confirmed no real effect on metabase, will make another PR to remove Facility Device Specimen Type view from metabase.
image

**Review by emmastephenson — APPROVED** [review]
Database changes look good, as long as you create another ticket/PR for the metabase view I'm happy to have this in 👍

**Comment by zdeveloper** [comment]
thanks @emmastephenson, it will be addressed as part of the same ticket #3352

**Review by mehansen — APPROVED** [review]
>As far as the values in the table, they are irrelevant, since the table is not used at all in the app (https://github.com/CDCgov/prime-simplereport/pull/4858).

it's not used in the current app, but I was thinking more along the lines of if someone were on an outdated old branch without your code cleanup, could they hypothetically need those values? although in that case they can rebase off main easily enough. not blocking at all

appreciate the explanations @emmastephenson and @zdeveloper

**Pull request merged**
