### PR TITLE
Attach Application Insights objects to global Log Analytics Workspace

### LINKED ISSUE #6218: Classic Application Insights is deprecated and will be retired in February 2024
Our Application Insights resources are showing that they need to be migrated to the Workspace-based Application Insights paradigm, or face deprecation. We need to test this well in advance to ensure we don't run into any potentially-blocking issues.

This should be a relatively easy change in TF. Let's ensure this does not require a provider upgrade.

### PR DESCRIPTION
**Pull request by rin-skylight**
# DEVOPS PULL REQUEST

## Related Issue

- Resolves #6218.

## Changes Proposed

- Attach existing Insights object to global analytics workspace.

## Additional Information

- Log Analytics should offer additional features above what is currently offered. These are likely worth a further look for diagnostic/on-call purposes.

## Testing

- Test to ensure usual queries and other methods of diagnostics are still operational after the migration.
- This item has been deployed to `pentest`, and remains available accordingly for verification.

### Infrastructure
- [x] Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!

### Cloud
- [ ] Oncall has been notified if this change is going in after-hours
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by BobanL — DISMISSED** [review]
Changes look good to me, I can confirm the deprecation notice no longer appears on the deployed environment.

**Review by alismx — CHANGES_REQUESTED** [review]
The main file looks good, but what's up with the tf lock file? Should that be included in this PR?

**Comment by rin-skylight** [comment]
> The main file looks good, but what's up with the tf lock file? Should that be included in this PR?

That was totally my fault! 😓 Fixed!

**Review by alismx — APPROVED** [review]
Thanks for the lockfile fixup!

**Review by zdeveloper — APPROVED** [review]

**Review by DanielSass — APPROVED** [review]

**Pull request merged**
