### PR TITLE
Validate plid UUIDs in the front end

### PR DESCRIPTION
**Pull request by nullflux**
## Related Issue or Background Info

- Currently, if a user copies & pastes their patient link incorrectly such that the plid is an invalid UUID (too short, too long, etc), the back end throws a 500. These send PagerDuty alerts, but it's really a user error.

## Changes Proposed

- Validate that plid's are usable UUIDs in the front end before even presenting the form. If not, error immediately using the "Invalid link" message

## Additional Information

- This is just a proposal! 

## Screenshots / Demos

https://user-images.githubusercontent.com/18486822/137418636-b2914cf7-271b-48ef-8547-7c4414e03992.mp4

### UI
- [ ] Any changes to the UI/UX are approved by design (@vz3 please see the included video)
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
I'm all for it, thanks for pushing this up so quickly Adam!! Really appreciate it!

@vz3 can you look at this tomorrow morning? This should help decrease the number of pages we're getting, and also hopefully provide a better UX as they'll be alerted to the issue before entering their DOB.

**Comment by emmastephenson** [comment]
> Would it be possible to have the error appear before the TOS? And I'll defer to @Rebecca-LM on copy for the error.
> 
> My quick take would be something like:
> 
> > **Link not found**
> > This self-registration link is invalid. Please contact your test provider to get the correct link.
> 
> I think the treatment is fine here, as there's no other possible action for the user at this point.

My understanding is no, because of some CDC requirements around TOS, but I'll in turn defer to @nickclyde as he's more familiar with this flow.

**Comment by Rebecca-LM** [comment]
@emmastephenson I'll need a little more context here to weigh in on the copy. What does it mean that the link is invalid, what link are they referring to and when would this happen? I watched the video but wasn't sure.

**Comment by Rebecca-LM** [comment]
> @Rebecca-LM this is actually for test results, so would the following be okay?
> 
> **Page not found** This test result link is invalid. Please double check the URL or contact your test provider for the correct link.

Perfect!

**Comment by nickclyde** [comment]
Alright, made those changes, here is the new functionality (valid link shown first, then an invalid one)

https://user-images.githubusercontent.com/9121162/138007132-3fbf3a37-120c-42de-9bdf-80acb47dc0d8.mp4

**Pull request merged**
