### PR TITLE
Add button story to Storybook

### LINKED ISSUE #1382: Add button component to storybook
### Description
The new customized authentication flows use the full width version of the button. This use case of the component needs to be documented.

### Proposed solution 
Add the button component to StoryBook including the use of:
- the default primary button
- the full width primary button
- the default outline button 

### Additional context
Example uses

see [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/CDC-USDS?node-id=1669%3A1) for all uses

### PR DESCRIPTION
**Pull request by maya**
## Related Issue or Background Info

Resolves #1382 

## Changes Proposed

- Move button into its own folder with the story
- Create a top-level Components folder in Storybook

Screen Shot 2021-05-04 at 11 30 10 AM

### CODE REVIEW

**Comment by emmastephenson** [comment]
Is it possible to change the `Button/Button` naming convention? Or is that expected for Storybook components?

**Comment by maya** [comment]
I think it's probably good(?) that the component folder and file are the same name. It follows the convention I've seen other projects do. Did you have something else in mind?

**Comment by emmastephenson** [comment]
Not particularly, I just know I will probably attempt to import `Components/Button` one day and be confused when it doesn't work 😆 But if it's convention elsewhere then I'm happy to keep it, I just wanted to check.

**Review by emmastephenson — APPROVED** [review]

**Comment by maya** [comment]
Yeah, slightly harder to import but better overall for the project to have all files (component, tests, stories) for the component together 😄

**Pull request merged**
