### PR TITLE
extend the patient link life to 10 days and lockout attempts to 10

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- addresses #3247

## Changes Proposed

- extend the patient link life to 10 days 
- extend lockout attempts to 10

### Infrastructure
- [x] **Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!**

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [x] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [x] Any content changes (including new error messages) have been approved by content team

### Support
- [x] Any changes that might generate new support requests have been flagged to the support team
- [x] Any changes to support infrastructure have been demo'd to support team

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
Yes! 🎉  🎉

**Review by nickclyde — COMMENTED** [review]
Code looks good, but do we potentially need CDC security approval for this? I seem to recall getting approval last time we changed this. cc @jdorothy

**Comment by zdeveloper** [comment]
> Code looks good, but do we potentially need CDC security approval for this? I seem to recall getting approval last time we changed this. cc @jdorothy

we have the cdc approvals for both changes

**Review by nickclyde — APPROVED** [review]
:+1:

**Review by emmastephenson — DISMISSED** [review]

**Comment by rin-skylight** [comment]
I have a question...I can understand why we want to extend the value for SHELF_LIFE. Why is LOCKOUT_THRESHOLD being extended, as well? I'm not seeing that mentioned in the original ticket, and would very much like to understand the relation. 😸

**Comment by zdeveloper** [comment]
> I have a question...I can understand why we want to extend the value for SHELF_LIFE. Why is LOCKOUT_THRESHOLD being extended, as well? I'm not seeing that mentioned in the original ticket, and would very much like to understand the relation. smile_cat

good call out, per convo with @TimBest  we decided to extend both, I think the ticket is just missing that detail

**Comment by emmastephenson** [comment]
> I have a question...I can understand why we want to extend the value for SHELF_LIFE. Why is LOCKOUT_THRESHOLD being extended, as well? I'm not seeing that mentioned in the original ticket, and would very much like to understand the relation. 😸

We're finding that a _lot_ of users go over the lockout threshold, and not because they're maliciously trying to gain access to someone else's results - most of the time it's a parent not sure which child the result is for, or a case where the facility entered their DOB incorrectly, or they just keep mistyping their DOB. Increasing the lockout threshold gives users more grace to access their results without being too much of a security vulnerability, as 10 DOB attempts still won't be enough for random access attempts.

**Comment by rin-skylight** [comment]
That Demo Day presentation shed a lot of light on this, in addition to the great follow-up comments. Thanks for the answers, all!

**Review by rin-skylight — DISMISSED** [review]

**Review by rin-skylight — APPROVED** [review]

**Review by jdorothy — APPROVED** [review]

**Pull request merged**
