### PR TITLE
remove creating patient link when adding patient to queue

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- addresses #3121 

## Changes Proposed

- only create patient link when submitting a test

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by emmastephenson — APPROVED** [review]
LGTM, thanks for addressing this so quickly!

**Comment by nickclyde** [comment]
Can I get a little more context for this? The reason we create two links is so that the patient can fill out their pre-test questions on their own, and then receive a separate link for the test result. If you remove this, then patient links will only be for viewing test results - which is fine if we want to remove the ability for patients to do pre-test questions, I just wasn't sure if that was the goal here?

**Comment by emmastephenson** [comment]
> Can I get a little more context for this? The reason we create two links is so that the patient can fill out their pre-test questions on their own, and then receive a separate link for the test result. If you remove this, then patient links will only be for viewing test results - which is fine if we want to remove the ability for patients to do pre-test questions, I just wasn't sure if that was the goal here?

I think we may have already removed the ability to do pre-test questions on the frontend? I seem to remember Adam talking about that at a demo day back in August or so. I think it was dropped because not many people were using the feature

**Comment by nickclyde** [comment]
:exclamation: Somehow I completely missed that! Let me do a quick review of the code to confirm

**Comment by zdeveloper** [comment]
@emmastephenson @nickclyde I am fairly certain what Emma said is correct. It seems like prefilling the questionnaire was removed and this is just a leftover. @nickclyde would love for you to confirm since this predates me a bit.

**Comment by nickclyde** [comment]
Yup, this was done waaaaaaay back in July and somehow I just totally missed it!
https://github.com/CDCgov/prime-simplereport/pull/2102

**Review by nickclyde — APPROVED** [review]

**Pull request merged**
