### PR TITLE
Bob/add new features to app nav

### PR DESCRIPTION
**Pull request by fzhao99**
# FRONTEND PULL REQUEST
Had some UI regressions that slipped through the cracks on the last PR

## Related Issue
https://github.com/CDCgov/prime-simplereport/issues/3621
 
## Changes Proposed
Fixing drawer menu bugs
 
## Screenshots / Demos
Smoke tested in dev with screenshots below.

Screen Shot 2022-04-26 at 12 51 20 PM
Screen Shot 2022-04-26 at 12 51 14 PM

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [x] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### CODE REVIEW

**Review by kenieh — APPROVED** [review]
LGTM, ty bob for the quick fix!

**Comment by mehansen** [comment]
What were the bugs that this is fixing?

**Comment by fzhao99** [comment]
The mobile view used to look like this. This PR swaps the icons on the drawer with the actual words

Before:
image

After:
image

**Review by mehansen — APPROVED** [review]
Thanks, that makes sense. Looks good!

**Pull request merged**
