### PR TITLE
Deconflict `<header>` across the app

### LINKED ISSUE #3974: USAgov banner is styled as a header
## Area or Component
Likely application-wide, but seen on the patient experience

## Quick Summary
The banner at the top of the site ("An official website of the United States government. Here's how you know") is stylized as a header, but we normally have other headers in main content of the application.

## Accessibility Violation
Two:
* Ensures the document has at most one banner landmark (https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=AxeChrome)
* Landmarks should have a unique role or role/label/title (i.e. accessible name) combination (https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=AxeChrome)

## Action Requested
If possible: remove the role=`banner` from the USA-gov banner at the top of the site.
Also change it away from a `<header>` element, since we nearly always have our own `<header>` element.

## Source Code (optional)
https://github.com/CDCgov/prime-simplereport/blob/c3e6b2dc330021e425e01657eaee613c51f9e11c/frontend/src/app/commonComponents/USAGovBanner.tsx#L80-L80

## Original Deque Issue:
landmark-no-duplicate-banner | Ensures the document has at most one banner landmark | Two header landmarks on the page; one for main content and one for the "an official website of the US govt" | Document should not have more than one banner landmark | https://dequeuniversity.com/rules/axe/4.4/landmark-no-duplicate-banner?application=AxeChrome | moderate | No | No |   | [".usa-banner__header"] | Fix any of the following:  Document has more than one banner landmark | <header class="usa-banner__header"> | cat.semantics,best-practice | rnv7@cdc.gov | Patient Self Reg - Terms of Service | https://stg.simplereport.gov/app/register/9C7BB |   | 2022-07-13T20:53:04.535Z
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
landmark-unique | Landmarks should have a unique role or role/label/title (i.e. accessible name) combination | Same as above | Ensures landmarks are unique | https://dequeuniversity.com/rules/axe/4.4/landmark-unique?application=AxeChrome | moderate | No | No |   | [".usa-banner__header"] | Fix any of the following:  The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable | <header class="usa-banner__header"> | cat.semantics,best-practice | rnv7@cdc.gov | Patient Self Reg - Terms of Service | https://stg.simplereport.gov/app/register/9C7BB |   | 2022-07-13T20:53:04.544Z

### LINKED ISSUE #3982: Logo in patient experience header is mislabelled
## Area or Component
Patient Experience

## Quick Summary
There's a SimpleReport logo in the patient experience labelled with the string literal `process.env.REACT_APP_TITLE`.

## Accessibility Violation
The short text alternative for the complex image is not appropriate or meaningful.
https://cdc-devtools.dequecloud.com/rule-help/en/alt-text-short-text-not-meaningful

## Action Requested
Update the short text for the logo to render properly (use `process.env.REACT_APP_TITLE` as the variable name, not the literal name)

## Source Code (optional)
https://github.com/CDCgov/prime-simplereport/blob/c3e6b2dc330021e425e01657eaee613c51f9e11c/frontend/src/patientApp/PatientHeader.tsx#L38-L38

## Original Deque Issue
alt-text-short-text-not-meaningful | The short text alternative for the complex image is not appropriate or meaningful. | Alt text for logo is not useful (PROCESS-REACT-ENV) | Short text alternative is not appropriate | https://cdc-devtools.dequecloud.com/rule-help/en/alt-text-short-text-not-meaningful | serious | Yes | No | Images | ["body > div#root:nth-of-type(1) > div.App:nth-of-type(1) > div#main-wrapper:nth-of-type(1) > header.header.border-bottom.border-base-lighter:nth-of-type(1) > div.display-flex.flex-align-center.maxw-tablet.grid-container.patient-header:nth-of-type(1) > div.padding-y-1:nth-of-type(1) > div#basic-logo.margin-bottom-0:nth-of-type(1) > div.display-flex.flex-align-center:nth-of-type(1) > img.width-4:nth-of-type(1)"] | The short text alternative for the complex image is not appropriate or meaningful. | {process.env.REACT_APP_TITLE} | wcag2a,wcag111c | rnv7@cdc.gov | Patient Results - DOB | https://dev.simplereport.gov/app/pxp/birth-date-confirmation?plid=2d388b8a-ce92-43e9-bc35-75306ef6df08 |   | 2022-07-14T18:59:32.829Z
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### LINKED ISSUE #4084: Result page is missing a main heading
## Area or Component
Result page

## Quick Summary
There's no H1 element on the results page. 

## Accessibility Violation
Page should contain a level-one heading: https://dequeuniversity.com/rules/axe/4.4/page-has-heading-one?application=AxeChrome

## Action Requested
Add a level-one heading to the page (we can probably use "Results" in the navigation bar for this - that's the equivalent experience for sighted users)

## Original Deque Issue
https://docs.google.com/spreadsheets/d/1b6xjubAN5Uw11DV4_B5zvSu7HeDI6Z-DpV4DMcToqAY/edit#gid=1978534823&range=16:16

### PR DESCRIPTION
**Pull request by emmastephenson**
# FRONTEND PULL REQUEST

- Fixes #3974 

## Changes Proposed

There should only be a single `<header>` landmark on any page. SimpleReport had `<header>` elements both for the USAGov banner, and for the navigation bar. 

This change deconflicts these `<header>` elements by putting both of them inside the `Page` component.

## Additional Information

- The usual caveats of "I am a backend engineer attempting to write frontend code, please check this throughly"
- Chromatic definitely should be checked here

## The Diff
Github has not done a great job with diff-checking this one...the actual changes to the `App`, `PatientExperience`, and `PatientRegistration` files are from

```
<Page>
{ child components, including header }
< /Page>
```

to
```
< Page 
 header = {header}
children = {children}
/>
```
none of the actual `children` content changed at all.

### Design
- [ ] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [ ] Any content changes have been approved by content team

### Support
- [ ] Any changes that might generate new support requests have been flagged to the support team
- [ ] Any changes to support infrastructure have been demo'd to support team

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### Documentation
- [ ] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Review by emyl3 — CHANGES_REQUESTED** [review]
I am only seeing one `<header>` element across SR and in the PXP app.

I did notice that this PR is suppose to "Fixes https://github.com/CDCgov/prime-simplereport/issues/4084". However, I am not seeing a `h1` for the results page. 🤔 Let me know if I am missing something!

**Comment by fzhao99** [comment]
Can confirm Elisa's point about the h1 not showing up in the results page.

Another complicating factor is that our Touchpoints implementation seems to have separate landmark elements as seen below
Screen Shot 2022-08-01 at 1 58 35 PM

Don't think this needs to be a blocking issue for this PR (which otherwise looks good!) since we have another ticket for it [here](https://app.zenhub.com/workspaces/simplereport-accessibility-61153c23e7546f0010407728/issues/cdcgov/prime-simplereport/4002) but flagging it so we can fix it once we get around to fixing our Touchpoints-related issues.

**Comment by emmastephenson** [comment]
> Can confirm Elisa's point about the h1 not showing up in the results page.
> 
> Another complicating factor is that our Touchpoints implementation seems to have separate landmark elements as seen below Screen Shot 2022-08-01 at 1 58 35 PM
> 
> Don't think this needs to be a blocking issue for this PR (which otherwise looks good!) since we have another ticket for it [here](https://app.zenhub.com/workspaces/simplereport-accessibility-61153c23e7546f0010407728/issues/cdcgov/prime-simplereport/4002) but flagging it so we can fix it once we get around to fixing our Touchpoints-related issues.

Yeah, I looked briefly into including Touchpoints on the `<main>` element but somehow putting it under `main` disables the clickability so I figured we would address it in a separate ticket. Thanks for highlighting that though!

**Comment by emmastephenson** [comment]
> I am only seeing one `<header>` element across SR and in the PXP app.
> 
> I did notice that this PR is suppose to "Fixes #4084". However, I am not seeing a `h1` for the results page. 🤔 Let me know if I am missing something!

@emyl3 and @fzhao99 good catch - I suspect I was trying to link #4074 instead, except that is _also_ not resolved with this ticket! Let's blame Friday afternoon brain 😄 Taking that one off.

**Review by fzhao99 — APPROVED** [review]

**Review by emyl3 — APPROVED** [review]
Thanks Emma! LGTM! 😹

**Pull request merged**
