### PR TITLE
Update Dockerfiles to not run as the root user

### LINKED ISSUE #3372: Update Dockerfiles to not run as the root user
### Description
Our Dockerfiles are all configured to run as the root superuser. They can likely run with fewer privileges.

### Proposed solution 
Amend the following Dockerfiles to use a user with more limited privileges:
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/backend/Dockerfile.db-rollback#L1-L1
(this one could potentially be deleted as I don't think anyone is using SchemaSpy)
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/backend/Dockerfile.schemaspy#L1-L1 
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/backend/Dockerfile.prod#L1-L1
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/backend/Dockerfile#L1-L1
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/frontend/Dockerfile.dev#L7-L8
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/frontend/cypress/Dockerfile.e2e#L16-L16
https://github.com/CDCgov/prime-simplereport/blob/7f0c58ec6b376d5f26763e7de1dca1745f3752de/frontend/cypress/support/nginx/Dockerfile.nginx.compose#L3-L3

### Additional context
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1644425709462849
See Emma for Fortify scan.

### PR DESCRIPTION
**Pull request by nickclyde**
## Related Issue or Background Info

- Resolves #3372

## Changes Proposed

- Add a step to all Dockerfiles to add an `appuser` group and user and make the `CMD` run as that user
- Remove schemaspy since no one uses it

### Infrastructure
- [x] **Consult the results of the `terraform-plan` job inside the "Terraform Checks" workflow run for this PR. Confirm that there are no unexpected changes!**

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [x] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [x] Any content changes (including new error messages) have been approved by content team

### Support
- [x] Any changes that might generate new support requests have been flagged to the support team
- [x] Any changes to support infrastructure have been demo'd to support team

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Comment by rin-skylight** [comment]
Can we roll this out to one of our Azure environments to verify that everything seems to work as expected? It's Docker, so it should work everywhere in theory...but I have seen weirdness in practice.

**Comment by nickclyde** [comment]
Just tried to deploy to dev, turns out `groupadd` is not available in alpine because... it's alpine 😅 
https://github.com/CDCgov/prime-simplereport/runs/5149466753?check_suite_focus=true#step:5:573

Will find an alternative or install it in the image

**Comment by nickclyde** [comment]
Screen Shot 2022-02-10 at 3 58 22 PM
🤦

**Comment by nickclyde** [comment]
Deployed to dev, smoke tests look good!

**Review by rin-skylight — APPROVED** [review]
Thanks for the extra verification steps on this, along with the great catch on the Alpine weirdness. Approved!

**Pull request merged**
