### PR TITLE
Make Analytics home page for org admins; rename Admin to SupportAdmin

### LINKED ISSUE #2479: v0: Analytics page is homepage for admin users
### Description
We're building out a new analytics dashboard, and want it to be easily discoverable for admin users.

### Proposed solution 

- Make analytics dash the homepage for SR admins
- When clicking on logo, redirect to analytics page
- Add analytics tab in top nav (Dashboard / Conduct Tests / Results / People)

### Additional context
This page should only be visible to admins and super admin users.
Top nav needs a pass from content before submission.

### PR DESCRIPTION
**Pull request by nickclyde**
## Related Issue or Background Info

- Resolves #2479 

## Changes Proposed

- Changes the routing logic so that homepage for super admins / support admins is `/admin`, for org admins is `/dashboard`, and everyone else is `/queue`
- `/dashboard` now routes to the new Analytics component
- Added a nav link to the tob bar  "Dashboard" which goes to `Analytics`
- Renamed `AdminRoutes` and `Admin` components to `SupportAdminRoutes` and `SupportAdmin` for clarity
- Fixed `App.test.tsx` to expect `Analytics` to be the homepage

## Additional Information

- The original issue called out for a content review of the nav item, so tagging @Rebecca-LM 

## Screenshots / Demos

image

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [ ] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Comment by emmastephenson** [comment]
@vz3 should be the final decision-maker on this one, but it was my understanding that the analytics would actually live as a top-level nav component, such that the top nav was `Dashboard`, `Conduct Tests`, `Results`, `People` (or whatever we end up deciding to call the analytics tab.) I'm sorry for any confusion on this, that's my bad for not writing the ticket clearly enough!

**Comment by Rebecca-LM** [comment]
> @vz3 should be the final decision-maker on this one, but it was my understanding that the analytics would actually live as a top-level nav component, such that the top nav was `Dashboard`, `Conduct Tests`, `Results`, `People` (or whatever we end up deciding to call the analytics tab.) I'm sorry for any confusion on this, that's my bad for not writing the ticket clearly enough!

@nickclyde @emmastephenson that was my understanding too as far as top level nav. I think we're ok with "Dashboard" since the users we interviewed all were familiar with that term.

@nickclyde top dropdown header that says "Facility" should say "Testing facility". Under Dis Organization it says "All roles" but @vz3 can you weigh in if this should be "All groups" or "All people tested"? In this context I think "All people tested" makes more sense, since groups could be a lot of things like all testing facilities, etc.

**Comment by nickclyde** [comment]
Woops, sorry for the misunderstanding, I'll go ahead and make those changes!

**Review by bmaden-usds — APPROVED** [review]
Code changes so far LGTM.

One, thing I notice now that I didn't before (that I don't think is directly related to this PR) is that the alignment of the numbers is not the same all the way across.  The "Positive tests" number is lower than the others.  If it makes more sense, it is fine to just add a ticket to fix that later.

**Comment by nickclyde** [comment]
Dang, adding another link to the top nav means there's not much space for the facility select:
image

Thoughts @emmastephenson @Rebecca-LM @vz3? I could try shrinking the font size of the nav items maybe

**Comment by emmastephenson** [comment]
> Dang, adding another link to the top nav means there's not much space for the facility select: image
> 
> Thoughts @emmastephenson @Rebecca-LM @vz3? I could try shrinking the font size of the nav items maybe

Oh dang. I think we should be ok to shrink the font size a little, and maybe also shrink the favicons for settings and user logout?

**Comment by nickclyde** [comment]
How does this look?

image

**Comment by Rebecca-LM** [comment]
@nickclyde smaller font LGTM. Just noticed on the last card that it says Positives/Total tests but there is an extra space there. I also think that maybe a slash isn't the best way to represent this, since it isn't necessarily clear this means divided by, vs. just a slash between similar words. Not sure if a division symbol makes sense here, maybe @vz3 has a better design solution.

**Review by emmastephenson — APPROVED** [review]

**Comment by nickclyde** [comment]
@Rebecca-LM how does it look with the division symbol?

image

**Comment by Rebecca-LM** [comment]
@nickclyde tbh I'm on the fence about it, but just since I'm not sure how users would react! can we make it a little bigger and lowercase the t in total?

**Comment by nickclyde** [comment]
@Rebecca-LM how's this?

image

**Comment by Rebecca-LM** [comment]
@nickclyde LGTM. One last nit is under central schools the all people tested and date range blend together for me. Is there a way to distinguish each from each other? Maybe a little padding above and below the date range?

**Pull request merged**
