### PR TITLE
Printing

### LINKED ISSUE #426: Print Lab Results
As a patient receiving a COVID test, I want to get a lab result to take with me, so that I can share it with others like my doctor, other employers, or for travel.

As a test administrator, I want to have medical record documentation of the tests I perform, so that I can add them to patients medical records, show proof when I am audited, and so that I can bill insurance for the tests I perform.

**Design TODO**
- [X] Decide what the test result should look like when we generate it on desktop/as a PDF
- [x] Should it open in a lightbox, print preview, new tab, etc. How does the user get to actually printing it?- Use internal print to PDF feature

**Engineering TODO**
- [ ] Add button to results and option to print when clicked
- [ ] Add generated PDF of lab results to print

**Additional Context**
What we're hearing from testing sites is they will continue to keep paper records until they can save their own copy of lab results.

How to get to the print button
Screen Shot 2020-12-23 at 7 22 16 AM

Example Antigen Lab Result (from another lab)
[Example Antigen Lab Result.pdf](https://github.com/CDCgov/prime-simplereport/files/5735926/Example.Antigen.Lab.Result.pdf)

SimpleReport Lab Result Design (Negative Result)
[Lab Result.pdf](https://github.com/CDCgov/prime-simplereport/files/5935466/Lab.Result.pdf)
Lab Result

SimpleReport Lab Result Design (Positive Result)

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

Fixes #426 
(Epic in #535?)

## Changes Proposed

Adds a popup menu in the test results section, at the moment it will only have the "print results" choice.
Screen Shot 2021-01-14 at 2 39 08 PM

When the user selects this choice it will show a preview of the printed report in a modal dialog:
Screen Shot 2021-01-14 at 2 39 44 PM

If they click Print it takes them to the system/browser print dialog which allows them to save to PDF or print directly to a printer:
Screen Shot 2021-01-14 at 2 40 25 PM

Here is the resulting PDF:
[test-result-sample.pdf](https://github.com/CDCgov/prime-simplereport/files/5816765/test-result-sample.pdf)

## Questions (mostly for @hmyers-cms and @aliciabeckett-gov)

* **UX:** We could conceivably skip our own dialog (the first one) and take them directly to the system one, but that would take some additional work. We have to render what we need _somewhere_ in order for the system print dialog to print it, but we might be able to do it off screen. It would take a bit more research to figure that out.

* **Layout issues:** The two-column format for the Patient and Facility causes problems because addresses in particular are often long. Do we need them to be labeled? Things like the names, addresses, and phone numbers are pretty easy to identify without labels and the sample we got in #426 named "Example Antigen Lab Result.pdf" does something similar.

* **Missing information:** I don't see a place to obtain the Specimen ID, Test Name, or Collection Date. We do have a time for the Test Date if you want to print it. The Test Result is just not showing in this shot but it's there. I need some real text for the Next Steps section or we can remove it.

### CODE REVIEW

**Comment by hmyers-cms** [comment]
I'm fine with having our own modal pop up for now if it makes things way easier. Eventually we will want to build bulk printing, and this pattern won't really work anymore, but we can address the issue then.

For the layout issues, it looks like it is fine everywhere except the facility address. In theory we may not need those labels but I think they help keep the layout visually consistent and makes it more clear that this is the facility address and not the patient or ordering providers address.

You should be able to take the next steps text from my mockup. Copy/pasted here so you don't need to type it all up from the image:

Antigen tests can return inaccurate or false results and follow up testing may be needed. Continue social distancing and wearing a mask. Contact your healthcare provider to determine if additional testing is needed especially if you experience any of these COVID-19 symptoms.
     •  Fever or chills
     •  Cough
     •  Shortness of breath or difficulty breathing
     •  Fatigue
     •  Muscle or body aches
     •  Headache
     •  New loss of taste or smell
     •  Sore throat
     •  Congestion or runny nose
     •  Nausea or vomiting
     •  Diarrhea

**Comment by hmyers-cms** [comment]
A couple styling notes:
- The ellipsis icon is a bit small, any chance we can bump that up a bit?
- From your screenshot w/ the action menu open, I actually can't tell whether you're about to print the negative or the positive result. The design has the entire row highlighted to make it more obvious which one you've selected the action on. If that's gonna be really tough to implement we can chat about simpler alternatives for the short term and do the full row highlighting once we move to bulk actions

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms would it help to stack the boxes vertically to get around the address issue? Otherwise it all looks good to me!

**Comment by dmethvin-gov** [comment]
Thanks for the input, @hmyers-cms and @aliciabeckett-gov ! Sorry about these long replies, I just want to make sure I bring things to your attention and address any concerns.

I think the remaining high-priority question is whether the Specimen ID, Test Name, and Collection Date are important enough that we need to address them before releasing this, and whether to remove them if we don't. All we know really is the date the test was reported, which can be back dated. I can't find a place where we describe the test name or specimen.

I've included a shot below of something like what I was proposing in terms of removing the labels. It gives us plenty of room for the address and facility names, which would also be problematic for "Arroyo Hills Convalescent Care". Your call on the formatting, I can keep it as is, just wanted to show an idea of what I meant.

Screen Shot 2021-01-15 at 2 23 41 PM

The new Next Steps is there now. I made them two columns because we were getting close to the end of the page and I assume we want to keep this to a single page. To keep it to a page we'd have to buy back space with tighter spacing or smaller font size. I haven't actually seen this printed (I don't have a printer) so I'm not sure what this looks like on paper.

Also, is Next Steps dependent on test result? It seems like the text might be different in those cases.

Screen Shot 2021-01-15 at 4 55 34 PM

Good call on making the menu dots bigger, they were smaller than 32px which is the minimum recommended hit target. I've enlarged them but hopefully not comically. I added the hover styles as well. I didn't want to pull in all the work for the test results changes here so I hadn't tried to address all the work to get in sync with the engineering prototype.

Screen Shot 2021-01-15 at 4 24 37 PM

**Comment by hmyers-cms** [comment]
I can make peace with this layout if it avoids engineering headaches. Can we bold the person and facility name, and also bold the labels for sex, DOB, ordering provider, NPI, and CLIA?

The style updates on the actions menu look great!

The other questions I'll leave to Alicia to answer.

**Comment by aliciabeckett-gov** [comment]
Specimen ID, Test Name, and Collection Date:

Specimen ID- we should have this but could ship without it
Test Name- we definitely need this
Collection Date- we don't need this since we don't know it, we only know result date. It should be the same as the test date because it is a rapid test, and if it's not we don't know that. So let's not include Collection date.

**Comment by aliciabeckett-gov** [comment]
Also, I think we do want different guidance if someone tests positive. Let me follow up with Alex at CDC to see if we can get some guidance.

**Comment by dmethvin-gov** [comment]
Closing because this branch is stale and the ticket is blocked on stakeholder feedback. Most of this code has been merged but not visible in the UI.

**Pull request closed without merging**
