### PR TITLE
Save timer state to localStorage

### LINKED ISSUE #410: Timers need to persist
As a user, I want to know that I will not lose my timer even if I refresh the page, the app logs me out, or even my computer crashes.

Current Behavior:
-Start a timer
-Refresh Browser/Restart Browser/Log out and Log in
Result: Timer resets
Expected behavior: Timer does not reset

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

Fixes #410

## Changes Proposed

- Save timer state to `localStorage` when timers are added or removed
- Restore running timers on load
  - But remove timers finished for more than (N=60) minutes
- Rename some variables for clarity

## Additional Information

Be aware that due to browser security restrictions the sounds do not play on load. The user must interact with the page (e.g., click or type) before the sound API runs. So if someone exits the app and then restarts after a timer has expired, the sound will not play The timer will show the correct time though.

Keeping this in a draft state because at the moment I can't play audio at all in the app. Even when reverting to `main` it doesn't work. I thought it might just be the browser but restarting didn't help. Can someone else can try this (or just `main`) and see if sound is working in the app for them?

```
TestTimer.tsx:51 Uncaught (in promise) DOMException: The element has no supported sources.
index.js:1 Uncaught Error: The error you provided does not contain a stack trace.
    at S (index.js:1)
    at V (index.js:1)
    at index.js:1
    at index.js:1
    at a (index.js:1)
TestTimer.tsx:51 Uncaught (in promise) DOMException: The element has no supported sources.
```

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
Update: I can't even get the old code to play sound on `dev.simplereport.org`, can anyone verify?

**Comment by dmethvin-gov** [comment]
Recapping the behavior and implementation:
* Timers are kept in `localStorage` so it's a per-workstation thing. Storing on the server raises a lot of issues we probably don't want to deal with right now.
* Browsers have a restriction that a window can't play sounds until the user interacts with the window. (There are some escape hatches but they require the user to reconfigure the browser or computer.) If the user reloads the app but does not at least click somewhere in the window, they will see the timers running but the app won't be able to play a sound. Once we implement #404 a user will need to click almost immediately so this may not be a problem.
* Really old timers (currently old=60 minutes plus the timer length, so 75 minutes from start) are removed and reset when the app reloads. This is to catch edge cases where tests are no longer in the queue and therefore the timer would never be visible and never removed.

**Comment by TomNUSDS** [comment]
This feature will make timers more reliable and therefore more used.

One thing to consider is that this approach of decrementing a "time remaining" variable is that there tends to be drift over time. It's much more reliable to have an "end time" that's update when the timer starts and is compared to the current time on a timer.

I only know this because I've implemented something similar in the past and the drift was significant when the page was put into a background tab. The timers seemed to be starved of cycles and would fall behind. Granted, those times were on the scale of hours, but it added up.

**Comment by dmethvin-gov** [comment]
> One thing to consider is that this approach of decrementing a "time remaining" variable is that there tends to be drift over time. 

The `timer.alarmAt` keeps the end time, the countdown is only calculated for the convenience of the display.

**Comment by TomNUSDS** [comment]
Great! I didn't realize that about `timer.alarmAt` LGTM!

**Review by timothybest-usds — APPROVED** [review]

**Pull request merged**
