### PR TITLE
Refactor SASS files so modules can use variables

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

Move SASS variable and configuration settings into a file separate from the main `App.scss` file. This lets components import config values such as colors in their own `.scss` file. I did just one simple change to show how it is used, the settings in the other files can be changed in later commits or refactors so we can get this merged soon.

This change doesn't allow the use of mixins or macros, I hadn't been using them in the previous project where I did this. I tried including a few other files but was only rewarded with errors about finding files because I think the search path is confused. If either of you know the magic to that we could give it a try. 

This change doesn't affect the use of utility _classes_, so we can continue to use those where appropriate.

### CODE REVIEW

**Comment by maya** [comment]
I think it's a good start. I found a utilities package `packages/_uswds-utilities.scss`, but when I tried to import it, I got errors that it couldn't find variables. I'm hoping this package would let us use the utility functions + tokens. So will need to keep digging or find some magic ✨

**Comment by dmethvin-gov** [comment]
Yeah i don't know what it takes to get SASS to find the files. It seems like SASS is moving from the global `@include` model to a module-based `@use` model that would be helpful here, but at that point it would probably be easier to avoid SASS altogether and move to CSS variables, assuming that IE11 is not a concern.

**Comment by maya** [comment]
I opened #860 just to test something out. I have a note about a potential solution in case anyone wants to take look.

**Comment by dmethvin-gov** [comment]
I think this is ready to merge as-is. It can be enhanced in several ways but it would be good to get this part done first.

**Review by nickscialli-usds — APPROVED** [review]

**Comment by ClydeDroid** [comment]
Friendly reminder to merge `main` to this PR, as new lint checks/configs were added by #885 and #995!

**Pull request merged**
