### PR TITLE
Update form labels in Other section of Person form

### LINKED ISSUE #1255: Add helper text to congregate care question
- [ ] Add helper text to congregate care (see screenshot) - in patient app and core app
- [ ] Change "Healthcare" from uppercase to lowercase (Instead of "Work in Healthcare?", it should read "Work in healthcare?")

### PR DESCRIPTION
**Pull request by maya**
## Related Issue or Background Info

Fixes #1255 

## Additional Information

- Adds HintText prop to YesNoRadioGroup.tsx

## Screenshots / Demos
Screen Shot 2021-04-14 at 2 19 12 PM

### CODE REVIEW

**Comment by maya** [comment]
@katiealoisi I saw a couple of grammar and style issues in the original screenshot which I've fixed here, cc @Rebecca-LM

**Comment by maya** [comment]
We should probably avoid using slashes but I wasn't sure what to change "Resident in congregate care/living setting?" to. "Resident in congregate care or living setting?"? @Rebecca-LM

**Comment by Rebecca-LM** [comment]
@maya I made other suggestions to this entire flow in Figma. Here it should be "Are you a resident in a congregate living setting?" I don't think we need to delineate care vs. other living setting here.

**Comment by maya** [comment]
@Rebecca-LM are these the correct copy changes?
 Screen Shot 2021-04-14 at 3 08 05 PM

**Comment by maya** [comment]
For now, I just minimally updated the first label to "Resident in a congregate care setting?" until I hear back on what's the final copy to use for this PR.

**Review by nullflux — APPROVED** [review]
Looks good on the code front!

Pre-emptive ✅, pending final copy review

**Comment by katiealoisi** [comment]
I'm good with @Rebecca-LM's suggestion to use: "Are you a resident in a congregate living setting?" I also looked through your other comments in Figma and agree we should change the explainer text to read: "For example: nursing home, group home, prison or jail, military"

**Comment by Rebecca-LM** [comment]
@maya I think it may be "resident of" (vs. at) but tried to confirm online and not able to. The rest looks good.

**Comment by katiealoisi** [comment]
Also, I just checked the CDC website and they use "healthcare worker" versus "health care worker" (at least recently for COVID comms). Can you update the form label for the second question to: "Are you a healthcare worker?"

**Comment by Rebecca-LM** [comment]
> Also, I just checked the CDC website and they use "healthcare worker" versus "health care worker" (at least recently for COVID comms). Can you update the form label for the second question to: "Are you a healthcare worker?"

@katiealoisi AP style [says two words](https://twitter.com/apstylebook/status/1222609078897250306?lang=en). For an HHS website I worked on we did two words. Fine with either, but whatever we decide I'll put in the style guide. Lmk!

**Comment by katiealoisi** [comment]
> > Also, I just checked the CDC website and they use "healthcare worker" versus "health care worker" (at least recently for COVID comms). Can you update the form label for the second question to: "Are you a healthcare worker?"
> 
> @katiealoisi AP style [says two words](https://twitter.com/apstylebook/status/1222609078897250306?lang=en). For an HHS website I worked on we did two words. Fine with either, but whatever we decide I'll put in the style guide. Lmk!

Hmmmm. Given that I've seen both "healthcare" and "health care" on CDC sites, and that AP and HHS officially support health care as two words, let's go with "health care" ("Are you a health care worker?")

**Comment by maya** [comment]
Copy updates made in eeb9d13

Screen Shot 2021-04-15 at 10 08 20 AM

**Pull request merged**
