### PR TITLE
Correct language on "print test result" view for negative test case

### PR DESCRIPTION
**Pull request by nathancrtr**
## Related Issue or Background Info

image (1)
* The above screenshot accurately captures the issue but (at least I'm pretty sure - @LGFranklin correct me if I'm wrong) prescribes the text for the _positive_ test case, which isn't what we want here

## Changes Proposed
- No longer refer to "antigen" in the test notes for negative results, as this is inaccurate and confusing

## Additional Information
* I treated the [Patient test result content v4](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit) as canonical when updating the text
    * @Rebecca-LM if this document is out-of-date in any way please let me know!

#### English
Screen Shot 2021-09-16 at 12 50 18 PM

#### Spanish
Screen Shot 2021-09-16 at 12 54 02 PM

#### English
Screen Shot 2021-09-16 at 1 01 00 PM

#### Spanish
Screen Shot 2021-09-16 at 12 53 42 PM

## Checklist for Author and Reviewer
- [ ] @Rebecca-LM is the updated copy correct?
- [ ] @LGFranklin is this the correct outcome?

### UI
- [x] Any changes to the UI/UX are approved by design 
- [x] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [x] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [x] Database changes are submitted as a separate PR
  - [x] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [x] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [x] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
  - [x] Each new changeset has a corresponding [tag](https://docs.liquibase.com/change-types/community/tag-database.html)
- [x] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [x] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [x] Any dependencies introduced have been vetted and discussed

## Cloud
- [x] DevOps team has been notified if PR requires ops support
- [x] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by nullflux — APPROVED** [review]
LGTM! Let's get a ✅  from Leslie or Rebecca before shipping

**Comment by LGFranklin** [comment]
Looks good to me; need to make this for negative AND inconclusive.

**Comment by nathancrtr** [comment]
> Looks good to me; need to make this for negative AND inconclusive.

@LGFranklin yes indeed, the negative and inconclusive test cases produce identical text in the "print" view:

Screen Shot 2021-09-16 at 1 28 32 PM

**Comment by Rebecca-LM** [comment]
@nullflux do we need updated language for the inconclusive too? Didn't see it here.

One thing to grab from the versions Nathan and I created is the written out URLs that are needed for print results. We have one for English and the Spanish URL for Spanish. They were formatted in the correct way (without https:// and some other stuff). Lmk if you have questions on this.

**Comment by nathancrtr** [comment]
> @nullflux do we need updated language for the inconclusive too? Didn't see it here.
The original requirement was that the negative and inconclusive cases should have the same test notes for the "print" view, so that is taken care of here:

Screen Shot 2021-09-16 at 1 28 32 PM

> One thing to grab from the versions Nathan and I created is the written out URLs that are needed for print results. We have one for English and the Spanish URL for Spanish. They were formatted in the correct way (without https:// and some other stuff)

@Rebecca-LM that's a good call - until this PR, that link to the CDC website didn't exist on the negative/inconclusive cases at all. The positive case has had links for a while and they are formatted correctly on the "print" view:

Screen Shot 2021-09-16 at 2 03 49 PM

I can fix that for negative/inconclusive here real quick.

**Pull request merged**
