### PR TITLE
filter out non-covid results from bulk uploader csv

### PR DESCRIPTION
**Pull request by zdeveloper**
# BACKEND PULL REQUEST

## Related Issue

- #6080

## Changes Proposed

- Filter out non-covid results from the bulk uploader RS CSV pipeline
- If flu only file is uploaded, only FHIR will be submitted, and the UI will show the FHIR report ID

## Testing

- How should reviewers verify this PR? dev6

image

### CODE REVIEW

**Review by DanielSass — COMMENTED** [review]
On first pass everything looks good to me.  Will pull down to test locally before approving. 👍

**Comment by mpbrown** [comment]
Hmm I'm getting this error on `dev6` when I attempt to upload `test-results-upload-valid-with-flu-results.csv`. I tried updating the specimen types and triggering the device sync on `dev6` but it still gave the error. Is that considered a valid file with the flu specimen type "FLUBV RNA Resp Ql NAA+probe"?

image

**Comment by DanielSass** [comment]
> Hmm I'm getting this error on `dev6` when I attempt to upload `test-results-upload-valid-with-flu-results.csv`. I tried updating the specimen types and triggering the device sync on `dev6` but it still gave the error. Is that considered a valid file with the flu specimen type "FLUBV RNA Resp Ql NAA+probe"?
> 
> image

Flu only / non covid devices aren't going to be brought in with the device sync.  Double check the list of flu loincs (hard-coded) to make sure the device is valid?

**Comment by zdeveloper** [comment]
@mpbrown thanks for the catch, the `test-results-upload-valid-with-flu-results.csv` was valid for the test since we're mocking things, but not valid in real life, updated it to be valid for both.

**Review by DanielSass — APPROVED** [review]

**Pull request merged**
