### PR TITLE
Upgrade to node version 20 for Azure Function App

### LINKED ISSUE #7561: Upgrade Azure function app to node 20
Upgrade the Azure function app to use node 20 part of #6844 effort

Draft PR up to make this change #7559 but blocked by #7560

### PR DESCRIPTION
**Pull request by emyl3**
# DEVOPS PULL REQUEST

## Related Issue

- Resolves #7561 

## Changes Proposed

- Detailed explanation of what this PR should do

## Additional Information

- decisions that were made
- notice of future work that needs to be done

## Testing

- How should reviewers verify this PR?

### CODE REVIEW

**Comment by emyl3** [comment]
Blocked until this is resolved: https://github.com/CDCgov/prime-simplereport/issues/7560

**Comment by DanielSass** [comment]
Looking at the terraform error, does the azure function not support node 20?

**Comment by emyl3** [comment]
> Looking at the terraform error, does the azure function not support node 20?

@DanielSass Commented above but made a ticket here https://github.com/CDCgov/prime-simplereport/issues/7560 and marked this one as blocked until this is complete

**Comment by emyl3** [comment]
closed in favor of https://github.com/CDCgov/prime-simplereport/pull/7595

**Pull request closed without merging**
