### PR TITLE
center queue loading message and match background color

### PR DESCRIPTION
**Pull request by zdeveloper**
## Related Issue or Background Info

- queue page loading screen is off to the side

## Changes Proposed

- center loading patients message
- match website background color

## Screenshots / Demos
current behavior

https://user-images.githubusercontent.com/4952042/133451078-c0f5daf3-126b-4060-8699-83ccf5037201.mp4

proposed behavior

https://user-images.githubusercontent.com/4952042/133509432-4a07c417-9e6b-449e-ae37-92b6258433e4.mp4

### UI
- [ ] Any changes to the UI/UX are approved by design 
- [ ] Any new or updated content (e.g. error messages) are approved by design 

### Testing
- [ ] Includes a summary of what a code reviewer should verify

### Changes are Backwards Compatible
- [ ] Database changes are submitted as a separate PR
  - [ ] Any new tables that do not contain PII are accompanied by a GRANT SELECT to the no-PHI user
  - [ ] Any changes to tables that have custom no-PHI views are accompanied by changes to those views
        (including re-granting permission to the no-PHI user if need be)
  - [ ] Liquibase rollback has been tested locally using `./gradlew liquibaseRollbackSQL` or `liquibaseRollback`
- [ ] GraphQL schema changes are backward compatible with older version of the front-end

### Security
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

## Cloud
- [ ] DevOps team has been notified if PR requires ops support
- [ ] If there are changes that cannot be tested locally, this has been deployed to our Azure `test`, `dev`, or `pentest` environment for verification

### CODE REVIEW

**Review by nickclyde — APPROVED** [review]
Nice!!

**Comment by kenieh** [comment]
Nice lean addition! I'm guessing this is a short-term solution until the load time improves? 

Here are a few easy tweaks we can do to improve the message's visibility. Right now, the navbar stands out more than the message, making it difficult to spot the loading message. 

- Increase font-size to 22px
- Increase spacing between the text and the navbar by 80px
- Feel free to use the rem equivalents of px for these

Screenshot of these changes:

Screen Shot 2021-09-15 at 9 07 31 AM

@Rebecca-LM @zdeveloper what do you think about the phrase "Loading patients..."? Would it be more accurate to say "Loading tests..." or "Loading test environment"?

___________

For future context, we do have a loading pattern that can be repurposed for loading situations such as this. I'm assuming we just want a lean design for the time being?

Screen Shot 2021-09-15 at 9 08 07 AM

**Comment by zdeveloper** [comment]
@kenieh i think that '`Loading tests ...`' makes more sense too, but ill defer to @Rebecca-LM 

btw, this data doesnt take a long time to load, but it shows up for a few miliseconds (I slowed it down for video purposes) but in the old style it causes a flicker since the background color would change rapidly

**Comment by Rebecca-LM** [comment]
> @kenieh i think that '`Loading tests ...`' makes more sense too, but ill defer to @Rebecca-LM
> 
> btw, this data doesnt take a long time to load, but it shows up for a few miliseconds (I slowed it down for video purposes) but in the old style it causes a flicker since the background color would change rapidly

@zdeveloper Agree on the "Loading tests ..." as the best option here. Please make sure there is a space before the three dots, per AP style. Thanks!

**Pull request merged**
