### PR TITLE
Upload submission detail view UI changes

### LINKED ISSUE #3888: Add test results top nav to submission detail view
### Description

#3864 added a top nav bar to the `/results/upload` pages to easily navigate from and within the bulk submissions views. However, this nav was not added to the "view submission detail" view:

### Acceptance criteria
- Add the results nav component
- Remove mention of `COVID-19`
- Use the correct loading indicator
    - Ask @vz3 about this, he mentioned on a call that the "loading" component used for the submission detail view isn't correct

### PR DESCRIPTION
**Pull request by mehansen**
# FRONTEND PULL REQUEST

## Related Issue

Resolves #3888 

## Changes Proposed

- add the test results top nav to submission view page
- update some copy and text formatting
- use a text loading indicator instead of the loading card
- fix paths for upload pages so correct subnav link is highlighted

## Additional Information

- ~this needs to wait for #3928 to be merged or vice versa because there will be some merge conflicts wrt where `prime-home` className is set~ done

## Testing

I'll deploy it to dev but it might be enough to just view the screen capture.
 
## Screenshots / Demos

https://user-images.githubusercontent.com/6401323/177837190-d06b2122-62f6-41d1-893f-863e7338faf8.mov

### Design
- [x] Any UI/UX changes have a designer as a reviewer, and changes have been approved
- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke-tested by both the engineering and design teams

### Content
- [x] Any content changes have been approved by content team

### Support
- [n/a] Any changes that might generate new support requests have been flagged to the support team
- [n/a] Any changes to support infrastructure have been demo'd to support team

### Security
- [n/a] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [n/a] Any dependencies introduced have been vetted and discussed

### Documentation
- [n/a] Any changes to the startup configuration have been documented in the README

### CODE REVIEW

**Review by nathancrtr — COMMENTED** [review]
This looks great! 🙌 

One thing I noticed is that we lose the current-location indicator on the top nav on this view (`CSV upload history` is not underlined). 
Screen Shot 2022-07-08 at 12 23 09 PM. Think it makes sense to add that in? (cc: @vz3)

**Comment by vz3** [comment]
yes please on the current page indicator for CSV upload history

**Comment by mehansen** [comment]
Latest iteration of the UI:
Screen Shot 2022-07-11 at 3 47 56 PM

cc @vz3 @nathancrtr

**Comment by mehansen** [comment]
Open to suggestions for better ways to form the URL, but both the upload list view and the detail view have to have `/results/upload/submissions` in their URLs for the CSV Upload history link to properly indicate that it's active

**Comment by nathancrtr** [comment]
It is a bummer to have the URIs be a little inelegant but oh well 🤷 I think it would take more effort than it's worth to unwind them at this point

**Comment by mehansen** [comment]
@vz3 also requested I update the back copy and icon on the CSV template guide to match the back copy on the upload details view ("<- Upload spreadsheet" and "<- Upload history", respectively). as I was doing this I noticed that no link in the subheader is active for the template guide. do we want Upload spreadsheet to be highlighted here?
Screen Shot 2022-07-12 at 4 24 29 PM

**Comment by mehansen** [comment]
I also noticed that we use the `usa-card__header` and `usa-card__body` classes in most of our other uploader pages, so I added that to get some uniformity in the spacing and margins. thoughts on whether I should keep or revert that? I wasn't sure if it looked a little funky on the detail view page since it doesn't have any header text
before:

https://user-images.githubusercontent.com/6401323/178616136-31ffe983-07a2-48c9-9c96-016f25f2219b.mov

after:

https://user-images.githubusercontent.com/6401323/178616176-04520f3f-46b5-4792-942c-1334cc13e42a.mov

**Comment by nathancrtr** [comment]
Re: https://github.com/CDCgov/prime-simplereport/pull/3949#issuecomment-1182600841: good question! Tagging @vz3

**Comment by vz3** [comment]
Yes please on Upload spreadsheet being indicated as current page

**Comment by mehansen** [comment]
Re-deployed to dev if any reviewers want to check it out

**Review by nathancrtr — APPROVED** [review]

**Review by vz3 — APPROVED** [review]

**Pull request merged**
