### PR TITLE
Enable patient bulk upload

### LINKED ISSUE #4937: Enable patient bulk upload for end users
### Background
Once all the code changes are in place for patient bulk upload, we'll need to enable the feature for end users instead of just superadmins.
 
### Action requested
Turn on patient bulk upload for end users. This should be a frontend-only change to alter what's visible on the Patient page.

### Acceptance Criteria
Patient bulk upload is visible and available to end users.

### Additional context
There are a few more patient bulk upload tickets to finish before this can be worked on, and we should do a final bug bash of the feature as well.

### PR DESCRIPTION
**Pull request by emmastephenson**
# FRONTEND PULL REQUEST

## Related Issue

- Fixes #4937 

## Changes Proposed

- It's finally here! Turn on patient bulk upload for standard users!

## Additional information

- Support team has been notified
- [#399](https://github.com/CDCgov/prime-simplereport-site/pull/399) and [#408](https://github.com/CDCgov/prime-simplereport-site/pull/408) on the static site will be merged as soon as this PR is merged.

## Testing

- Temporarily remove your "SR-DEV[X]-ADMIN" permission from the deployed environment and verify that you still have permission to bulk upload patients.

### CODE REVIEW

**Review by johanna-skylight — APPROVED** [review]
LGTM

**Comment by emmastephenson** [comment]
The lighthouse check failed because the performance score dropped, but the accessibility score was still fine. I also think the performance score issue may be a blip, as I'm not adding any new code 🤔

**Review by BobanL — APPROVED** [review]
Worked for me in dev3! Thank  you :D

**Review by emyl3 — APPROVED** [review]
YAY!!! Excited to have this out :D

**Pull request merged**
