### PR TITLE
Add CodeQL workflow from automated LGTM request.

### PR DESCRIPTION
**Pull request by rin-skylight**
# DEVOPS PULL REQUEST

## Related Issue

- Addresses automatic changes proposed in https://github.com/CDCgov/prime-simplereport/pull/4826.

## Changes Proposed

- Activate new CodeQL scanning workflow in a non-required state, so we can get initial results and determine formal procedures surrounding the scanning.

## Additional Information

- CodeQL reports a failed check as it has uncovered close to 100 findings on its initial scan. These are not _new_ vulnerabilities, but rather, the baseline that it will be working with moving forward.
- I've gone through and addressed any false positives that are also listed as high priority. All other items will need additional verification or mitigations.

### CODE REVIEW

**Review by BobanL — APPROVED** [review]

**Review by emmastephenson — APPROVED** [review]
Changes LGTM, but it is worth noting that this check will fail on all PRs until we get to a good baseline. I can create a ticket to address those issues.

**Comment by emmastephenson** [comment]
Ticket created to get us to a clean baseline: https://github.com/CDCgov/prime-simplereport/issues/4865

It is worth noting that when this PR is merged, I think all the detected issues will show up under the "Security" Github tab.

**Review by georgehager — APPROVED** [review]

**Comment by emmastephenson** [comment]
#4956 has been merged to address some of the high-profile CodeQL findings, but it seems as though the check here will still fail because of all the lower-level alerts being introduced. I'm hopeful that the check will only fail on this PR because everything is a new alert, but either way I'm comfortable merging this PR now.

**Comment by rin-skylight** [comment]
It looks like the failure was tied to three high-priority alerts that needed to be addressed. All seemed to be either irrelevant or some form of false positive; marking them as such made the associated check pass!

**Pull request merged**
