### PR TITLE
Bump netty-codec-http:4.1.55 to netty-codec-http@4.1.60+

### PR DESCRIPTION
**Pull request by snesm**
# BACKEND PULL REQUEST

## Related Issue

Vulnerabilities in obsolete netty-codec-http and netty-codec-http2

## Changes Proposed

Update Azure packages that are dependent on old netty-codec-http and netty-codec-http2 to:
    com.azure:azure-core-http-netty:1.11.9
    com.azure:azure-core:1.27.0
    com.azure:azure-storage-common:12.15.1
    com.azure:azure-storage-queue:12.12.1

## Additional Information
https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.27.0/sdk/core/azure-core-http-netty/CHANGELOG.md
https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.27.0/sdk/core/azure-core/CHANGELOG.md
https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.27.0/sdk/storage/azure-storage-common/CHANGELOG.md
https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.27.0/sdk/storage/azure-storage-queue/CHANGELOG.md

## Testing

- How should reviewers verify this PR?

## Checklist for Primary Reviewer

- [ ] Any large-scale changes have been deployed to `test`, `dev`, or `pentest` and smoke tested
- [ ] Any content updates (user-facing error messages, etc) have been approved by content team
- [ ] Any changes that might generate questions in the support inbox have been flagged to the support team
- [ ] GraphQL schema changes are backward compatible with older version of the front-end
- [ ] Changes comply with the SimpleReport Style Guide
- [ ] Changes with security implications have been approved by a security engineer (changes to  authentication, encryption, handling of PII, etc.)
- [ ] Any dependencies introduced have been vetted and discussed

### CODE REVIEW

**Review by nickclyde — APPROVED** [review]

**Review by rin-skylight — DISMISSED** [review]
I've tried deploying these changes to both `dev` and `pentest`, and both fail with timeouts waiting on the staging slot to be ready. I've confirmed the changes are isolated to this branch by attempting to deploy the contents of `main`, which succeeded without issue.

It looks like a compatibility issue exists with the updated Azure packages. We won't be able to merge this until versions are found that function appropriately. The Spring migration may take care of that, however.

I'd like to request either testing with different versions of the Azure packages, or closing this PR until after the Spring migration is complete.

**Comment by snesm** [comment]
@rin-skylight, thanks for the additional testing!

Was there any useful diagnostic from the process?

**Comment by rin-skylight** [comment]
I finally had some time to circle back and look at the logs on this...as it turns out, there were some infrastructure changes made since this PR went up, to account for some of our flexible DB work. This PR didn't have those changes, so the vnet link to the DB was being destroyed on each deployment.

@snesm , all you should have to do is pull `main` into this branch. I ran a test with that on a separate branch, and it seemed to clear the problem up. Your changes are perfectly compatible!

**Comment by snesm** [comment]
@rin-skylight: Oddly, there is  no Update Branch button and git pull of this branch says "Already up to date."

**Review by rin-skylight — APPROVED** [review]
Deployment tests pass! Thank you for getting this done.

**Pull request merged**
