### PR TITLE
add linting and use yarn in our app functions

### PR DESCRIPTION
**Pull request by BobanL**
# BACKEND PULL REQUEST

## Related Issue

- All of our projects use yarn except for our app functions
- There is no linting on our app functions

## Changes Proposed

- Add prettier & eslint
- Use yarn instead of npm

## Additional Information

- Since there is a lot of linting changes, [using github.dev](https://github.dev/CDCgov/prime-simplereport/pull/4729/files) maybe a better way to review this pr
- [The app still builds, deploys as expected.](https://github.com/CDCgov/prime-simplereport/actions/runs/3488964691/jobs/5838495691) 

## Testing

- Check the app function to ensure no unexpected errors occur. (100 test events were submitted at 10:45 am est on 11/17)

### CODE REVIEW

**Review by emyl3 — APPROVED** [review]
Thanks for deploying this and making things more uniform! I'm seeing no issues with this in the `QueueBatchedReportStreamUploader` function app monitor in Azure!
https://portal.azure.com/#view/WebsitesExtension/FunctionMenuBlade/~/monitor/resourceId/%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-dev%2Fproviders%2FMicrosoft.Web%2Fsites%2Freportstream-batched-publisher-dev4%2Ffunctions%2FQueueBatchedReportStreamUploader
Screen Shot 2022-11-17 at 10 58 43

**Review by georgehager — APPROVED** [review]
this looks good to me @BobanL! 🌮  might recommend doing a quick check with devops to see if there's a historical reason we used npm instead of yarn for functions.

**Comment by BobanL** [comment]
I've already ask @rin-skylight and she wasn't sure why it's like that. Maybe @emmastephenson or @zdeveloper would have more context?

**Comment by emmastephenson** [comment]
> > this looks good to me @BobanL! 🌮 might recommend doing a quick check with devops to see if there's a historical reason we used npm instead of yarn for functions.
> 
> I've already ask @rin-skylight and she wasn't sure why it's like that. Maybe @emmastephenson or @zdeveloper would have more context?

@BobanL My guess is that the function apps were just implemented in such a hurry we didn't make them standard to the rest of the application, but @zdeveloper might have more info.

**Review by emmastephenson — APPROVED** [review]
LGTM, thanks for cleaning this up!

**Pull request merged**
