### PR TITLE
Bump com.googlecode.libphonenumber:libphonenumber in /backend

### PR DESCRIPTION
**Pull request by fzhao99**
dependabot pull request that I closed / reopenned to kick the CI jobs that got stuck

### CODE REVIEW

**Comment by emyl3** [comment]
@dependabot rebase

**Comment by emyl3** [comment]
> @dependabot rebase

bob is not dependabot -- my bad! 😆

**Review by emyl3 — APPROVED** [review]
deployed to dev6 and updated a patient's phone number -- LGTM... Let me know if there's something else to test!

**Review by mpbrown — APPROVED** [review]
LGTM!

**Pull request merged**
