### PR TITLE
Johanna/6723 add destination disease columns upload table

### LINKED ISSUE #6723: Add disease and destination values to Uploads table
### Background
We have no visibility into what gets uploaded with our bulk results uploader except for the total count of records. It would be useful to know how many results we're sending of each disease and to what destination pipeline.

Uploads table currently holds record of all uploads made using the results bulk upload tool that passed our validations and were sent to ReportStream. We currently extract all Covid rows and send that to the Covid pipeline (or skip sending if no Covid rows) and then send the whole CSV converted to FHIR bundles to the Universal Pipeline and the Uploads table reflects that. You will see rows with the same submission ID and creation date and user info but often different record counts (record count will be the same if the CSV only has Covid rows). An upload will have status FAILURE if it was rejected by RS with errors. A failure response will also log to the Result Upload Error table.

### Action requested
Update the Uploads table with 2 new columns:
* disease (link to supported disease table)
* destination pipeline (string: COVID, UNIVERSAL)

For a bulk upload, log the record count per disease per destination pipeline.

Update the query for the upload history table such that the current behavior remains the same for the user. For each submission, there should be 1 row per pipeline submitted to and the record count should reflect the total records submitted to that pipeline.
We can probably achieve this by grouping by reportID and then aggregating the records count column. This should be done in the query that hits the table (no need to bring all the rows back and do it in the frontend).

#### Example
A csv with 2 covid rows and 1 fluA row and 3 rsv rows sends 2 rows total to the covid pipeline and 6 rows total to the universal pipeline.
In this case we should add 4 entries to the upload table:
reportID | submissionID | disease | destination | records count |
uuidA | uuid1 | covid | covid | 2 |
uuidB | uuid1 | covid | universal | 2 |
uuidB | uuid1 | fluA | universal | 1 |
uuidB | uuid1 | rsv | universal | 3 |
Notice that submission ID is the same but report ID (which we get in the responses from RS) will be different for each pipeline.

The upload history table would show two new rows in the UI.
reportID | records
uuidA | 2
uuidB | 6

### Acceptance criteria
* no regressions to logging to result upload errors table
* upload results history table behavior is the same to the user, both for uploads submitted after this change and previous uploads where the table does not have disease info
* when a user makes an upload, I can use Metabase to see the count of rows for each disease that is sent to each pipeline
* implementation should be easily extensible to more diseases

### PR DESCRIPTION
**Pull request by johanna-skylight**
# BACKEND PULL REQUEST

## Related Issue

- Resolves #6723 

## Changes Proposed

- Creates the model for the new table `UploadDiseaseDetails` and corresponding repository.
- Updates to `TestResultUploadService` include:
   - CVS validation logic moved to its own method.
   - Processing of the ReportStream response (covid and universal pipeline) have been moved to their own method.
   - Method `saveSubmissionToDb` now receives the destination pipeline and the disease/count breakdown.
- Creates auxiliary classes :
   - `FHIRBundleRecord` : contains the serialized fhir bundle plus the diseases/count breakdown as metadata.
   - `CovidSummisionSummary`: contains the RS response and other information relevant to covid reporting (e.g.: submissionId, org, destination).
   - `UniversalSummisionSummary`: contains the RS response and other information relevant to universal reporting (e.g.: submissionId, org, destination).
   - `Pipeline`: new type to represent COVID | UNIVERSAL pipeline names.
- `TestResultUpload` now uses the @builder annotation.
 

## Testing
Code is available in dev2.

- Upload a file and verify that the upload records and the disease details are correctly logged in our DB.
- Verify validations work as usual.

### CODE REVIEW

**Review by BobanL — DISMISSED** [review]
Changes look good! just one nit about the codesmells that sonar has identified.

**Comment by johanna-skylight** [comment]
I have address the feedback from Boban and Bob. New code is available in `dev2` thanks!

**Review by BobanL — APPROVED** [review]
😄

**Review by emyl3 — APPROVED** [review]
LGTM! Tested on dev2! RSV uploads look good and no regression with the upload history view

**Pull request merged**
