### PR TITLE
Print results

### PR DESCRIPTION
**Pull request by dmethvin-gov**
## Related Issue or Background Info

#426

## Changes Proposed

* Add menu selection for printing an individual result. 
* Creates an Actions Menu component that we can use in multiple places
  -  TODO: Patients menu should be refactored to use this
* Adds dialog for printing and print-specific styles
* Updates the information being printed and minimizes patient info per the ticket

## Additional Information

An early version of the code was already there but not accessible because the menu choice wasn't there.

* I kept the result printouts to a single page because I was encountering formatting issues when going to a second page. We are right at the edge with the length of the positive result description.
* To create a PDF the user will "print" the result using the computer's own print-to-PDF feature.
* You can print a result marked as error but it will show a watermark...I thought maybe people would need documentation of an error as well.

## Screenshots / Demos
Screen Shot 2021-02-17 at 12 20 11 PM

[SimpleReport-err.pdf](https://github.com/CDCgov/prime-simplereport/files/5997419/SimpleReport-err.pdf)
[SimpleReport-neg.pdf](https://github.com/CDCgov/prime-simplereport/files/5997420/SimpleReport-neg.pdf)
[SimpleReport-pos.pdf](https://github.com/CDCgov/prime-simplereport/files/5997421/SimpleReport-pos.pdf)

### CODE REVIEW

**Review by nickscialli-usds — COMMENTED** [review]
Noticed a few differences with the mockup located here: https://github.com/CDCgov/prime-simplereport/issues/426#issuecomment-776797248

**First:** The text in the note bulletpoints isn't the same, leading me to believe I might be looking at the wrong mock

If I'm looking at the right mock, the following comments apply, otherwise I'll do a new review when I'm looking at the right thing

- There is both a "Collection Date" and a "Test Date" in the mock but only a "Test Date" in this PR. The "Test Date" in the mock has the test time as well (hour/minute of day)
- The POSITIVE/NEGATIVE indicator in the mock is bold and either red or green.
- The links are formatted like links (blue, underlined). This would probably be free if they were actually links in the code.
- The title and list formatting of the "When to seek medical attention" section are different between the two.
- Sex is lowercased in the app `male` rather than uppercased `Male` like the mock

**Comment by dmethvin-gov** [comment]
These are good questions, I think most need @aliciabeckett-gov and @hmyers-cms to weigh in.

> There is both a "Collection Date" and a "Test Date" in the mock but only a "Test Date" in this PR. The "Test Date" in the mock has the test time as well (hour/minute of day)

I'm not sure whether we wanted both dates or not. At the point where I started this I think we only had Test Date but we've since added Collection Date. 

> Sex is lowercased in the app male rather than uppercased Male like the mock

I'll fix this.

> The POSITIVE/NEGATIVE indicator in the mock is bold and either red or green.

I can make it bold but there can be contrast issues with using colors. Also it's very possible that the printer at the facility will only be black-and-white so it will end up being a lighter grayish color. I wonder if we should explain the meaning of POSITIVE with a word or two? 

> The links are formatted like links (blue, underlined). This would probably be free if they were actually links in the code.

Since we're using the system print dialog I don't have a lot of control over whether they are actual links, and the printed copy won't be clickable even if saved as PDF.

> The title and list formatting of the "When to seek medical attention" section are different between the two.

That is where I had to trim the text to get it down to one page. I think it retains the same meaning but could use some more guidance on how important it is to have that exact longer content.

**Comment by aliciabeckett-gov** [comment]
We should remove Sex. The only PII can be name and DOB.

Making Positive/Negative bold is good enough for now.

> The title and list formatting of the "When to seek medical attention" section are different between the two.

This is fine. Let's ship it!

**Review by nickscialli-usds — APPROVED** [review]
:shipit: indeed!

**Pull request merged**
