### PR TITLE
Refresh the test queue every 10 seconds

### PR DESCRIPTION
**Pull request by jeskew-gov**
## Related Issue or Background Info

#418

## Changes Proposed

- Refreshes the TestQueue component at a fixed interval as a stopgap until we get subscriptions figured out.

## Additional Information

- I have not written any React code since before functional components were a thing, so my first impulse was to change `TestQueue` to be a class-based component with a timer set up in `componentDidMount` and torn down in `componentWillUnmount`. I *think* the idiomatic way to do this in a functional component/with hooks is with `useEffect`, but I'm not sure how to test this and would be open to suggestions there.

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
I'm surprised this works as well as it does! Each refetch causes a re-render of the entire queue since it gets a new object from the backend (even if it's the same data, it's a different JavaScript object). There are a bunch of odd artifacts that occur, for example if you have the `Device` dropdown open it redraws and might mess up the user's click. I tried to record it but this computer doesn't have the right permissions. None of those are related to hooks vs classes though, it's just a consequence of our very busy data stack to get to the server.

I also saw some strange behavior for the results radios, it would redraw 8 times flipping between the old and new choices, but eventually settle to the correct value. I'm not sure if there are some timing issues where it goes wrong. I can imagine some edge cases where the user has a local update that's clobbered, but tried some things and didn't see them happen. Obviously on a slower connection with multiple computers adding to the queue those kinds of problems might be more likely.

On balance I think it comes down the value of refreshing the queue. If it has to happen automatically and they don't mind the quirks then let's go for it and wait for feedback. I don't think we really got a good description of why this was a valuable feature, or at least I didn't understand the use case.

**Comment by jeskew-gov** [comment]
@dmethvin-gov The last time I worked on a react application, we used shallow equality checks w/ immutable.js-managed lists and objects in `shouldComponentUpdate` to avoid rerenders caused solely by reference inequality, but I'm not sure how that translates to functional components. 

If [this StackOverflow answer](https://stackoverflow.com/a/40910993) holds true in React 16, though, we might only be able to use that approach by migrating `QueueItem` and its children to be class-based components. The `refetchQueue` function passed down to each queue item might not be a stable reference anyway, which would make that effort moot.

**Comment by timothybest-usds** [comment]
I think the polling should be done with Apollo https://www.apollographql.com/blog/dynamic-graphql-polling-with-react-and-apollo-client-fb36e390d250/

Sounds like it will also fix the refresh issues

**Review by timothybest-usds — APPROVED** [review]

**Comment by dmethvin-gov** [comment]
If the user is editing something in the queue like the override date tested, the refresh clobbers the input.

**Comment by dmethvin-gov** [comment]
I can't reproduce the problem now so I'm not sure what was going on. After restarting and clearing several things it doesn't seem to be clobbering any data although the visual issues and unnecessary re-renders are still there. I think our longer term (sprint 10?) goal is to move to subscriptions backed by a local cache, which I think would solve most of these.

**Review by dmethvin-gov — APPROVED** [review]

**Pull request merged**
